### ISSUE TITLE
ASDF legacy converter system is being deprecated

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/specutils#1011]
- [ ] Also revert https://github.com/astropy/specutils/pull/1021 if applicable
- [ ] Also revert https://github.com/astropy/specutils/pull/1024 if applicable

ASDF if planning on releasing one final version of ASDF 2, version 2.15 which will be an LTS release. Several things in ASDF 2 are slated to be removed in ASDF 3, and so deprecation warnings are being added to these things as part of the 2.15 release.

In particular, the `asdf.types.CustomType` class is being deprecated (see asdf-format/asdf#1359 for details), which `specutils` uses here https://github.com/astropy/specutils/blob/34b5e84fd107f31a3c2fe2d1aaf95517d68d95f1/specutils/io/asdf/types.py#L20 Subclassing `CustomType` is how the legacy converter system for extensions ASDF operates.

The new converter system, based on the `asdf.extension.Converter` class, is the replacement for this system. Effectively, this means much of the `specutils.io.asdf` ASDF extension will need to be refactored in a similar way to how https://github.com/astropy/asdf-astropy is a refactor of `astropy.io.misc.asdf` using this "new" converter system.

The ASDF maintainers are willing to assist `specutils` in performing this refactor.

[🐶](https://jira.stsci.edu/browse/AL-718)

Also see:

* #1006

**Comment by pllim** [comment]
Is SCSB still willing to work on this part? If not, please give me an example PR with the changes I need to make. Thanks!
