### ISSUE TITLE
RTD admin please rebuild latest

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#1028]
https://readthedocs.org/projects/specutils/builds/

Recent PRs are failing with what seems unrelated errors. I have a feeling that if you rebuild the "latest" from current `main`, you would also see the same failure. At the time of posting, "latest" is 1.5 weeks old.

- [x] Need new ndcube release with sunpy/ndcube#600
- [x] https://github.com/sunpy/ndcube/issues/604

**Comment by rosteen** [comment]
I think it's due to https://github.com/sunpy/ndcube/issues/598
