### ISSUE TITLE
FluxConservingResampler returning incorrect fluxes and errors

### ISSUE THREAD

**Issue by cshanahan1** [astropy/specutils#1059]
I am seeing a difference between the fluxes and errors returned by FluxConservingResampler and what is described in https://arxiv.org/abs/1705.05165, which this resampler should be implementing. Particularly, I see this in certain cases when there are uneven size bins (including the example that is used in the class docstring), but it may be more general than that and occur in any cases with partial overlap. 

For example lets say we want to resample wavelengths = [3, 5, 13]*u.nm, with fluxes [2.5, 4.5, 8.5]) * u.AB onto new output grid [ 2, 6, 10]  * u.AA. A visual representation of this is:

<img width="770" alt="Screen Shot 2023-05-16 at 5 04 55 PM" src="https://github.com/astropy/specutils/assets/20444899/5a3732d6-f92e-49f1-92a3-3eeb45c0e78e">

According the the flux conserving routine, the output fluxes should be [nan 4.5 7.5]. However, FluxConservingResampler is returning [nan, 4.5, 7.81].

I think the source of the error is the following: The resample matrix for this case as computed by FluxConservingResampler, which SHOULD represent, for each overlapping input, output bin the fractional overlap * the width of the input bin (i.e P_ij * w_i) is
[[ 0.  0.  0.]
 [ 0. 20.  0.]
 [ 0.  5. 24.]]
which appears to have an additional factor of w_i in it, and when you do the math you get a flux of 7.81

when this additional factor of w_i is removed, you get the correct flux of 
[[ 0.  0.  0.]
 [ 0. 4.  0.]
 [ 0.  1.  3.]]

((1 * 4.5) + (3 * 8.5)) / (3 + 1) = 7.5 for the last bin

A sanity check, stepping through each iteration in the method described in the paper, for each output bin, we have to find the fraction of each overlapping input bin that will contribute to the final flux.

**output bin 0 (centered at 2, edges 0 to 4)**
   - goes out of range of input bins. flux should be nan.
   **TOTAL FLUX IN OUTPUT BIN 0 = NaN**

**output bin 1 (centered at 6, edges 4 to 8)** 
   - does not overlap input bin 0. no contribution to flux
   - overlaps input bin 1 (centered at 5, edges 4 to 9)
       - what fraction of input bin 1 is inside output bin 1? 0.8.
       - (fraction of input bin in output (P_ij) * width of input bin (w_i) = 0.8 * 5 = 4.0
       - P_ij * w_i * flux_i = 4.0 * 4.5 = 18.0
   - does not overlap input bin 2.
   **TOTAL FLUX IN OUTPUT BIN 1 = 18.0 / 4.0 = 4.5**

**output bin 2 (centered at 10, edges 8 to 12)**
   - does not overlap input bin 0. no contribution to flux
   - overlaps input bin 1 (centered at 5, edges 4 to 9)
       - fraction of input bin 1 inside output bin 2 = (overlap area/ area input bin 1) = 0.2
       - (fraction of input bin in output (P_ij) * width of input bin (w_i) = 0.2 * 5 = 1.0
       - P_ij * w_i * flux_i = 1.0 * 4.5 = 4.5
   - overlaps input bin 2 (centered at 13, edges 9 to 17)
       - fraction of input bin 2 inside output bin 2 = (overlap area / area input bin 2) = 0.375
       - (fraction of input bin in output (P_ij) * width of input bin (w_i) = 0.375 * 8 = 3.0
       - P_ij * w_i * flux_i = 3.0 * 8.5 = 25.5
   **TOTAL FLUX IN OUTPUT BIN 2 = (4.5 + 25.5) / (1.0 + 3.0) = 7.5**

Stepping through and calculating by hand shows that the correct flux should actually be 7.5.

This error also impacts the output uncertainties as they use this same resampling matrix when calculated. Fixing this will require the truth values in the unit tests to be updated.

**Comment by pllim** [comment]
Fixed in #1060
