### ISSUE TITLE
Spectrum1D velocity_convention documentation appears wrong.

### ISSUE THREAD

**Issue by mpound** [astropy/specutils#1067]
The documenation for Spectrum1D says that the velocity_convention parameter should be one of {“doppler_relativistic”, “doppler_optical”, “doppler_radio”},   However OneDSpectrumMixin appears to want {"relativistic", "optical, "radio"}  i.e., without "doppler_".    Minimally failing example:

import numpy as np
from specutils import Spectrum1D
import astropy.units as u

npts = 1000
x = np.arange(npts)
restfreq = 110.20137\*u.GHz
xfreq = restfreq+(x-npts//2)*10\*u.kHz
y = np.random.rand(npts)
s = Spectrum1D(flux=y\*u.K,spectral_axis=xfreq, rest_value = restfreq,
             velocity_convention='doppler_radio',radial_velocity=25\*u.Unit('km/s'))
s.velocity

This will raise 
AttributeError: module 'astropy.units.equivalencies' has no attribute 'doppler_doppler_radio'.

If instead, velocity_convention matches what OneDSpectrumMixin wants:
s = Spectrum1D(flux=y\*u.K,spectral_axis=xfreq, rest_value = restfreq,
             velocity_convention='radio',radial_velocity=25\*u.Unit('km/s'))
s.velocity
[correct quantity printed here]

I'm assuming this is just a documentation error and not an inconsistency between Spectrum1D and OneDSpectrumMixin.

**Comment by rosteen** [comment]
Thanks for reporting this, sorry for the delay in replying - I'm trying to catch up on some issues and will hopefully get this fixed this week.
