### ISSUE TITLE
Update tests to account for Numpy 2.0 changes

### ISSUE THREAD

**Issue by rosteen** [astropy/specutils#1070]
See https://github.com/astropy/astropy/issues/15095 - Numpy 2.0 is changing their string representation, which will break some tests. There will likely be other Numpy 2.0 issues to fix in the future, but this is the one I know about now...

**Comment by pllim** [comment]
Actually maybe you don't run doctest enough to be affected. I don't see any numpy 2.0 related failures in your devdeps log. Just #1072 but then again maybe after you fix up the remote data links, some might crop up, so let's keep this open until we can be sure.

**Comment by pllim** [comment]
https://github.com/astropy/specutils/actions/runs/5719752980/job/15529937564 is all green now and claims to use numpy `2.0.0.dev0+666.g452d3ad4c` so you are definitely not affected.
