### ISSUE TITLE
TST: SDSS remote data file link is broken

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#1072]
Example log: https://github.com/astropy/specutils/actions/runs/5719752980/job/15498297211

http://das.sdss.org/spectro/1d_26/0273/1d/spSpec-51957-0273-016.fit

`urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by pllim** [comment]
@weaverba137 , do you know anyone from SDSS data server that can help with this? Thanks!

**Comment by weaverba137** [comment]
Are the failures ongoing, or was it just one? I just downloaded the spSpec file successfully.

**Comment by pllim** [comment]
When I click on that link manually on browser, nothing happens. I don't get a download prompt or nothing. I am not within any SDSS internal network, FWIW.

**Comment by weaverba137** [comment]
I clicked on the exact link above and the file appeared in my Downloads folder. It is a valid FITS file.

**Comment by pllim** [comment]
Hmmm... nothing appears in my Downloads. I am using Chrome.

Programmatically, it downloads no problem with `requests` and `astropy.utils.data.download_file`, so for the purpose of CI, could the SDSS server be flagging the CI here as spam and blocked it?

**Comment by weaverba137** [comment]
I've sent an email to SDSS about it.

**Comment by weaverba137** [comment]
The server was down last week due to a cooling issue, but should be fixed now. I notice that other tests pass.  Is the one failure the only one that fetches remote data?  Or do other tests fetch remote data and this maybe has something to do with Python 3.11?

**Comment by weaverba137** [comment]
I don't know when the server was actually fixed. The test was last run yesterday.

**Comment by pllim** [comment]
OK let's rerun it then: https://github.com/astropy/specutils/actions/runs/5719752980 🤞

**Comment by pllim** [comment]
Aha, green now. Thanks for your help! 😸
