### ISSUE TITLE
DOC: Broken link to old mailing list needs to be fixed

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#1075]
Example log: https://github.com/astropy/specutils/actions/runs/5922597630/job/16056813261

https://mail.scipy.org/pipermail/numpy-discussion/2010-July/051760.html is broken now. Remove it or replace it.

**Comment by rosteen** [comment]
I'm trying to figure out where this link is even coming from, it's driving me crazy. Grepping the `specutils` project directory doesn't find anything 😵

**Comment by pllim** [comment]
Then it probably inherited from parent class docstring? 🤔

**Comment by pllim** [comment]
Yup... https://github.com/sunpy/ndcube/blob/7f5c8cafbce95c6def7905ef2fb139752cafccc7/ndcube/ndcube.py#L1013

https://github.com/sunpy/ndcube/pull/632

**Comment by pllim** [comment]
Fixed upstream. Probably need them to release for this to eventually go away.
