### ISSUE TITLE
Specutils in the muler and gollum ecosystem and prospect for upstreaming

### ISSUE THREAD

**Issue by gully** [astropy/specutils#1077]
Hi `specutils`! 👋👋 👋
Thank you for your nice framework!!  We (me, @kfkaplan, @ericasaw, @SujayShankarUT, and others) are a community of developers and users of specutils who have built two frameworks around specutils: 
- [muler](https://github.com/OttoStruve/muler),  a fluent-interface (lightkurve-like method chaining) API for echelle spectroscopy (with HPF, IGRINS, and Keck NIRSPEC supported currently)
- [gollum](https://github.com/BrownDwarf/gollum/), a fluent-interface API for precomputed synthetic spectral models (with PHOENIX and Sonora supported currently)

Both of these frameworks rely heavily on specutils by using Spectrum1D as a parent-class, and then wrap specialized functionality tailored to our use cases.  We have evolved to a point that we feel it important (and exciting and productive!) to have some cross talk with specutils core developers.  

I am not certain what form this should take, but for one we think we may have some ideas for functions to upstream, and and at a minimum we represent a devoted userbase of your nice package, so we have some perspective that may be useful from a user-testing / user experience point of view.

Maybe a good first step is to 1) get on your radar that we exist ✅ , and 2) gauge what level of engagement you all could be willing to support.  I know @bmorris3 and @eteq, but I don't think I've ever met @rosteen or @pllim before.  Would one or multiple of you all be open to chatting with us?

Best wishes,
--`muler` and `gollum` team

ps, pinging @kelle because she would be happy this exchange is happening and may have encouraged it some months ago.  🙏

**Comment by pllim** [comment]
Thanks for reaching out! Will also want to ping @tepickering here.

Please also feel free to reach out to the communication channels listed in https://www.astropy.org/help as you see appropriate.

**Comment by rosteen** [comment]
Also posted on Astropy Slack, I made [a when2meet poll](https://www.when2meet.com/?21749877-ukNpp) to see if we can figure out a good time to meet about this next week. Please mark your availability there.

**Comment by gully** [comment]
Woohoo! We had a nice remote meeting this week.  The notes from the meeting are summarized on here:

https://github.com/OttoStruve/muler/issues/149

I'll close this Issue now, since there is no action to be taken, and any future work can open new PRs and Issues.  Thanks again for the nice meeting!
