### ISSUE TITLE
Why are SDSS spPlate readers "hidden" in the sdss.py loader?

### ISSUE THREAD

**Issue by weaverba137** [astropy/specutils#1094]
The `__all__` object in `specutils.io.default_loaders.sdss` does not list `spPlate_identify` or `spPlate_loader`. Is this just an oversight?  If so, I'd be happy to submit a quick PR to just add those.

**Comment by rosteen** [comment]
I don't know of any history here for why it could have been intentionally left out, I would assume it's just an oversight. Thanks for bringing it up, if you want to open a PR I'll be happy to review/merge.
