### ISSUE TITLE
Create a reader for DESI data files

### ISSUE THREAD

**Issue by weaverba137** [astropy/specutils#1103]
This issue is simply a reminder to add support for reading DESI spectrum files.

There are two types:

1. `spectra` files may contain multiple observations of the same astronomical object.
2. `coadd` files co-add all observations of the same astronomical object into one spectrum.

Both files have very similar structure, the only real difference would be metadata.

Feel free to assign this to me.

**Comment by kelle** [comment]
Could you upload two sample files?

**Comment by weaverba137** [comment]
The files are > 1GB typically, so here are *links* to example files, chosen at random from the public data:
* https://data.desi.lbl.gov/public/edr/spectro/redux/fuji/healpix/sv3/dark/260/26065/coadd-sv3-dark-26065.fits
* https://data.desi.lbl.gov/public/edr/spectro/redux/fuji/healpix/sv3/dark/260/26065/spectra-sv3-dark-26065.fits
