### ISSUE TITLE
write_fits fails with lookup table WCS

### ISSUE THREAD

**Issue by Raindogjones** [astropy/specutils#115]
Having created a spectrum with Spectrum1D, using a lookup table as the WCS, write_fits then fails with:
'Spectrum1DLookupWCS' object has no attribute 'write_fits_header'

Thanks,
Dave

**Comment by wkerzendorf** [comment]
@Raindogjones Hi Dave, FITS does not support standard lookup tables for writing. I suggest writing to a text file.
