### ISSUE TITLE
fit_lines center window does not work

### ISSUE THREAD

**Issue by TurboSlayer** [astropy/specutils#1160]
Using a single value for `window` in `fit_lines` causes the program to use the entire spectrum as opposed to centering around the mean of the gaussian. Defining the window bounds manually works as expected. I've tried putting in some extreme constants into `window` such as np.inf and negative numbers, all of which have no effect on the line fit.

Defining a window of 10 by setting bounds manually:
```python
g_init = models.Gaussian1D(amplitude=2000, mean=6563 * u.AA, stddev=3 * u.AA)
g_init += models.Const1D(0)
g_fit = fit_lines(spectrum, g_init, window=(6553 * u.AA, 6573 * u.AA))
```
![bounds_window](https://github.com/user-attachments/assets/14221505-602b-47fd-baae-dac3ead80527)

Defining a window of 10 automatically:
```python
g_init = models.Gaussian1D(amplitude=2000, mean=6563 * u.AA, stddev=3 * u.AA)
g_init += models.Const1D(0)
g_fit = fit_lines(spectrum, g_init, window=10 * u.AA)
```
![center_window](https://github.com/user-attachments/assets/0ec014b5-1fdf-4919-aeef-d435bc3780a4)

**Comment by rosteen** [comment]
Thanks for the report, I'm hoping I'll have time to look into this next week.
