### ISSUE TITLE
Spectrum1D.from_fits and Spectrum1D.from_ascii should not exist

### ISSUE THREAD

**Issue by astrofrog** [astropy/specutils#117]
Spectrum1D.from_fits and Spectrum1D.from_ascii should not exist - instead, `specutils` should be defining readers/writers via the unified I/O interface and registering them for the `Spectrum1D` class.

`Spectrum1D` should inherit from the `NDIOMixin` class to enable this.

@wkerzendorf - was there a reason for not doing this that I am missing?

**Comment by wkerzendorf** [comment]
@astrofrog - yep there was a reason - when this was built `NDIOMixin` did not exist :wink: . Thanks for the heads-up I actually didn't know about this.

**Comment by astrofrog** [comment]
@wkerzendorf - np :) let me know if you need any help in defining the readers/writers!

**Comment by wkerzendorf** [comment]
@astrofrog yes definitely. Currently it seems also that modeling has changed again and it seems specutils has issues again. I'm also travelling, which doesn't help the issue :frown:
