### ISSUE TITLE
Combining and rebinning of spectra

### ISSUE THREAD

**Issue by indiajoe** [astropy/specutils#120]
Do we plan to add features to combine (average, sum, etc.) 1D spectra?
For that, first we will need to implement function to rebin/interpolate spectrum to various dispersion points. (This will be the tricky part to make sure flux/counts etc are conserved.)
After that I believe a spectra combiner will be straight forward.

**Comment by wkerzendorf** [comment]
@indiajoe Yes we were thinking about using https://github.com/astrofrog/reproject as it will work on similar WCS objects that specutils is using.

**Comment by wkerzendorf** [comment]
We definitely welcome some help there!

**Comment by indiajoe** [comment]
@wkerzendorf Thanks. that sounds nice. I have never used reproject before, so I shall look into that package.
