### ISSUE TITLE
Spectrum1DLookupWCS incorrectly returns NaN for the first dispersion pixel

### ISSUE THREAD

**Issue by nhmc** [astropy/specutils#123]
See example below. It must be related to how the lower limit is applied in np.interp.

``` python
>>> import astropy.units as u
>>> import numpy as np
>>> from specutils import Spectrum1D

>>> wave = np.arange(10.) * u.AA
>>> flux = np.ones_like(wa)
>>> spec = Spectrum1D.from_array(wave, flux)
>>> spec.dispersion
<Quantity [ nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.] Angstrom>
```

**Comment by keflavich** [comment]
I think this is actually kinda correct - you can't have a wavelength of 0 angstroms

**Comment by nhmc** [comment]
The same thing happens with any value for the start wavelength.

**Comment by wkerzendorf** [comment]
@nhmc maybe an unstable modelling problem again. are you using both dev versions of astropy/specutils?

**Comment by nhmc** [comment]
The problem is with numpy.interp:

``` python
>>> np.interp(1, [1, 2], [2, 2], left=np.nan)
nan
```

**Comment by nhmc** [comment]
I started making a branch to make a workaround for this problem, but discovered there's more cleaning up that needs to be done in specwcs.py before that small change can be made.

Also I found the example usage of Spectrum1DLookupWCS in the README no longer appears to work: 
```
lookup_table_wcs = specwcs.Spectrum1DLookupWCS(wave, unit='angstrom') # create the wcs
lookup_table_wcs(0) # doing the transformation for pixel 0
<Quantity 6000.0 Angstrom>
Spectrum1D(flux=flux, wcs=lookup_table_wcs)
Spectrum1D([ 0.66118716,  0.39584688,  0.81210479, ...,  0.5238203 ,
             0.05986459,  0.11621466])
```
These examples should be added as tests.

**Comment by wkerzendorf** [comment]
@nhmc am still travelling will take a look at this when I come back.

**Comment by nhmc** [comment]
That would be great, thanks.

**Comment by nhmc** [comment]
It turns out this is a bug introduced by numpy 1.10 (see numpy/numpy#6468).

**Comment by wkerzendorf** [comment]
@nhmc thanks for checking this out. I will probably fix some other issues with ole streicher in the next few days.
