### ISSUE TITLE
Problem with specutils on linux

### ISSUE THREAD

**Issue by mgennaro** [astropy/specutils#133]
Hi I have been using the specutils package without problem on my MAC. Now I want to run some code on a linux server and the same code gives me this problem:

---> 10 from specutils.extinction import extinction_ccm89 as ext_ccm89

/home/gennaro/anaconda3/envs/astroconda/lib/python3.5/site-packages/specutils/extinction.py in <module>()
     18 
     19 
---> 20 from specutils import cextinction
     21 
     22 try:

ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/gennaro/anaconda3/envs/astroconda/lib/python3.5/site-packages/specutils/cextinction.cpython-35m-x86_64-linux-gnu.so)

Any suggestion/help?
Thanks,
Mario

**Comment by gcupani** [comment]
Same problem here.

**Comment by wkerzendorf** [comment]
Actually, I think that means that your system is outdated and does not support the newer glibc that is needed (that's what I gathered from a quick google search).

**Comment by gcupani** [comment]
Thank you, that was the case indeed.
