### ISSUE TITLE
Release bump?

### ISSUE THREAD

**Issue by jhunkeler** [astropy/specutils#137]
Hi,

I am including the `specutils` package into AstroConda but hit a minor snag in the process. Tag v0.2 cannot be built under Python 3.5.2 due to the `distutils.config.ConfigParser()` bug in `setup.py`. However, the problem has been fixed in the `master` branch, so would it be possible for you to generate a v0.2.1 tag so that people can build/distribute `specutils` using the latest interpreter?

Thank you for your time.

Joe

**Comment by nmearl** [comment]
Thanks, @jhunkeler. I put in an issue yesterday (#135) for this.

**Comment by nmearl** [comment]
@eteq @astrofrog @mwcraig How do you guys feel about this?

**Comment by jhunkeler** [comment]
@nmearl Ah sorry, I didn't realize you had.

**Comment by keflavich** [comment]
Solved by #135.  I've needed this too.

**Comment by mwcraig** [comment]
Could someone please open a PR at  https://github.com/astropy/conda-channel-astropy to update the specutils version once the new version is uploaded to pypi?

**Comment by keflavich** [comment]
@mwcraig: done: https://github.com/astropy/conda-channel-astropy/pull/47
