### ISSUE TITLE
Masked arrays

### ISSUE THREAD

**Issue by bmorris3** [astropy/specutils#142]
Question: I see that the `mask` attribute on `Spectrum1D` can be used to store a mask for the wavelength/flux arrays, but those wavelength/flux attributes currently are not returned as masked arrays. Is that a planned feature in the future, or is the `mask` attribute just there to hold a mask, but not to return wavelengths/fluxes as masked arrays?

**Comment by bersavosh** [comment]
Hi there,
I see this issue as closed, but I'm wondering about the same thing and cannot find any answers. Specially because even after feeding the flux as a masked array (using `numpy.ma`), `specutils` seems to ignore the mask, which is really odd.

**Comment by pllim** [comment]
I also have the same question. Re-asked in #585 .

**Comment by eteq** [comment]
I don't know for sure why this was closed back in the day without that explanation, but hopefully the explanation in #585 (https://github.com/astropy/specutils/issues/585#issuecomment-586449541) suffices!
