### ISSUE TITLE
Update Astropy affiliated package info

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#156]
As requested by @mwcraig, please update `specutils`'s entry in the link given below.

"Please take a look at the information for your affiliated package at https://github.com/mwcraig/astropy-affiliated-numfocus-blog and edit the yml file there to add a bit more information information about your package: a representative image, a link to educational materials (e.g. a notebook or tutorial or ...) and an update of your packages description, if it is out of date or missing." -- Matt Craig

**Comment by eteq** [comment]
(done in mwcraig/astropy-affiliated-numfocus-blog#14)
