### ISSUE TITLE
Plans for python2 support

### ISSUE THREAD

**Issue by bsipocz** [astropy/specutils#161]
While sorting out the test matrix, I wonder about the plans for the python and numpy support?

**Comment by nmearl** [comment]
I think that the main use of specutils will be a part of a broader workflow or pipeline depending on a user's use case. With that in mind, I think we should support python 2, at least until EOF, just to ensure inter-operability with users' current setups.

**Comment by bsipocz** [comment]
Python2 support has been dropped already, so I'm closing this issue now.
