### ISSUE TITLE
logging not imported in specutils/specutils/io/default_loaders/tabular_fits_writer.py

### ISSUE THREAD

**Issue by Morisset** [astropy/specutils#163]
import logging
is missing in the file  specutils/specutils/io/default_loaders/tabular_fits_writer.py

**Comment by SaOgaz** [comment]
It doesn't look like the other writer has logging either, only the readers.  Should it have logging?  @eteq, @nmearl?

**Comment by nmearl** [comment]
If it's necessary, sure. @Morisset is there some debug message you're expecting in this particular loader?
