### ISSUE TITLE
Cannot find the specutils.extinction package

### ISSUE THREAD

**Issue by HeloiseS** [astropy/specutils#164]
Hello,

I was looking for specutils.extinction.reddenning and when I followed the downloading procedure on the README file (that  clones the github repo) I didn't find it. I can't see it on the Github either. 
I was asked on twitter by Steven Crawford to create an issue and told that I could find what I was looking for in the legacy branch. 

Cheers

**Comment by nmearl** [comment]
That is correct. The current master branch of specutils is completely different that the previous version. You'll have to switch branches in your locally cloned package:

First, change directories to your cloned copy:
```bash
$ cd specutils
```

Then, checkout the legacy branch:
```bash
$ git checkout legacy-specutils
```

Then, install the package again:
```bash
$ python setup.py install
```

Alternatively, the legacy version of specutils is available on the python package index. You could remove your cloned copy of specutils and instead simply run:
```bash
$ pip install specutils
```

**Comment by eteq** [comment]
@HeloiseS - you may want to check out https://github.com/karllark/dust_extinction though.  Moving forward the *tentative* plan is that that will include support for working with specutils spectrum objects.
