### ISSUE TITLE
Feature Request: Port some spectroscopic tools from IRAF

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#165]
Is this the right place for such a request? The request was, "... spectrum analysis tasks such as `standard`, `sensfunc`, `identify`, and `reidentify`... I hope in future we will have sophisticated Python library for spectrum analysis."

c/c @SaraOgaz

**Comment by crawfordsm** [comment]
Somewhat of a port of `identify` is available here: 
https://github.com/crawfordsm/specidentify 
It can be updated to handle just about any spectrograph, but it is currently lacking in documentation.

Eventually we hope to add more tools to:
https://github.com/astropy/specreduce
but no work has really been done on that yet.

**Comment by eteq** [comment]
@pllim @SaraOgaz - agreed in a broad sense! First, let me bring to your attention #167, where there's a link to the project where we are starting to scope out the various planned tools for specutils.  

Note, though, that some of this belongs better in `specreduce`.  The scope of `specutils` is meant to be limited to "I have a spectrum that's been reduced and want to do stuff with it", while specreduce is "I have a raw output from my instrument and need to do ccd reductions, flat-field, wavelength cal, and so on.   `identify,  `reidentify`, and  `sensfunc`  *might* belong better in `specreduce, but `standard` is a bit more debatable...?

**Comment by eteq** [comment]
Hah, my comment collided with @crawfordsm - but hopefully similar content :wink:

**Comment by pllim** [comment]
OK, the replies sound promising. Thanks! I think what is a good start might be a "conversion" table and status of each task. Example row: `identify | specidentify | available`

**Comment by crawfordsm** [comment]
That's definitely a good idea -- maybe start something on the `specreduce` wiki pages?  That would probably be a good place and hopefully most things start getting added into specreduce

**Comment by pllim** [comment]
I went to `astropy/specreduce` but nothing happens when I click on "Wiki"; it just silently reload the "Code" page.

**Comment by bsipocz** [comment]
@pllim - that probably means that the checkbox for "wikis" in the settings/features is not clicked.

**Comment by pllim** [comment]
Okay, I don't have admin rights to `specreduce`, so someone who is admin there need to create the Wiki first. Thanks!

**Comment by tepickering** [comment]
for reference, we kickstarted ``specreduce`` development during #pyastro18 so hopefully that will continue to snowball. we also fleshed out its roadmap at https://github.com/astropy/specreduce/projects/2.

**Comment by eteq** [comment]
After looking at what's in https://github.com/astropy/specreduce/projects/2 and comparing to the list in this issue, I think there's really only one thing left that belongs in `specutils`, which I will create as a separate issue that's more focused and then close this one (but link to this one so in the future others can see it).

**Comment by pllim** [comment]
We still need a conversion guide somewhere but I don't know where is the best place for this.

**Comment by nmearl** [comment]
Conversations concerning the translation of comparable iraf tasks to the spec tools should occur in the specreduce repository (specifically spacetelescope/specreduce#40).

**Comment by pllim** [comment]
After two years, I still cannot find a good IRAF conversion guide for this when I get help calls. Is there one somewhere? Thanks!
