### ISSUE TITLE
Latest development version on master is out of date

### ISSUE THREAD

**Issue by drdavella** [astropy/specutils#166]
The latest released version of this package is `0.2.2`, which implies that the latest development version of this package should be something like `0.2.3.dev`. However, it is currently set in both `setup.cfg` and `setup.py` to be `0.1.dev`.

This causes a problem for packages that want to build against a development version of `specutils` but express a requirement for something at least as recent as `0.2.2`.

**Comment by nmearl** [comment]
The new specutils is not a continuation of the previous specutils, which has been retired as `legacy-specutils`. Packages using legacy specutils should not be building against a development version of this package. Once this new specutils is released, users wishing to use the legacy specutils will have to explicitly build against the legacy version.

**Comment by bsipocz** [comment]
That being said, it may be worth consider to have a jump in the version numbers, e.g. start from 0.3 or 0.5 or even 1.0, so the discontinuation is clear (and the new release thus cannot be confused with the 0.1 release of the legacy one)

**Comment by drdavella** [comment]
It's also worth considering whether this version bump should happen on the `legacy-specutils` branch, if not `master`.
