### ISSUE TITLE
Implement spectrum Analysis and Manipulation tools

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#167]
This is a "meta issue", covering a large swath of work to follow after the baseline `Spectrum1D` from the Specutils APE is implemented.

There are a wide range of spectral analysis and manipulation tools to be implemented in specutils.  The basic guideline is that they shouldn't be *too* domain-specific or experimental, but that's just a guideline and is open to debate on any specific case.

To see specific tasks, look at the `specutilsutils` project board:
https://github.com/astropy/specutils/projects/1

Detailed discussion of specific issues should be in those issues (cards in the project board can be promoted to issues at any time).  This issue is for "meta discussion" of the overall effort, only.

**Comment by pllim** [comment]
Is `specutilsutils` a typo or ...? :wink:

**Comment by bsipocz** [comment]
it's a shame that @adrn is not more involved in spectroscopy :)

**Comment by keflavich** [comment]
No.  Intentional.

**Comment by SaOgaz** [comment]
@eteq, should we close this in favor of #234?

**Comment by nmearl** [comment]
Declaring this closed in favor of #234.
