### ISSUE TITLE
Data loaders need prioritization to resolve multiple matches

### ISSUE THREAD

**Issue by sean-lockwood** [astropy/specutils#171]
When trying to associate an identifier with my particular type of FITS file, the loader cannot decide between the generic FITS loader and my STIS-specific FITS loader.

```
IORegistryError: Format is ambiguous - options are: cubetest1, stis-format, tabular-fits
```
[Location of error in AstroPy source code](https://github.com/astropy/astropy/blob/9626265d77b8a21c113615c08bc6782deb52eaed/astropy/io/registry.py)

My identifier:
```python
# Define an optional identifier. If made specific enough, this circumvents the
# need to add `format="my-format"` in the `Spectrum1D.read` call.
def identify_stis_fits(origin, *args, **kwargs):
    from astropy.io import fits
    import os
    import six
    
    if isinstance(args[0], six.string_types) and (os.path.splitext(args[0].lower())[1] == '.fits'):
        with fits.open( args[0]) as f:
            return f[0].header.get('INSTRUME', '') == 'STIS'
    else:
        return False
```

Glue gets around this by allowing the specification of [loader priorities](http://docs.glueviz.org/en/stable/customizing_guide/customization.html#custom-data-loaders).

**Comment by SaOgaz** [comment]
Do we want to use the loader priorities for this? Also, should we map this to an actual Astropy issues, since it seems like that's where this would need to be addressed? (@nmearl)

**Comment by aragilar** [comment]
I'm also interested in this, the current priority system sorts the loaders, but astropy always finds all possible loaders, and then assumes there will be only one possible option (unless a format option is provided). If astropy had a `use_first` option on read, then the priority system would work. I'll raise an issue on the astropy issue tracker, and link back to this.
