### ISSUE TITLE
Make a function to reverse Spectrum1D.flux values

### ISSUE THREAD

**Issue by eblur** [astropy/specutils#177]
Add a method to `Spectrum1D` that will allow one to change the `spectral_axis` units between wavelength and energy.

Example call:
```
import numpy as np
import astropy.units as u
from specutils import Spectrum1D

# Initiate a spectrum with wavelength
wavel_bin_centers = np.linspace(1.0, 40.0, 100) * u.angstrom
fake_counts = np.random.poisson(10.0, size=100)
myspec = Spectrum1D(spectral_axis=wavel_bin_centers, flux=fake_counts)

# ---- Proposed enhancement:
# Method for changing spectral_axis to a different energy unit
myspec.cast_spectral_axis(u.keV)
```

The method would change the `spectral_axis` to energy units (or wavelength), which includes reversing the order of the `spectral_axis` and `flux` array values. Will also need to check for case where `flux` quantity is in units of 1/wavelength or 1/energy.

**Comment by eblur** [comment]
Can it return the respective `Spectrum1D.flux` values for the desired spectral_axis unit?

**Comment by keflavich** [comment]
I'm not sure exactly what you're looking for.  Do you expect the flux values to change when the spectral axis values do?

Note that the spectral axis access tools are already implemented, e.g.:
https://github.com/astropy/specutils/blob/master/specutils/spectra/spectrum1d.py#L122

**Comment by keflavich** [comment]
I'm starting to see what you're getting at, but I think it needs to be done a bit differently.  It is perfectly valid to plot a flux in ergs/s/cm^2/angstrom vs frequency, for example, even if it's not very intuitive.

The tool you want might be something like `recast_flux_unit(myspec, spectral_unit=u.eV)`, which would then have a new flux unit.

**Comment by eblur** [comment]
How about `recast_flux_unit(myspec, spectral_axis_unit=u.eV)` because `spectral_unit` kind of sounds like you are changing the `flux` unit to eV and not, e.g., erg/s/cm^2/eV

**Comment by keflavich** [comment]
Good point.  Actually, it would need to be `recast_flux_unit(myspec, spectral_unit=u.erg/u.s/u.cm**2/u.eV)`, I think, since changing the spectral axis unit doesn't change the flux unit.

This should also be handled by some equivalency, e.g.:
`myspec.flux.to(u.erg/u.s/u.cm**2, equivalencies=u.spectral_density(100*u.AA))`.  However, it appears not to work for energy units at the moment, only wavelength/frequency... hrm.

**Comment by eblur** [comment]
Mmmm... but if the `flux` values are in unit-less, like the use-case I presented at the top of this thread, then the `spectral_unit` casting is meaningless.

I still insist on something like `recast_flux_unit(myspec, spectral_axis_unit=u.eV)`. This will handle the ordering of the flux array values (which need to be reversed if you are switching between wavelength and energy).

**Comment by eblur** [comment]
It's for X-ray spectra. The response functions are always specified by energy space, whereas the spectrum files themselves are sometimes specified in energy and sometimes wavelength. There are no `flux` values, they are photon counts (unit-less).

In my current implementation of an X-ray spectrum object, I force the spectrum (`flux`) to be in stored in energy order because the response function will always provide values in order of energy.

This choice cannot be forced on `Spectrum1D` after initializing it. There is a probably an OOP  workaround, but the proposed method would make it significantly easier *and* be useful to some people (e.g. the specific flux example).

It's not about changing the flux units, it's about forcing the `flux` and `spectral_axis` units to be tied together in a correct way.

**Comment by eblur** [comment]
I see why you're confused. The plot examples I gave would actually be fine because the convenience functions return the spectral_axis values in the original order.

This will still be an issue for dealing with X-ray responses, but I will try fixing it from the astropy.units end. However, please keep this issue open for now. I'll close it when I'm satisfied!
