### ISSUE TITLE
setup.py develop failures

### ISSUE THREAD

**Issue by tepickering** [astropy/specutils#183]
when doing a fresh install of specutils, i ran ``python setup.py develop`` and it generated a slew of errors that ended with:
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```
immediately re-running the same command then worked as expected. on another computer, ``python setup.py develop`` failed with a different complaint about invalid PYTHONPATH.  running ``python setup.py install`` did work and ``develop`` worked after that.

**Comment by nmearl** [comment]
> when doing a fresh install of specreduce

`specreduce` or `specutils`?

**Comment by bsipocz** [comment]
This was a template/helpers issue, can't recall exactly, but ping me if you still see it once the template files are updated (I've seen you have a PR for that already).
