### ISSUE TITLE
Documentation does not show the simplest way to read a FITS file.

### ISSUE THREAD

**Issue by simontorres** [astropy/specutils#185]
When starting to experiment with specutils/Spectrum1D the documentation can be confusion because it goes directly to [how to write a custom loader](http://specutils.readthedocs.io/en/latest/custom_loading.html) and skips the simplest way of reading which is reading a fits file with a standard WCS.

**Comment by simontorres** [comment]
there is a pull request with an addition of an example on how to simply read a fits file. The text should be improved though.

**Comment by SaOgaz** [comment]
Looks like this can be closed, since it was addressed in #232. Sound good to you @simontorres?

**Comment by simontorres** [comment]
Indeed, though the PR has not been merged. Feel free to close it if you think that is not relevant.

**Comment by SaOgaz** [comment]
Oh whoops, for some reason when I looked at the PR I thought it was merged, not sure what I was thinking.

**Comment by rosteen** [comment]
Looks like this never got closed after the relevant PR was merged. The docs have been updated, this can be closed.
