### ISSUE TITLE
Flux unit conversion

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#197]
Confirm the ability to convert flux units. This should leverage astropy units etc.

**Comment by eteq** [comment]
Can you clarify what exactly you are thinking needs to be added beyond the already-existing units support in `Spectrum1D`, @brechmos-stsci? That is, do you think some specific methods need to exist on `Spectrum1D`?

**Comment by nmearl** [comment]
@robel

**Comment by robelgeda** [comment]
This feature already exists in the current code [here](https://github.com/astropy/specutils/blob/master/specutils/spectra/spectrum_mixin.py#L77). Some enhancements to the function can be made. The two features I we discussed are:

- [ ]  Ability to pass in custom equivalencies. This feature would have been very helpful in the CubeViz sprints when converting b/w none standard flux units such as `Jy / spaxel` to `Jy / arcsec2`
- [ ] Ability to change the units without converting the data. This will come in handy when you know the initialized units do not match the data values. This will reset or override the stored units.

**Comment by brechmos-stsci** [comment]
@eteq We talked, but just to put here.  I just wanted to be sure the basic functionality is there for other projects that will use this. Also, too, to add any tests that might benefit the flux unit conversion part of the repo.  If this is all done, awesome :).

**Comment by brechmos-stsci** [comment]
@robelgeda I suspect it is going to be best to keep things consistent (with WCS), but others will have to give you a better answer. :)

**Comment by nmearl** [comment]
@robelgeda No need. The wcs representation in specutils does not store information about the flux, only the dispersion.

**Comment by SaOgaz** [comment]
Is this basically done except for the tests? @brechmos-stsci @robelgeda?

**Comment by robelgeda** [comment]
@SaOgaz : this should be closed.
