### ISSUE TITLE
Implement initial value guessing for line fitting

### ISSUE THREAD

**Issue by nmearl** [astropy/specutils#201]
Re-implement initialization functions for making preliminary guessing to be fed into the astropy modeling machinery. (Currently initializer functions exist in the specviz repository.)

**Comment by eteq** [comment]
@brechmos-stsci  has this on his plate as part of the line-fitting work

**Comment by brechmos-stsci** [comment]
Parameter estimation was added in via PR https://github.com/astropy/specutils/pull/362
