### ISSUE TITLE
List of Collaborators 

### ISSUE THREAD

**Issue by robelgeda** [astropy/specutils#204]
Just following up from the morning tag up, here are a list of accounts that will be contributing to this repo. (I may have forgotten some so please feel free to add more)
 
@nmearl 
@brechmos-stsci 
@robelgeda
@javerbukh 
@SaOgaz
@mfixstsci
@astrofrog 
@drdavella

CC: @kassin @eteq

**Comment by astrofrog** [comment]
Note that if not all need write access to the repository, but need to be assigned, there are ways to make separate read-only and read/write teams. Read only teams can be assigned but can't merge PRs.

**Comment by nmearl** [comment]
@astrofrog Seems like they can all be added to the astropy contributors team, which already allows read access?

**Comment by SaOgaz** [comment]
Is this still an outstanding issue @nmearl?

**Comment by bsipocz** [comment]
@SaOgaz - Some of those accounts still need to be added to the contributors team (well, in case they need to be assignable to issues/PR reviews), that can only be done by someone with an org admin access (e.g. @eteq or @astrofrog).

**Comment by astrofrog** [comment]
I just invited @brechmos-stsci @robelgeda @javerbukh and @mfixstsci to the astropy contributors team so that they can be assigned
