### ISSUE TITLE
add specutils logo to docs header

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#211]
In #200, the specutils docs header was changed to say "specutils" instead of package-template.  @bsipocz pointed out that it really ought to also have the logo.  This is a good idea (and should be straightforward given that #205 is in), but requires a bit of css modification.  

Really the package-template/theme should be updated to allow this, though. If that's easy it should be done at the same time, if it's hard it can be done later and just manually adjust the css in specutils a la what photutils already does.

**Comment by robelgeda** [comment]
I am working on this and it looks like some css edits need to be done to `astropy-sphinx-theme` to allow this. I am not really sure how to do this but will use the photutils solution for now. I will also create a ticket on `astropy-sphinx-theme`
