### ISSUE TITLE
Contributing link links to matplotlib page.

### ISSUE THREAD

**Issue by simontorres** [astropy/specutils#213]
It is not clear to me why the link at the end of the front page in readthedocs points to a page about [contributing to matplotlib](https://matplotlib.org/devel/contributing.html#contributing) . Was this a place holder or this page is intended to be the guide for contributing to specutils?

**Comment by bsipocz** [comment]
Thanks for finding that. The intersphinx links have apparently get messed up, it indeed should point to https://specutils.readthedocs.io/en/latest/contributing.html?highlight=contributing
