### ISSUE TITLE
API not documented/automodapi missing

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#219]
There's no "reference/API" section in the docs, so that means none of the docstrings are being generated into the sphinx docs.  That should be fixed by adding an `automodapi` call.

**Comment by eteq** [comment]
I'm assigning myself and will try to do this ASAP, but if I haven't gotten to it within a couple days someone else can feel free to try to tackle it!

**Comment by bsipocz** [comment]
@eteq #218 adds quite a few `automodapi` calls, and also sets up good measures to make sure we spot typos, wrong links on the way...

**Comment by SaOgaz** [comment]
This has been done throughout a few other PRs. Checked with @eteq before closing.
