### ISSUE TITLE
High-level API question: import direct from specutils or no?

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#220]
This is a very broad question we should probably have an answer for as soon as possible since it has rather wide implications for the user experience. There are two basic options I'm thinking about: 

1) In some of the other affiliated packages (most notably `photutils`), all of the "real" functions are imported into the base package.  E.g., for `specutils` that would mean `from specutils import Spectrum1D, equivalent_width`.  That has the advantage that it's relatively easy for users - they just need to do `import specutils` and `specutils.<whatever>` gets them whatever they need.  

2) However, in other Python packages (most relevantly `astropy` itself), the "real" functions are usually at least one import in.  So e.g. `from specutils.spectra import Spectrum1D` and `from specutils.analysis import equivalent_width`.  That is a bit more of a burden to users to be more verbose in imports, but makes more organizational sense so users can "discover" functionality more easily.  It also has the advantage that you don't necessarily import everything all at once (desirable for e.g. `astropy` where imports take a non-trivial time, something that *might* be true for specutils in the future).

This has consequences for the examples (which should follow whichever we choose), the reference/API docs (which should present to the user one or the other of these cases but not both), and the "public API": any guarantee we make of API stability is only with respect to which of the above we choose, *not* any internal reorganization (this comes up a lot in `astropy` if we reorganize a sub-package but it turns out someone didn't know that the layout is an implementation detail).

What this issue is *not* about: the actual layout of `.py` files.  We definitely should lay out the files more like in 2) - that makes it much easier to develop the code.  But we can use the `from .whatever import *` trick to make that all *look* like case 1) - it's entirely a question of what user interface to present.

**Comment by eteq** [comment]
cc @crawfordsm @keflavich @nmearl @bsipocz @astrofrog @brechmos-stsci @simontorres @kelle @eblur @SaOgaz - long list but since this is a pretty major user-facing decision I think nows a good time to get a variety of opinions...

(This shouldn't hold up active development right now, but it should be decided ASAP so that we can make things consistent once a decision is made)

**Comment by bsipocz** [comment]
I personally (when being the user) like the structured layout better, so I can have a better control what to import, and kind of also see what is coming from where. But I acknowledge this is very likely a minority preference, so unless you foresee a real chance that top level import time becomes non-trivial, either solution is fine by me.

Also, I see a 3rd way to do it, have the very very basic functionality that is more likely to be needed for all use cases, e.g. `Spectrum1D` etc at top level, but structure the more specialized functionality one layer down.

**Comment by brechmos-stsci** [comment]
@eteq My personal opinion is to have at least one, and maybe at most two layers.  It gives structure as to what as where and could help distinguish between different types of methods (measurement, manipulation, core functionality).  It think a flat structure would make the namespace a little hard to understand.

I really like scipy as it seems organized (at least to me) and each set of functionality is in its own namespace.

**Comment by eblur** [comment]
I do not have strong opinions on the subject.

I agree with Brigitta that having Spectrum1D and a few other base classes and functions imported at the top level is ideal. More specialized items could be kept one layer deeper (but not more than that). 

Perhaps there will be more debate around which classes and functions are considered "base".

For me, I will be happy as long as the documentation is good and up-to-date.

**Comment by simontorres** [comment]
I would prioritize code development over making imports slightly simpler for the user. 
- as a user I can live with a longer import, is just a small amount of effort compared to a full  tool/script. I also agree that it can not be more than _two levels down_ 
- I would not use the trick of `from something import *`, I would rather have everything that will be put on top level imported individually, if this is going to be a problem, then option 1 has no chance to occur. I would do

```python
from something import (lib1,
                       lib2,
                       etc)
```

**Comment by astrofrog** [comment]
I would say for now we only import some of the important classes to the top level (e.g. ``Spectrum1D``) and leave the rest in sub-modules. We can always choose to import them to the top level later. I agree with others that we should only have one level of sub-modules though.

**Comment by SaOgaz** [comment]
I don't feel super strongly either, but like @bsipocz's suggestion the best so far.  It seems very reasonable to me to have at least the `Spectrum1D` object at the top level.

**Comment by crawfordsm** [comment]
I'm indifferent, but we should also consider that one day we may want to move `Spectrum1D` and the specutils functionality into astropy core and so it might be best to have it resemble how it might look then.

**Comment by SaOgaz** [comment]
It seems like we have a majority agreement with @bsipocz, but should we leave this issue open for further discussion?

**Comment by hamogu** [comment]
Also +1 for @bsipocz

**Comment by nmearl** [comment]
Going forward it's been implicitly decided to take the approach in which functions belonging to an obvious module are accessed through that module (`from specutils.analysis import equivalent_width`), while top-level data containers are accesible through the `specutils` namespace (`from specutils import Spectrum1D, SpectralCoord, SpectralRegion`).
