### ISSUE TITLE
Should Spectrum1D be allowed to be created without a spectral_axis?

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#221]
I just noticed that `Spectrum1D` objects can be created without a `spectral_axis`.  My view is that this is *not* what we want: a spectrum isn't really a spectrum if it's just flux without any wavelength/frequency/etc.  So I'm inclined to say this just isn't allowed.  What do other others think?

**Comment by nmearl** [comment]
I believe the previous version of specutils also did not allow creating a spectrum object without a dispersion solution. We could either error (as in the previous iteration), or simple simple create a generic solution that's something like `np.arange(len(self.flux))`.

**Comment by crawfordsm** [comment]
Even if you are in pixel space, that would still be your spectral_axis.  It would just be in units of 'pixels' and if a user tried to access  `Spectrum.wavelength` that would fail with an error as there isn't a conversion.

**Comment by SaOgaz** [comment]
From a newer spectrum users perspective, I would be very puzzled if I could create a `Spectrum1D` object with no `spectral_axis`.  And I would find an auto-default dispersion to be a bit confusing as well.  How likely is it that the `spectral_axis` would actually be an arange list?  Or are there instances where someone only has the flux and just needs to do something with it, not caring what the `spectral_axis` is?

**Comment by simontorres** [comment]
I think the case would be when you don't have a wavelength solution, you still need a dispersion axis. In other words is not that you don't care about what the spectral axis is, is that you just can't define it in terms of physical units. Do you agree @nmearl and @crawfordsm ?

**Comment by nmearl** [comment]
I think defaulting to pixel space if no explicitly dispersion solution is provided is reasonable.
