### ISSUE TITLE
Implement "line cut-out" function for equivalent width/flux measures

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#222]
The `equivalent_width` function already in specutils only accepts a spectrum, with no keywords to "cut out" parts of an existing spectrum.  I think that's a feature not a bug, and `flux` should be done the same way... we need to implement easy ways to do "cut outs", but we should do that instead of baking it into the analysis functions.

That said, one thing that *is* useful for both fluxes and (to some extent) equivalent width measurements, is to be able to specify passbands on either sides of a line, which are then fit as a continuum (usually linear, but possibly constant or possibly something like a higher degree polynomial) and then the measurement is done on the line either continuum-sutracted or continuum-normalized. That "pre-operation" of taking a larger spectrum, fitting a continuum, subtracting/dividing by it, and then cutting out just the "line" part, should be provided as a high-level convenience function.  It should use the same continuum-fitting machinery we will need for full-spectrum (and single line) fitting, but should be available as a one-liner because it's a very commonly-needed operation.

**Comment by nmearl** [comment]
Perhaps another issue for discussing the continuum fitting, since that functionality wouldn't be dependent on this "cutouts".

Speaking of which, what do you _mean_ by "cutouts"? Are you alluding to masking out certain regions, or literally generating new spectrum objects given e.g. spectral axis ranges?

**Comment by nmearl** [comment]
Related to #245.

**Comment by eteq** [comment]
I think this has been dealt with by the spectral region functionality, so closing. (#248 + #289)
