### ISSUE TITLE
Remote test data

### ISSUE THREAD

**Issue by crawfordsm** [astropy/specutils#223]
It would be useful to be able to run regression tests against the different formats of files that we are adding.  It would also be useful to have some developer documentation about how to add those files and tests for those different formats.

**Comment by crawfordsm** [comment]
cc @eteq on whether we should store this in https://github.com/astropy/astropy-data

**Comment by bsipocz** [comment]
Some docs live here in the core repo: http://docs.astropy.org/en/latest/development/testguide.html#working-with-data-files

**Comment by bsipocz** [comment]
@crawfordsm - either there, or following photutils' example create a separate datasets repo, e.g `specutils-datasets`:

https://github.com/astropy/photutils-datasets

**Comment by simontorres** [comment]
I like @bsipocz 's last idea

**Comment by nmearl** [comment]
I'll mirror a comment I made on a PR: I'm not a fan of the separate-repo-to-store-data model. I'd much prefer that we use git lfs to deal with large files, as that does not put up any extra barriers to contributors writing tests and having to maintain associated data

**Comment by bsipocz** [comment]
@nmearl - How often do contributors need to add data files to the repo compared to the ones whose contributions use the files already available? If the test data was set up with a good selection of data types this shouldn't be a big issue.
The infrastructural machinery to deal with the external repo is readily available following the example of either astropy/photutils/gammapy/etc, so not that much of a maintenance burden imo.

**Comment by nmearl** [comment]
@bsipocz Your points make me more convinced that setting up a separate repo is unnecessary. For a contributor who wants to add new test data, the git lfs requires only installing the command line extension to begin adding large data to the repo, and the data would be added in a way that makes sense, not confined to a separately managed repo. For a contributor who doesn't need to add data, they only have to concern themselves with a single repo. So for a nice set of data already available, a general contributor won't even be aware that the data isn't technically a part of the package (as git lfs only stores a pointer).

**Comment by bsipocz** [comment]
@nmearl - I'm not sure I follow. With my suggestion they don't need to worry about any data files or repos unless they add new data. The access will be dealt with `get_pkg_data_filename`, `download_file`, and alike util functions.

The other option requires git lfs as a dependency for everyone otherwise they will get only text pointers but not the data files. Or at least this was the case last time (not recently though, so this may have changed) I've checked how git lfs works. Also, I'm not sure whether that case any tests would work for standalone released versions, as I suspect the suggestion doesn't include bundling the data files into a release.

So, I still feel this dependency is a much higher barrier for random contributors than the occasional need to add new data files, and enlarges the size of releases unnecessarily.

**Comment by nmearl** [comment]
Apologies, I was away on travel for the past few weeks.

> With my suggestion they don't need to worry about any data files or repos unless they add new data. The access will be dealt with get_pkg_data_filename, download_file, and alike util functions.

I was unaware of the extent to which astropy built out functionality for retrieving data from a remote repository -- this is certainly very useful. The issue with this is that we'd still be maintaining two separate git histories for something that effectively should be a single continuous history (the package and its test data).

> The other option requires git lfs as a dependency for everyone otherwise they will get only text pointers but not the data files.

Unless a contributor _needs to add new test data or use test data_ git lfs would not be a dependency. It would be fine for them to only have pointers. Likewise, a user who is not interested in retrieving the test data need not clone with git lfs, (or if they have git lfs installed and are still not interested in cloning with the data, to set the flag to avoid downloading the lfs data).

> Also, I'm not sure whether that case any tests would work for standalone released versions, as I suspect the suggestion doesn't include bundling the data files into a release.

This is a good point: releases would need to have the test data bundled with them in order for the user to run the tests from a hosted distribution channel. But I'm not quite convinced of this use case -- a user interested in running the tests probably should be using a cloned version of the code, as I'd imagine most local testing would be done via some command akin to `python setup.py test`. However, if you mean a simple tagged release version, then there really is no issue: the git lfs data gets associated with that particular tag as well, and is available in the same way as discussed above.

I admit that git lfs really shines in the case of package-necessary data, not necessarily package **test* data. While I still think we should be leveraging the tools already available, like git lfs, to handle large data files, if the astropy community is already implementing this maintain-a-separate-repo in managing tests we should continue that for no other reason than to ensure that contributors to one astropy package can use their experience equally well in contributing to another.

**Comment by bsipocz** [comment]
> 
>     The other option requires git lfs as a dependency for everyone otherwise they will get only text pointers but not the data files.
> 
> Unless a contributor needs to add new test data or use test data git lfs would not be a dependency. It would be fine for them to only have pointers. Likewise, a user who is not interested in retrieving the test data need not clone with git lfs, (or if they have git lfs installed and are still not interested in cloning with the data, to set the flag to avoid downloading the lfs data).

But not having the files will mean that they can't run the tests locally, or do I misunderstood something? So git lfs is really a mandatory thing for all the contributors (which can be OK, but when we talk about barriers of entry, this seems to be an extra one to add to the usual ones).

>     Also, I'm not sure whether that case any tests would work for standalone released versions, as I suspect the suggestion doesn't include bundling the data files into a release.
> 
> This is a good point: releases would need to have the test data bundled with them in order for the user to run the tests from a version of the package retrieved from a hosted distribution channel. But I'm not quite convinced of this use case -- a user interested in running the tests probably should be using a cloned version of the code, as I'd imagine most local testing would be done via some command akin to python setup.py test. However, if you mean a simple tagged release version, then there really is no issue: the git lfs data gets associated with that particular tag as well, and is available in the same way as discussed above.

I think @eteq has the most experience with this, getting users to run the tests to spot out irregularities with their setup, etc. But maybe this point is only important to the core package and less so for more specialized ones, such specutils

> I admit that git lfs really shines in the case of package-necessary data, not necessarily package test data. While I still think we should be leveraging the tools already available, like git lfs, to handle large data files, if the astropy community is already implementing this maintain-a-separate-repo in managing tests we should continue that for no other reason than to ensure that contributors to one astropy package can use their experience equally well in contributing to another.

Unfortunately the astropy machinery predates git lfs, I suspect we might have gone down a different route if that was available a few years earlier. Anyway, I'm necessarily arguing against it, but feel that we need check the pros and cons a bit more carefully.

**Comment by nmearl** [comment]
@eteq @astrofrog @bsipocz I'm about to include some new test data for #228, when any of you get the chance, could you set up a `spectuils-data` repo?

**Comment by astrofrog** [comment]
Just my £0.02 - unless the data are huge, it might make sense to put this in a specutils folder in astropy-data rather than making a whole new repo?
