### ISSUE TITLE
Splice algorithm test, looking for feedback

### ISSUE THREAD

**Issue by SaOgaz** [astropy/specutils#224]
Hi all,

I would like to post here a summary of what I've found comparing a current rough draft implementation of Spice in specutils (in a branch on @nmearl's fork) and start a discussion on the splice algorithm choice we would like for specutils, and possibly the design.  I ran through several example sets.  The jupyter notebooks with all the analysis are here if you want to take a closer look: https://github.com/SaOgaz/splice_explore

In terms of the current algorithm comparison,  I tried to map out the equivalent equations being used by the current Python implementation, and the IRAF one is listed in the help file.  I hope I got these right, but I'm not 100% sure I did.  Been a while since I've done Summation math.... top equation is IRAF, bottom is Python

<img width="959" alt="screen shot 2018-05-30 at 10 26 30 am" src="https://user-images.githubusercontent.com/5287848/40862436-84df1e8c-65ba-11e8-986f-ac2e78b028bb.png">

Now for the examples I ran through both versions:

**Ex1 - Non uniform spectral axis**  - Used some basic HST-STIS spectra with various non-uniform axis (basically an un-edited STIS data set)

**Ex2 - Uniform spectral axis** - For this I took a subset of two STIS spectra that had the exact same spectral axis, and replaced that spectral axis with an evenly spaced spectral axis (used a `np.linspace` call over the min and max spectral axis value).  I also ran an example providing the IRAF version of splice with an explicit output spectral axis, but the results were essentially identical to this example, so I probably won't post it here, but the notebook will be posted)

**Ex3- Weighted - Non uniform spectral axis**- A uniform spectral axis (same two STIS spectra) but this time I used weighting.  The weighting I applied was just a randomly generated (between 0 and 1) numpy array.  I used a different weighting array for each of the two spectra.

**Results** (wavelengths are in angstroms I believe.  IRAF results in blue, Python in orange. Flux diff stats have been normalized by the average IRAF Flux):

The weighted example at the bottom is where it gets interesting.  Let me explain a little what I've found.  In the IRAF version, the weighting is applied during the resampling summation.  So essentially the weights are applied in their "natural" form.  In the Python version, the weighting and the flux are both resampled separately, THEN all multiplied and average out.  Here's where I'm hoping I mapped out the summation equations correctly.  I was hoping someone with a more hardcore math background could tell me if these results are making sense, as this *could* effect how we design splice and do the resampling.

**Ex1 - Non uniform spectral axis**
![screen shot 2018-06-01 at 4 42 30 pm](https://user-images.githubusercontent.com/5287848/40862552-d9a168a8-65ba-11e8-9146-e183046204e9.png)

wavelength/flux summaries:
![screen shot 2018-06-01 at 4 48 43 pm](https://user-images.githubusercontent.com/5287848/40862807-a88d4a60-65bb-11e8-855a-614a7755bc52.png)

Flux diff stats (keep in mind for these that the output wavelength grid is not identical between IRAF and Python, so the flux difference aren't that representative, but including them anyway:
![screen shot 2018-06-01 at 4 45 51 pm](https://user-images.githubusercontent.com/5287848/40862667-41c1eea8-65bb-11e8-8eff-df9d17d7c425.png)

**Ex2 - Uniform spectral axis**
![screen shot 2018-06-01 at 4 50 35 pm](https://user-images.githubusercontent.com/5287848/40862887-ea951a50-65bb-11e8-9d1c-38aeae728406.png)

wavelength/flux summaries:
![screen shot 2018-06-01 at 4 50 56 pm](https://user-images.githubusercontent.com/5287848/40862904-f8afbe42-65bb-11e8-92f5-263ba2750a62.png)

Flux diff stats (these wavelength axis are identical, so flux diff is more fair to look at here):
![screen shot 2018-06-01 at 4 51 49 pm](https://user-images.githubusercontent.com/5287848/40862929-17b068dc-65bc-11e8-919e-35ff85473126.png)

**Ex3- Weighted - Non uniform spectral axis**
![screen shot 2018-06-01 at 4 54 08 pm](https://user-images.githubusercontent.com/5287848/40863019-6b42a708-65bc-11e8-8852-af9a06372a28.png)

wavelength/flux summaries:
![screen shot 2018-06-01 at 4 54 33 pm](https://user-images.githubusercontent.com/5287848/40863035-79a52c9e-65bc-11e8-8dc5-cbce8467354f.png)

Flux diff stats:
![screen shot 2018-06-01 at 4 54 55 pm](https://user-images.githubusercontent.com/5287848/40863050-888e853e-65bc-11e8-8a78-b6fb9a2f3c36.png)

@eteq @stscicrawford @nmearl @brechmos-stsci @hcferguson @keflavich

**Comment by hcferguson** [comment]
@SaOgaz I don't think the two equations are equivalent. The python one looks suspicious to me. 
The IRAF one is a little weird too, but I think I understand it when referring back to the [splice help page](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?splice). The thing that had me confused on first glance was ScalarWeight, but that seems to be a shortcut if all the pixels have the same weight. So I would give it just one index and not two, but no big deal. Also while it doesn't matter much, the Splice help has 
```      i   = index over input arrays
        j   = index over wavelength bins in each input array
        k   = index over wavelength bins in the output array
```
While your second (python) example reverses the meaning of ```i``` and ```j```. Anyway, your python example doesn't have ScalarWeight at all, which is fine at this stage. 

The main problem with the python example is that the weights are not being applied to the individual fluxes input, but only to the sum. Changing the notation for compactness, I think the following reflects the IRAF algorithm -- which looks correct to me:

<html>
<a href="https://www.codecogs.com/eqnedit.php?latex=\large&space;f_k&space;=&space;\frac{\sum_{i,j}&space;s_i&space;w_{i,j}&space;f_{i,j}&space;o_{i,j}}&space;{\sum_{i,j}&space;s_i&space;w_{i,j}&space;o_{i,j}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\large&space;f_k&space;=&space;\frac{\sum_{i,j}&space;s_i&space;w_{i,j}&space;f_{i,j}&space;o_{i,j}}&space;{\sum_{i,j}&space;s_i&space;w_{i,j}&space;o_{i,j}}" title="\large f_k = \frac{\sum_{i,j} s_i w_{i,j} f_{i,j} o_{i,j}} {\sum_{i,j} s_i w_{i,j} o_{i,j}}" /></a>
</html>

Where:
<html>
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{matrix}&space;i&space;&&space;{\rm&space;index\&space;over&space;\&space;input\&space;arrays}\\&space;j&space;&&space;{\rm&space;index&space;\&space;over&space;\&space;input\&space;wavelength\&space;pixels}\\&space;k&space;&&space;{\rm&space;index\&space;over\&space;output\&space;wavelength\&space;pixels}\\&space;s&space;&&space;{\rm&space;scalar\&space;weight\&space;(independent\&space;of\&space;wavelength)}\\&space;w_{i,j}&space;&&space;{\rm&space;input\&space;weight\&space;in\&space;wavelength\&space;bin\&space;j\&space;for\&space;spectrum\&space;i}\\&space;o_{i,j}&space;&&space;{\rm&space;overlap\&space;fraction\&space;of&space;pixel\&space;j\&space;in&space;spectrum\&space;i,\&space;with\&space;pixel\&space;k}\\&space;f_{i,j}&&space;{\rm&space;input\&space;flux\&space;in\&space;pixel\&space;j\&space;in&space;spectrum\&space;i}&space;\end{matrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{matrix}&space;i&space;&&space;{\rm&space;index\&space;over&space;\&space;input\&space;arrays}\\&space;j&space;&&space;{\rm&space;index&space;\&space;over&space;\&space;input\&space;wavelength\&space;pixels}\\&space;k&space;&&space;{\rm&space;index\&space;over\&space;output\&space;wavelength\&space;pixels}\\&space;s&space;&&space;{\rm&space;scalar\&space;weight\&space;(independent\&space;of\&space;wavelength)}\\&space;w_{i,j}&space;&&space;{\rm&space;input\&space;weight\&space;in\&space;wavelength\&space;bin\&space;j\&space;for\&space;spectrum\&space;i}\\&space;o_{i,j}&space;&&space;{\rm&space;overlap\&space;fraction\&space;of&space;pixel\&space;j\&space;in&space;spectrum\&space;i,\&space;with\&space;pixel\&space;k}\\&space;f_{i,j}&&space;{\rm&space;input\&space;flux\&space;in\&space;pixel\&space;j\&space;in&space;spectrum\&space;i}&space;\end{matrix}" title="\begin{matrix} i & {\rm index\ over \ input\ arrays}\\ j & {\rm index \ over \ input\ wavelength\ pixels}\\ k & {\rm index\ over\ output\ wavelength\ pixels}\\ s & {\rm scalar\ weight\ (independent\ of\ wavelength)}\\ w_{i,j} & {\rm input\ weight\ in\ wavelength\ bin\ j\ for\ spectrum\ i}\\ o_{i,j} & {\rm overlap\ fraction\ of pixel\ j\ in spectrum\ i,\ with\ pixel\ k}\\ f_{i,j}& {\rm input\ flux\ in\ pixel\ j\ in spectrum\ i} \end{matrix}" /></a>
</html>

This is equivalent to:

<html>
<a href="https://www.codecogs.com/eqnedit.php?latex=f_k&space;=&space;\frac{\sum_i&space;s_i&space;(\sum_{j}&space;w_{i,j}&space;f_{i,j}&space;o_{i,j})}&space;{\sum_i&space;s_i&space;(\sum_{j}&space;w_{i,j}&space;o_{i,j})}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f_k&space;=&space;\frac{\sum_i&space;s_i&space;(\sum_{j}&space;w_{i,j}&space;f_{i,j}&space;o_{i,j})}&space;{\sum_i&space;s_i&space;(\sum_{j}&space;w_{i,j}&space;o_{i,j})}" title="f_k = \frac{\sum_i s_i (\sum_{j} w_{i,j} f_{i,j} o_{i,j})} {\sum_i s_i (\sum_{j} w_{i,j} o_{i,j})}" /></a>
</html>

**Comment by SaOgaz** [comment]
I'm closing this issue, as we've now moved on with an actual implementation.  People can re-open if they feel differently.
