### ISSUE TITLE
Flux measurement

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#235]
Calculate the integral of the pixel intensities. 

This might be within a given region or the input spectrum will already be assumed to be the region over which the integral will be done.

**Comment by eteq** [comment]
Unlike most of the other starting analysis functions, this one requires a careful consideration of the *sub-pixel* effects on the edges.  @brechmos-stsci and I discussed this and we think the following is roughly what we want to assume as the core algorithm for how to compute this on a `Spectrum1D`:

1. sum up the *whole* pixels inside the relevant region  (see #245 on defining the "region"), multiply by d-whatever-the-`spectral_axis` is over those pixels (i.e. left edge of left whole pixel to right edge of right whole pixel)
2. for the "partial" pixels (left and right edge pixels), multiply the flux in that pixel by the fraction of the `spectral_axis` that the region includes.  That is, if pixel value 1.5 maps to 5999 angstroms, and 2.5 is 6001 angstroms, if the user asks for a region that begins at 6000, the contribution from the left pixel should be``flux[1] * 0.5*u.angstrom``.  This is still assuming a constant sub-pixel flux, but that's a reasonable assumption to start with.  It also means that if the spectrum is in pixels (i.e., not wavelength-calibrated), the sub-pixel operation will be a simple linear fraction, which is good.
3. The result should then be in proper flux units *only* if the spectrum is in the correct units for the `spectral_axis`.  If not, it's the user's responsibility to clean it up.  Later we might add some machinery to optionally automate the f_nu to f_lambda conversion, but that's for a second round.
