### ISSUE TITLE
EQW measurement

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#237]
Calculate the equivalent width measure.  

Notes:  W = Sum( (Fc-Fl)/Fc * dw, where Fc is the continuum flux per pixel, Fl is the line flux per pixel, and dw is the wavelength interval per pixel.

**Comment by eteq** [comment]
Note: this already exists in ``analysis/equivalent_width.py``.  But given #234 I think it probably makes sense to just replace that with something that's consistent with the full set of other "analysis" functions.

**Comment by eteq** [comment]
Should follow the region-selecting semantics shared globally (see #245).  Also one question here to consider is: how to decide the resulting units?  I think the assumption should just be "whatever `spectral_axis` is in".  That is, disallow a way for this function to return equivalent width in (say) pixels if the `spectral_axis` is angstrom (see e.g. #235 for related discussion that follows that convention)

**Comment by eteq** [comment]
Also important is that this be consistent with  #235 with respect to "edges" of pixels (i.e., fractional pixels).

**Comment by eteq** [comment]
This was implemented in #281 - forgot to close this!
