### ISSUE TITLE
Signal to noise measurement

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#239]
Calculate the signal to noise of the input spectrum.

**Comment by eteq** [comment]
@brechmos-stsci and I discussed this at length out-of-band.  We are thinking this is a good place to start as a way to resolve the questions in #245 without anything too complicated on the "algorithm" side.  So this one would simply compute ``np.mean(flux/uncertainty, axis=0) / u.pixel`` of a requested cutout region (which could default to ``None`` to mean "the whole spectrum").
