### ISSUE TITLE
Mean with in a region

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#243]
Calculate the mean flux intensity of a spectrum (possibly within a region) and should also allow the option of sigma clipping (based on astropy.stats sigma clipping).

**Comment by eteq** [comment]
I'm not convinced this should be implemented as a stand-alone function.  Instead it perhaps can simply be documented that the way do this is ``np.mean(spectrum.get_region(reg).flux)``?

**Comment by eteq** [comment]
Oh and I guess the snippet above is now (v0.4) `np.mean(extract_region(spectrum, reg).flux)`

**Comment by nmearl** [comment]
Closing in favor of #672.
