### ISSUE TITLE
Standard deviation of intensities with a spectrum

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#244]
The standard deviation of the pixel intensities in the region, with optional sigma clipping (to use astropy sigma clipping).

The region could either be passed in or a sub-set of the spectrum extracted and then passed into this method.

**Comment by eteq** [comment]
As with #243 , I'm not convinced this should be implemented as a stand-alone function.  Instead: ``np.std(spectrum.get_region(reg).flux)``?

**Comment by eteq** [comment]
Reading this more carefully, what is the purpose of this, @brechmos-stsci ?  I thought you meant the  *width* of a line, but now I see this is about the *flux*.  I wonder if this has been superceded by the uncertainty estimate thing in #248 ?  If so I think this can be closed.

**Comment by brechmos-stsci** [comment]
Hmmm.. no... not the width. For all of these "stats" things, I took them to mean a method that operates on a spectrum or region.  For this one, I took it as what you had in your comment, basically just a wrapper for np.std working on the flux.   (A mean and median could be useful too).

The reason to *actually* implement these (rather than let the user do it) would be to have it in the package for consistency of interface.

**Comment by eteq** [comment]
Ah, so in that case I'm not really in favor of this.  I think we don't want to add functions for consistency if there aren't science use cases driving them (so as to lower the maintenance burden).  But if we encounter a significant science case that requires this (bearing in mind also that it's a one-liner to do by hand... but that could still be a documentation thing).

**Comment by eteq** [comment]
For completeness, in v0.4 that would be `np.std(extract_region(spectrum, reg).flux)`

**Comment by nmearl** [comment]
Closing in favor of #672.
