### ISSUE TITLE
Document ways to define 1d spectrum regions (or make a class)

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#245]
For both the analysis tools (#234 and related sub-issues) and the line-fitting machinery, it's abundantly clear that we need a way to specify spectral "regions".  By that, I mean the two sides necessary to define a part of a spectrum in which to do a measurement, fit a line, define a continuum level, etc.  These need to be fairly flexible - e.g. they should accept pixel values *or* spectral values, so that you can cut out, say the area around a given spectral line with known wavele

To 0th order there are two ways to do this:

1. Define a class `SpectrumRegion`, which would then have methods that take a spectrum.  E.g.:
```
reg = SpectrumRegion(6400*u.angstrom, 6600*u.angstrom)
sub_spec = reg.cutout_spectrum(spectrum)
pix1, pix2 = reg.to_pixel(spectrum)
```
2. Have the region definition be simple objects like lists/tuples, but have the "useful" functionality be on the *spectrum*:
```
reg = [6400*u.angstrom, 6600*u.angstrom]
sub_spec = spectrum.cutout_spectrum(reg)
pix1, pix2 = spectrum.region_to_pixel(reg)
```

I originally had been advocating for 1, but @brechmos-stsci I think convinced me 2 is the way to go - that makes it so that the spectrum has more control over how the `cutout_spectrum` or `region_to_pixel` methods work, which is probably desirable.

The catch is that, with 2, it's harder to be certain all analysis functions consistently use the same "region" machinery, since there's not a single class to carry the information.  So we probably need a dedicated documentation page laying all this out explicitly for users to actually see it.

So in case 1, this issue can be viewed as "make `SpectrumRegion`, while for 2, this is "document how regions area defined".

cc @nmearl @crawfordsm @keflavich @brechmos-stsci

**Comment by keflavich** [comment]
I'm very firmly in favor of having a unified region functionality across astropy.  We have [recently](https://github.com/astropy/regions/pulls?utf8=%E2%9C%93&q=crtf) had CRTF regions, the CASA region format type, incorporated into astropy.regions.  These regions allow spectral selection in addition to spatial.  They might even support spectral-only selection, though astropy.regions doesn't do that yet.

I suggest that, whichever approach we take, we do the 'region' implementation in astropy.regions and import it here.

That said, I'm in favor of #2 above without considering the implications deeply.  It's just more directly how I think about the problem.

**Comment by eteq** [comment]
@keflavich - can you clarify what "regions" means for a 1D spectrum in the context of `astropy.regions`?  I *thought* all those formats you mentioned are for 2D objects - that is, there's no sense in using a complicated "region" specification that includes ellipses, polygons, circles, etc for a 1D region specification.

That said, I broadly agree with the idea of compatibility.  Is there something ready to be used *right now* from `regions` that is comparable to 1 or 2 here?  If not we might just go with 2 and then later on adapt that to `astropy.regions`?  As long as the logic to convert regions to pixels is sequesterd in one function (`Spectrum1d.region_to_pixel` in my toy example above), then that shouldn't be too bad.

**Comment by eteq** [comment]
(Oh, and just to be clear in case it isn't - here I'm talking about the *in Python* representation of the regions, not a serialization format on disk/table/etc)

**Comment by nmearl** [comment]
Depending on how complex the regions object might or might now be, in the simple case of defining a set of lower and upper bounds, we can extend the slicing on the spectrum object to handle not only pixel values, but unit values:

```
# Already supported
spec = Spectrum1D(spectral_axis=np.arange(1, 50) * u.nm,
                                  flux=np.random.sample(49) * 100)
reg1_spec = spec[5:10]  # Returns new `Spectrum1D` object

# Proposed
mn_bound, mx_bound = 5 * u.nm, 10 * u.nm
reg2_spec = spec[mn_bound:mx_bound]  # Likewise would leverage the slicing to return a new `Spectrum1D` object
```

Of course, more complicated slicing might need something more extendible.

**Comment by keflavich** [comment]
@eteq Nothing exists now, but this Issue plus the recently-implemented CRTF stuff highlights the need for something.  At the moment, the non-spatial axes are recorded as 'metadata' in the region objects, but eventually we'll want those to have some real meaning in the context of astropy.regions.

I am in favor of developing the spectral region code here and porting it to regions later.  At the moment, in spectral-cube, to take advantage of the spectral component of regions, we have to do some fairly awkward parsing:
https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/spectral_cube.py#L1877

**Comment by brechmos-stsci** [comment]
Currently in a PR I use regions defined as a tuple `( left * u.Quantity, right * u.Quantity )` and am passing them around.  

BUT, I wonder if it would make more sense to, now, create a super simple Region class that just encompasses the left and right idea.  Then it could be beefed up and changed as we gain understanding over the next little while on what is needed, but for now "region" could be a reasonably simple container class.

Actually, this would help in some other parts of the code I am working on currently.  For example `snr(spectrum, region=None)` allows region to be `None`, a single region e.g., `(1*u.um, 2*u.um)` or a list of regions.  But then in the code I have to parse out if the "list" is a 2-tuple type of thing or a list etc etc etc. If I do have the region class then I can just check for None, Region or list (of regions).

So, I would like to propose that I move this to an actual container class. I can implement this as part of the #248 which is what I am currently working on...

@eteq @keflavich

**Comment by eteq** [comment]
There is now a SpectralRegion (#248 + #289), so this can be closed I think.
