### ISSUE TITLE
Continuum subtraction

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#246]
This is a place-holder for discussion of how to express continuum subtraction.  this is pretty tightly coupled to #231 .  

My current concept is something like "step 0" here: https://github.com/spacetelescope/dat_pyinthesky/blob/master/pyinthesky_specutils_fitting.ipynb .  The idea is that continuum-modeling happens as an *independent* step from subtraction or normalization.

The idea is that then the same  continuum model can be use for line-fitting, applications that require subtraction, or those that require normalization. The user can then focus just on how they construct their continuum rather than also worrying about how to pass it around to other algorithms.

**Comment by nmearl** [comment]
Continuum modeling is implemented as a separate task with associated functions to help users. Users are responsible for applying that continuum appropriate to their data before being fed to functions (whose docstrings specify which type of data is required, re: normalized/subtracted). Likewise, we've also included a new decorator to help warn users that their data is not appropriately reduced for use in the function (the `warn_continuum_below_threshold` decorator).
