### ISSUE TITLE
Uncertainty in manipulations.convolution_smooth

### ISSUE THREAD

**Issue by profxj** [astropy/specutils#251]
While I appreciate that deciding how to smooth an uncertainty array
is a bit tricky,  if the `Spectrum1D` begins with an uncertainty the smoothed
version needs to have one too.

e.g. the following should not return `None`

```
from specutils.manipulation import box_smooth

flux = np.random.sample(200)
wave = np.arange(1100, 1300)
sig = np.ones_like(flux)*0.1

spec1d = Spectrum1D(flux, spectral_axis=wave, uncertainty=sig)
smth_spec = box_smooth(spec1d, width=3)
smth_spec.uncertainty
```

**Comment by eteq** [comment]
Absolutely. I fully agree @profxj - we have been talking about this in some out-of-band discussion, but the idea would be  to use a truly correct uncertainty for the flux-conserving smoothing case, and something that's more like interpolation for the less-formally-statstical smoothing approaches.

**Comment by brechmos-stsci** [comment]
@eteq I am looking into this issue a bit.  I assume one would just use the regular error propagation for astronomy data based on the uncertainty defined in the Spectrum1D object, though, I think I can use the [propagate feature of NDUncertainty](https://keflavich-astropy.readthedocs.io/en/latest/_modules/astropy/nddata/nduncertainty.html#NDUncertainty.propagate) [which is the underlying type for uncertainty](https://github.com/astropy/specutils/blob/master/specutils/spectra/spectrum1d.py#L35).
