### ISSUE TITLE
Version 0.3 not on Pypi

### ISSUE THREAD

**Issue by olebole** [astropy/specutils#269]
Hi,

for the Debian package of specutils, I regularly check Pypi for new updates. However, version 0.3 did not make it there. Was this just forgotten or is the Pypi version no longer maintained (and I should switch to observing github)?

Cheers
Ole

**Comment by nmearl** [comment]
Hello Ole! We have not made a public release of the new specutils yet. We anticipate having a full release in the coming weeks. This new specutils is incompatible with the previous version and will require users to refactor some of their code if they are currently using the previous version.
