### ISSUE TITLE
make up pixel_to_world/world_to_pixel in wcs adapter more consistent with APE14

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#275]
I just realized that the current `WCSAdapter` uses a subtly different definition of `world_to_pixel`/`pixel_to_world` than the [APE14 WCS API](https://github.com/astropy/astropy-APEs/blob/master/APE14.rst).  In APE14 (and to-be in gwcs and astropy in the next releases... hopefully), the "world" coordinates are *objects*, not arrays.  E.g., for an image, `pixel_to_world` yields a `SkyCoord` or similar, or for a spectrum a `Quantity`.  But in the specutils `WCSAdapter`, it is an *array* (i.e., what the APE14 `world_to_pixel_values`/`pixel_to_world_values` functions yield). 

Moving forward, I think we want the `specutils` machinery to consume the *actual* `pixel_to_world`/`world_to_pixel`, as the interface there was designed for just this sort of use case.  But it will require some work to get that to match up with the adapter now.  In terms of timelines, probably it's best to wait until at least `gwcs` has an APE14-compliant interface, though, since a change will need to be made at this point *anyway*.

Vaguely related to #274, since the answer *might* be in there if the doc referenced there existed.

cc @nmearl

**Comment by nmearl** [comment]
This has been solved in the APE 14 implementation, which specutils has incorporated.
