### ISSUE TITLE
Weirdness with multidimensional Spectrum1D

### ISSUE THREAD

**Issue by drdavella** [astropy/specutils#280]
The documentation says that I should be able to have multiple spectra that all use the same spectral axis in a `Spectrum1D` object. Naively, I would expect to be able to do this:

```python
frequencies = np.linspace(1, 10, 20) * u.um
flux = np.ndarray((3, 20)) * u.Jy
s1 = Spectrum1D(spectral_axis=frequencies, flux=flux)
```

However, the following assertions will fail:

```python
assert frequencies == s1.spectral_axis
assert len(frequencies) == s1.spectral_axis
```

This is highly unintuitive.

Doing the following *will* preserve the dimensions of the spectral axis:

```python
frequencies = np.linspace(1, 10, 20) * u.um
flux = np.ndarray((3, 20)) * u.Jy
s1 = Spectrum1D(spectral_axis=frequencies, flux=flux.T)
```

But this doesn't make any sense to me. It also has the consequence of making internal computations have to perform some unnecessary contortions.

Is this a bug or am I just misunderstanding how this is supposed to work?

**Comment by brechmos-stsci** [comment]
confirmed, at least here, and I agree it is a kind of odd way to define it for things to work out, but I might be missing something too.

@eteq @stscicrawford  @nmearl
