### ISSUE TITLE
ValueError in SpectralRegion.extract needs to be updated

### ISSUE THREAD

**Issue by robelgeda** [astropy/specutils#285]
The `ValueError` at [this line](https://github.com/astropy/specutils/blob/fd608603541a6bf1d5a8bb153bd1beaba1646a85/specutils/spectra/spectral_region.py#L150) needs to be updated for values which result in the same pixel indices. For example I got the following error for `left_index == right_index` `True`:
`ValueError: Lower region, 60.41062077854714 Hz, appears to be greater than the upper region, 61.934802777038556 Hz.`

**Comment by robelgeda** [comment]
@nmearl @eteq @hcferguson : This is still an open question: What should happen if the input wavelength range results in the same lower and upper flux array index? Should it return an array of one value or raise an exception?

**Comment by brechmos-stsci** [comment]
So, the way it is written now is if the left and right bounds on the region do not encompass at least one point in the spectrum then None is returned.  

Currently one is not allowed to create a SpectralRegion with the bounds being equal.

**Comment by hcferguson** [comment]
I lean towards throwing an error if they are equal, rather than quietly returning None, but could be convinced otherwise.

**Comment by brechmos-stsci** [comment]
K. I changed to an exception if the lower bound is >= the upper bound.
