### ISSUE TITLE
SpectralRegion extract not calculating the indices correctly

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#287]
Unfortunately, I introduced a bug into `SpectralRegion` in the `to_pixel()` method.  Currently the line is:
```
left_index = int(np.ceil(spectrum.wcs.world_to_pixel(np.array(self._lower))))
```
but the `np.array()` strips the units off the self._lower which is *not* a good thing. It likely should be wrapped as a list rather than `np.array()`.
Looking into it.

**Comment by brechmos-stsci** [comment]
This may not actually be an issue... or at least not the direct issue. More to follow.

**Comment by robelgeda** [comment]
I think there is a bug because of `ceil` and `floor` calls. For example I got the following:
```
Input:
lower = 57.543071794388084 Hz
higher = 57.84678099795279 Hz

Output index:
lower_index = 58
upper_index = 57 

Exception:
Lower region, 57.543071794388084 Hz, appears to be greater than the upper region, 57.84678099795279 Hz.

```

**Comment by brechmos-stsci** [comment]
Not an issue, closing.

**Comment by brechmos-stsci** [comment]
Didn't see @robelgeda's comment. re-opening.

**Comment by brechmos-stsci** [comment]
I am going to make some modifications to SpectralRegion (enhancements), so will look at this ticket with that one.
