### ISSUE TITLE
Update equivalent_width to use regions

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#299]
Right now the `equivalent_width` function pre-dates the region machinery.  To really do things right  on that function we need to have it properly consider edge-pixels (as mentioned in https://github.com/astropy/specutils/issues/237#issuecomment-418828490). That's not really realistic for 0.4.  

However, since `equivalent_width` is already in there we should clean it up a bit.  Should be easy to have it use the regions machinery like what `snr` does.

The other thing to do is to make it clear that anyone who uses this function will find it's different once #237 is addressed.  So at minimum a docstring mention, maybe even a warning that says something like "warning: eqw will be improved, which means slightly different result, in the next version".  Alternatively, we could have it raise an exception if the region edges are not *exactly* a pixel edge.  That should then behave the same as what #237 should implement.

I'm not assigning anyone right now, but I think @brechmos-stsci @drdavella or myself can aim to do it by the release this Fri, and who it is depends on who has hit their other items by then?

**Comment by drdavella** [comment]
Is this a duplicate of #268?

**Comment by drdavella** [comment]
Maybe this belongs in a separate issue, but as @eteq mentioned in a review #281, `median` should be exposed as a user-accessible parameter.

**Comment by eteq** [comment]
Done in #281
