### ISSUE TITLE
Doctests don't run with `test` command

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#307]
Oddly, when I run `python setup.py test` the doctests don't run (i.e., the ``.rst`` files don't appear in the tests).  https://travis-ci.org/astropy/specutils/builds/425492149 shows why this is relevant - only one of the tests is failing, because only one of the test elements (the one on astropy 2.0.x) is actually running the doctests, but there is a *real* error there.

I took a crack at this and could not figure out why... it really seems like pytest is finding the docs directory, just for some reason refusing to run on rst files.  Even weirder, pointing directly to a file (e.g. ``python setup.py test -t docs/index.rst`` *does* work...

I asked on slack, but figured I should record it here too... (cc @drdavella @astrofrog)

**Comment by bsipocz** [comment]
I'm afraid the regression was introduced in v3.0.3, and https://github.com/astropy/astropy/pull/7767 has fixed it. 

A way to make sure that the tests are run at least for one more recent version combination would be to add a test against the astropy dev version (this is very much encouraged anyway).

**Comment by nmearl** [comment]
This has been fixed in latest package releases.
