### ISSUE TITLE
(Decide whether to) implement in-place modifying flux/spectral_axis units

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#312]
This issue pulls together some threads in both #309 and #196.  Specifically, the question about whether or not we want to support operations that modify spectra *in-place*.  In #309 the consensus looked to be that it's safer to follow the lead of `numpy` and some of the other `astropy` functions and yield new spectra as the "primary" option, but #309 (particularly https://github.com/astropy/specutils/pull/309#issuecomment-419458266) leaves open the possibility of developer-centric/utility functions for doing in-place flux unit conversions/over-writes.

The purpose of this issue is to decide whether we want to have such in-place options.  I think this should be done uniformly at least for `flux` (which by implication probably changes `uncertainty`) and `spectral_axis` in the same manner (i.e., #196 should either be closed or implemented along with `flux` based on the result of this discussion)

**Comment by SaOgaz** [comment]
@eteq I'm told package development has moved forward with the "make a new object" model.  Is there still discussion needed on this?

**Comment by nmearl** [comment]
We have concluded that operations should _not_ modify data in-place, and instead should always return new data objects.
