### ISSUE TITLE
Basic implementation of flux/eqw

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#314]
In some out-of-band discussion, we decided for the v0.4 release to have a "quick-and-dirty" EQW and line-flux implementation that does not do fractional-pixel interpolation correctly.  Then in 0.5 we'll try to do the more correct approach.

So this issue is for 0.4: to update `equivalent_width` and add a `flux` (or maybe `line_flux`?  or `region_flux`?) to exist in `analysis` and have a quick-and-dirty implementation that doesn't do the sub-pixel stuff.  That is, just sum up the pixels inside the region and divide by the delta-spectral axis for those pixels. (And then `equivalent_width` should be just based on that, with an added `continuum` keyword which is assumed to be 1)

cc @drdavella @brechmos-stsci

**Comment by eteq** [comment]
To give a bit more background on what "quick-and-dirty" means for these two cases:

* `line_flux`

The flux in a region of a spectrum from lambda1 to lambda2 is:

<a href="https://www.codecogs.com/eqnedit.php?latex=f&space;=&space;\int_{\lambda_1}^{\lambda_2}&space;F_\lambda&space;d\lambda" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f&space;=&space;\int_{\lambda_1}^{\lambda_2}&space;F_\lambda&space;d\lambda" title="f = \int_{\lambda_1}^{\lambda_2} F_\lambda d\lambda" /></a>

Which turns into this in array form (where `i` is over pixels of the spectrum, and ``\Delta\Lambda_i`` is the wavelength span of pixel ``i``.):

<a href="https://www.codecogs.com/eqnedit.php?latex=f&space;=&space;\sum_{i=i_1}^{i_2}&space;F_{\lambda,&space;i}&space;\Delta&space;\lambda_i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f&space;=&space;\sum_{i=i_1}^{i_2}&space;F_{\lambda,&space;i}&space;\Delta&space;\lambda_i" title="f = \sum_{i=i_1}^{i_2} F_{\lambda, i} \Delta \lambda_i" /></a>

Note also that the typical meaning of "flux" is flux *in the spectral feature*.  So implicitly the spectrum is usually continuum subtracted *before* this measurement.  Other times a continuum model is assumed (or implied), but for the "quick and dirty" version I think we should just say in the docs "this only gives the right answer if you've *already* subtracted the continuum".

* `equivalent_width`

This one (where here ``F_c`` is the continuum level) is:

<a href="https://www.codecogs.com/eqnedit.php?latex=W_\lambda&space;=&space;\int_{\lambda_1}^{\lambda_2}&space;\frac{Fc&space;-F_\lambda}{Fc}&space;d\lambda" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_\lambda&space;=&space;\int_{\lambda_1}^{\lambda_2}&space;\frac{Fc&space;-F_\lambda}{Fc}&space;d\lambda" title="W_\lambda = \int_{\lambda_1}^{\lambda_2} \frac{Fc -F_\lambda}{Fc} d\lambda" /></a>

Which can be array-ified the same as `flux`.  But that is also:

<a href="https://www.codecogs.com/eqnedit.php?latex==&space;\int_{\lambda_1}^{\lambda_2}&space;\left(&space;1&space;-&space;\frac{F_\lambda}{Fc}\right)&space;d\lambda&space;=&space;\lambda_2&space;-&space;\lambda_1&space;-&space;\frac{1}{F_c}&space;\int_{\lambda_1}^{\lambda_2}&space;F_\lambda&space;d\lambda" target="_blank"><img src="https://latex.codecogs.com/gif.latex?=&space;\int_{\lambda_1}^{\lambda_2}&space;\left(&space;1&space;-&space;\frac{F_\lambda}{Fc}\right)&space;d\lambda&space;=&space;\lambda_2&space;-&space;\lambda_1&space;-&space;\frac{1}{F_c}&space;\int_{\lambda_1}^{\lambda_2}&space;F_\lambda&space;d\lambda" title="= \int_{\lambda_1}^{\lambda_2} \left( 1 - \frac{F_\lambda}{Fc}\right) d\lambda = \lambda_2 - \lambda_1 - \frac{1}{F_c} \int_{\lambda_1}^{\lambda_2} F_\lambda d\lambda" /></a>

And the last equation you can see has the expression for `line_flux` in it.  So EQW turns out to be a relatively simple transformation of `line_flux` *if* you specify a continuum level. I see two options for the contiuum level:

1. have a `continuum` keyword that the user can provide. Should default to ``1`` (unitless), which then means the assumption is a continuum-normalized spectrum.  But the user can give a continuum value if they *want to*
2. Have no keyword, just do the calculation assuming the continuum value is ``1``.

No string preference, but a minor tilt towards 1.


* "quick and dirty"

The "quick and dirty" here means a few things:
1. lambda1 and lambda2 might be *in between* pixels - this implementation just ignores that instead of taking fractions of pixels.
2. in specutils `spectral_axis` might be wavelength, or frequency, or even energy, and the flux in the spectrum might also be flux units per  (wavelength, or frequency, or even energy). We could imagine being smarter about this and always converting the flux/spectral_axis combo to whatever set makes sense to get out an actual flux in the end.

One other possible simplification:
3. Don't bother computing ``\Delta \lambda_i`` - rather assume an average value. I think \Delta \lambda_i``  is relatively easy to calculate, though (``np.diff``), so may as well do it?

**Comment by eteq** [comment]
Oh one other detail: the equations above all use ``lambda``, implying that they are only valid for wavelengths. In reality the same equations hold for ``frequency``/``energy``, or any future possible `spectral_axis`'s, so the ``lambda``'s should be viewed as "whatever the spectral axis is".

**Comment by eteq** [comment]
Yet one more detail: I propose once the PR for this is in, we close this but make a new issue to address the "quick-and-dirty" elements.

**Comment by hcferguson** [comment]
I agree with those definitions and with the definition of "quick & dirty." I also lean toward having a "continuum" keyword, which would make it simpler later to make that accept a function with region arguments for computing the continuum. 

Regarding your second (2), I presume that you are suggesting that in "quick and dirty" we just used the units that are given, even if the returned units look screwy. 

I would suggest having three tests on the same basic input spectrum to make sure the direction of pixel-increase isn't causing glitches in the sign of flux or equivalent width:

(1) flux is in ``` erg cm-2 s-1 AA-1``` and ```spectral_axis``` is in ```AA```
(2) flux is in ```Jy``` and ```spectral_axis``` is in ```micron```
(3) flux is in ```Jy``` and ```spectral_axis``` is in ```Hz```

Flux and equivalent width should be positive for emission features and negative for absorption features in all three cases. (Case 2 is going to be very common for JWST and usually one will probably want equivalent widths in Angstroms...so clearly we're going to have to do some work beyond quick & dirty).

**Comment by eteq** [comment]
@hcferguson - I agree with all that except this:

> Flux and equivalent width should be positive for emission features and negative for absorption features

The convention I'm familiar with (and backed up via informal survey of two spectroscopists who happened to be just down the hall as I was typing it up...) is that equivalent width is *negative* for emission lines.  That's the convention that the above equations follow.  Easy to fix because it's a sign flip, but if we're using our crazy astronomy parametrization anyway we might as well use our crazy sign conventions :wink:

**Comment by hcferguson** [comment]
@eteq You are right. I had it backwards.
