### ISSUE TITLE
Change the data used for tests to not create a bunch of warnings

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#315]
Currently the specutils tests yield a bunch of warnings of the sort like this:
```
/.../astropy/units/format/generic.py:474: UnitsWarning: 'erg/cm2/s/A' contains multiple slashes, which is discouraged by the FITS standard
    core.UnitsWarning)
```
this is not desirable because it hides "real" errors/warnings and makes it harder to parse what's going on with the tests.

I think the real fix is not to update the test data to be something that actually doesn't yield warnings... but if that's not possible we could just supress the warnings in those tests using either the standard python warning machinery or some of the pytest warning-catching tools.

cc @drdavella

**Comment by drdavella** [comment]
I'm happy to handle warning suppression in the test code, but I'm not so sure I know how to correctly modify the data files themselves.
