### ISSUE TITLE
Surface brightness units

### ISSUE THREAD

**Issue by hcferguson** [astropy/specutils#319]
It is possible that JWST spectra will have units of Jy/steradian instead of Jy. Other observatories have done this. We should make it possible to support such surface brightness units.

**Comment by eteq** [comment]
In theory this should be fairly easy, as all measurements should get their units propagated through correctly so just adding a "per sterradian" should just yield flux measurements per sterradian and so on.

But of course that all depends on the implementations of the analysis tools and input-handling to be correctly done.  So really this is a good *test* that it's all working correctly?

**Comment by rosteen** [comment]
I think this can be closed, we've been using specutils on the back end of Jdaviz with surface brightness units for some time.
