### ISSUE TITLE
Errors in world_to_pixel when spectral_axis is in Hz units

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#322]
Found errors when the spectral axis is in Hz style units.

```
d = np.linspace(1, 10, 10)[::-1]
s1 = Spectrum1D(spectral_axis=d*u.GHz, flux=np.random.random(10)*u.Jy)

# Errors
s1.wcs.world_to_pixel([8*u.GHz])
# ValueError: The points in dimension 0 must be strictly ascending

# Errors
s1.wcs.world_to_pixel([5e8*u.AA])
# astropy.units.core.UnitConversionError: 'Angstrom' (length) and 'GHz' (frequency) are not convertible
```

**Comment by hcferguson** [comment]
@brechmos-stsci The tests for the direction of pixel increase should be done independent of the units. Typically X-ray data will have the spectral_axis in keV but it could be increasing to the left or to the right. It used to be common for IR astronomers to use "wavenumber" (1/wavelength) on their spectral atlas.
