### ISSUE TITLE
Make it clear how to cite specutils

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#343]
Probably just want to use the Zenodo record for now, but we should say this in the docs and the release announcements.

cc @nmearl @keflavich @crawfordsm

**Comment by eteq** [comment]
That is, I'd say we write a few sentences in the docs saying "please cite the Zenodo DOI if used in a paper", and similar words in the release announcement

**Comment by stscicrawford** [comment]
If it isn't set up already, we should set up the create zenodo DOI with the release.  For right now, this should be the default citation for the package.   

In the not so longer term, we should determine what is the minimal functionality for the 1.0 release and then write a paper for a more formal citation for specutils.

If specutils is already being used in papers (and I believe it might be), then we should also consider an entry on ASCL.

**Comment by eteq** [comment]
I'm leaving this open since @stscicrawford raises good ideas for future directions, but the needs for -.4 are met by #349

**Comment by nmearl** [comment]
As mentioned above, specutils is being published on Zenodo and doi entries are being generated. However, we should still consider the case for a paper/entry on ASCL.

**Comment by pllim** [comment]
There is https://github.com/astropy/specutils/blob/main/specutils/CITATION
