### ISSUE TITLE
Add a "continuum checker" to tools that care about continuum

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#347]
Several of the analysis tools (the flux module functions, centroid, and width) assume the input spectrum is either continuum-subtracted or normalized.  Currently the user has to just know that.  We could add a check for this which does `fit_generic_continuum` and asks if the fitted continuum is "close to" either 0 or 1 and generates a warning (*not* an error) to inform the user if that's the case.

This is pretty straightforward to implement, but a question is: do we *want* to?  It should certainly be turn-off-able given that it has a performance penalty, but it might also be too hard to get a heuristic algorithm to correctly recognize the situation without giving a lot of annoying false positives.

Thoughts, @hcferguson @crawfordsm @nmearl @keflavich ?

**Comment by nmearl** [comment]
This might just be my own use cases, but I can't think of a case where I _wouldn't_ know that my spectrum isn't contrinuum-subtracted/normalized. I'm also feel like if I did not know, then I'd be immediately suspect of the code's determination and check it anyway.

**Comment by nmearl** [comment]
Further discussion should in #547 and #548.
