### ISSUE TITLE
Fix broken doctest 

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#353]
Right now travis master is broken (my bad - #313) because of this doctest failure but it's *only in astropy-dev*:

https://travis-ci.org/astropy/specutils/jobs/431704339#L1083

The core problem is that there's not really a way (that I know of) to tell doctests "run, but don't check the output". That would be fine here because the output is about download status. I guess another option is to just suppress the download message somehow?

Another question is what changed in astropy-dev (@bsipocz @astrofrog - either of you know?)

**Comment by astrofrog** [comment]
I think we should have an ``+IGNORE_OUTPUT`` directive for pytest-doctestplus to run but not compare the output.
