### ISSUE TITLE
Fitting constraints do not work

### ISSUE THREAD

**Issue by doccosmos** [astropy/specutils#363]
The astropy documentation for models.Gaussian1D says that bounds can be set; however this does not work:

guess =  models.Gaussian1D(amplitude = 10. * 10**-17 * u.Unit('erg cm-2 s-1 AA-1'), mean = 4861. * u.AA, stddev = 30. * u.AA)
guess.stddev.max = 50.
fit = fit_lines(spec, guess, window = (4830. * u.AA, 5040 * u.AA))

returns fit.stddev > 50.

**Comment by nmearl** [comment]
Bounds need to be defined in the model itself (the `Gaussian1D`). The `window` keyword in `fit_lines` is for fitting to a particular part of the spectrum using the models passed in.

Closing this for now, feel free to open again or submit a new ticket if this isn't clear enough.
