### ISSUE TITLE
Documentation is very unintuitive

### ISSUE THREAD

**Issue by nluetzge** [astropy/specutils#366]
I'm talking about this documentation: https://specutils.readthedocs.io/en/latest/ if there is another one that I have overlooked then I apologize in advance. The first thing I usually look for when installing new software is how to install it. This was not immediately clear where to find on this page.

I find the navigation in this documentation very confusing. I'm used to have the main chapter on the side bar on the left so I would like to have something like this:

1. Installation
2. Getting Started
3. Usage
    - Working with Spectrum1Ds
    - Working With SpectrumCollections
    - ...
4. Get involved

Or maybe we could put the entire list that is currently "Using specutils" in the side bar (plus the getting started point). Also why is there an extra link saying "Specutils Documentation" right underneath Page Contents that does not seem to lead to anything?

**Comment by eteq** [comment]
That's the right one - `latest` on RTD is always pointing to master.

Just so I'm clear, though @nluetzge - you're fine with the structure *itself*, right @nluetzge ? (i.e. the front page + https://specutils.readthedocs.io/en/latest/#using-specutils) - it's the navigation on the left side that's the issue?

I *think* this is straightforward to implement through appropriate adjustment of `docs/conf.py` parameters, or possibly adjustment about the toctree levels that are shown by default.

**Comment by nmearl** [comment]
This has been addressed in #556.
