### ISSUE TITLE
Add function to API to refresh the IO registry

### ISSUE THREAD

**Issue by drdavella** [astropy/specutils#370]
This will be useful for applications like `specviz` that may add new loaders while running and expect to be able to use those loaders in the same application session.

**Comment by drdavella** [comment]
@eteq, @nearl as far as I can tell from the code both here and in `astropy`, I don't think this should be necessary. Maybe I'm missing something though?

**Comment by drdavella** [comment]
@nmearl makes sense. It still might be useful to make this function part of the public API but we can probably close this issue since it should be sufficient for `specviz`.

**Comment by SaOgaz** [comment]
We should update the to-do list in #510 to reflect that we need to call the already existing specutils function.

**Comment by eteq** [comment]
(If yes it does reload, then I agree with @drdavella in https://github.com/astropy/specutils/issues/370#issuecomment-434439557 that this is already all set)

**Comment by drdavella** [comment]
@eteq after looking briefly at how the Astropy IO registry works, I suspect that this will work without any `importlib` magic, but it should be tested.

**Comment by drdavella** [comment]
It turns out that if we want to be able to use `_load_user_io` we are going to need to pass `force=True` to `astropy.io.registry.register_reader/identifier`. I can open a PR for that, though.

**Comment by SaOgaz** [comment]
Per @nden  and @drdavella suggeestion, I got my loader to refresh with some alternative commands.  Can we close this @drdavella?

**Comment by drdavella** [comment]
Yup!
