### ISSUE TITLE
Add `ignore_units` parameter to the `fit_models` method

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#386]
There has been some discussion that `fit_models` should be able to fit a Spectrum1D object to a model or compound model that does not have units.

So, the original idea is that we should add a parameter `ignore_units` on the `fit_models` method to tell the fitting to ignore the units on the model input as the initial guess. Then, if one says `ignore_units=True` then we just ignore the units on the model and implicitly the initial guess value for the parameters would then be "in the same unit as the spectrum to fit" (as the Spectrum1D object is required to have units).

But, maybe it is easier to just say that the input model can have units or not. If the input unit does NOT have units, then it is assumed the parameters have the same units as the Spectrum1D values. At some level this might make more sense, though less explicit.

@eteq @robelgeda

**Comment by robelgeda** [comment]
This looks good. This is the best way to enable the fitting until the units machinery is in place.

**Comment by brechmos-stsci** [comment]
There is discussion on the associated PR.  The `ignore_units` will be implicit depending on whether the input model has units or not. Rather than explicit with this parameter.
