### ISSUE TITLE
Data files for loader tests

### ISSUE THREAD

**Issue by nmearl** [astropy/specutils#388]
We need actual test data for some of the loader tests. Currently, these loaders are specutils-supported:

- [x] `apogee`
- [x] `ascii`: can be generated
- [x] `cube`
- [x] `ecsv`: can be generated 
- [x] `hst_cos`
- [x] `hst_stis`
- [x] `muscles_sed`
- [x] `sdss`
- [x] `tabular_fits`
- [x] `wcs_fits`

**Comment by hcferguson** [comment]
I'm about to submit a PR to update the ESCV loader to be more capable. I've put in tests. It uses a generic_spectrum_from_table function that I put in io that looks at column units to make intelligent guesses about which is which, and I've written tests for that. That same function can be used to build smart loaders for IPAC ascii files and for tabular FITS files (so I would propose replacing the current tabular_fits loader).

**Comment by hcferguson** [comment]
I'm using @drdavella 's trick of creating a small temporary file for the tests. I think that should suffice for unit tests of most of the loaders. We'll still want to provide people with a few test data sets, but needn't do that for every loader.

**Comment by nmearl** [comment]
I'm currently in the throes of setting up data access using Zenodo's REST API so we can host datasets there. I'm sure small, generic data can be created on the fly, but we really want to avoid having the repo play both host to datasets as well as code.

**Comment by nmearl** [comment]
The testing infrastructure is up and running, now all we need is the remaining test data for the loaders. @eteq @hcferguson any idea where we can get some of these?

**Comment by hcferguson** [comment]
I think @gderosa2004 provided the COS and STIS data. We must have had examples of the others in earlier SpecViz development, so it will take some email forensics to find them. I'll do some digging.

**Comment by hcferguson** [comment]
I've put some old testdata from the early SpecView testing days on central store in /astro/ferguson1/ferguson/old_specviz_testdata. There are some DEIMOS DEEP2 Data from Susan Kassin, testdata/SpecView/kassin/brightred.spec1d/spec1d.1100.007.11001699.fits, and some MDM CCD spectral data from Gisella de Rosa, e.g. testdata/SpecView/gderosa/MDM1.3_CCDSPEC/n5548_120201.fits. Not sure if we have loaders right now that can read either of these. If not, it would be interesting to try the Wizard. 

Looks like Apogee data could be downloaded from https://www.sdss.org/dr12/irspec/spectro_data/. SDSS from https://www.sdss.org/dr12/spectro/spectro_access/.

**Comment by hamogu** [comment]
I think this is related:
With the master on MacOSX I see all tests failing that download data through `urllib.request.urlopen` into a `tempfile.NamedTemporaryFile`. The Python docs (https://docs.python.org/3.7/library/tempfile.html#tempfile-examples) say: Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms ...

Here is an example error:
```
________________________ test_read_linear_solution[remote_data_path0] _________________________

remote_data_path = '/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/tmptf7cvf26/L5g_0355+11_Cruz09.fits'

    @remote_access([{'id': '1481190', 'filename': 'L5g_0355+11_Cruz09.fits'}])
    def test_read_linear_solution(remote_data_path):
>       spec = Spectrum1D.read(remote_data_path, format='wcs1d-fits')

specutils/tests/test_spectrum1d.py:211: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Users/hamogu/anaconda/envs/py36/lib/python3.6/site-packages/astropy/nddata/mixins/ndio.py:27: in read
    return io_registry.read(cls, *args, **kwargs)
/Users/hamogu/anaconda/envs/py36/lib/python3.6/site-packages/astropy/io/registry.py:517: in read
    data = reader(*args, **kwargs)
specutils/io/default_loaders/wcs_fits.py:58: in wcs1d_fits_loader
    with fits.open(file_name, **kwargs) as hdulist:
/Users/hamogu/anaconda/envs/py36/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py:164: in fitsopen
    lazy_load_hdus, **kwargs)
/Users/hamogu/anaconda/envs/py36/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py:400: in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'astropy.io.fits.hdu.hdulist.HDUList'>
fileobj = <astropy.io.fits.file._File <_io.FileIO [closed]>>, data = None, mode = 'readonly'
memmap = None, save_backup = False, cache = True, lazy_load_hdus = True
kwargs = {'uint': True}, hdulist = [], read_one = False

    @classmethod
    def _readfrom(cls, fileobj=None, data=None, mode=None,
                  memmap=None, save_backup=False, cache=True,
                  lazy_load_hdus=True, **kwargs):
        """
            Provides the implementations from HDUList.fromfile and
            HDUList.fromstring, both of which wrap this method, as their
            implementations are largely the same.
            """
    
        if fileobj is not None:
            if not isinstance(fileobj, _File):
                # instantiate a FITS file object (ffo)
                fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
            # The Astropy mode is determined by the _File initializer if the
            # supplied mode was None
            mode = fileobj.mode
            hdulist = cls(file=fileobj)
        else:
            if mode is None:
                # The default mode
                mode = 'readonly'
    
            hdulist = cls(file=data)
            # This method is currently only called from HDUList.fromstring and
            # HDUList.fromfile.  If fileobj is None then this must be the
            # fromstring case; the data type of ``data`` will be checked in the
            # _BaseHDU.fromstring call.
    
        hdulist._save_backup = save_backup
        hdulist._open_kwargs = kwargs
    
        if fileobj is not None and fileobj.writeonly:
            # Output stream--not interested in reading/parsing
            # the HDUs--just writing to the output file
            return hdulist
    
        # Make sure at least the PRIMARY HDU can be read
        read_one = hdulist._read_next_hdu()
    
        # If we're trying to read only and no header units were found,
        # raise an exception
        if not read_one and mode in ('readonly', 'denywrite'):
            # Close the file if necessary (issue #6168)
            if hdulist._file.close_on_error:
                hdulist._file.close()
    
>           raise OSError('Empty or corrupt FITS file')
E           OSError: Empty or corrupt FITS file

/Users/hamogu/anaconda/envs/py36/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py:1021: OSError
```

In other packages, I have made good experiences with creating a `tempfile.TemporaryDirectory` and placing file in there.

**Comment by nmearl** [comment]
The tests that utilize the `remote_data_access` do not use `NamedTemporaryFile`s. This error reads like a faulty write, what version of astropy are you using?

**Comment by SaOgaz** [comment]
@nmearl, I think this is similar to what i was seeing.... under astropy 3.0.5. Haven't tried re-making my conda setup yet...

**Comment by nmearl** [comment]
All above loaders have been implemented in some form. Closing in favor of individual tickets that may be opened in the future for specific support.
