### ISSUE TITLE
Add clearer docs on the continuum-fitting + line-fitting process

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#393]
While trying to demonstrate for some folks how to do continuum subtraction followed by `analysis` and fitting operations, I realized a lot of the "vision" for how this is supposed to work is still only here: https://github.com/spacetelescope/dat_pyinthesky/blob/master/pyinthesky_specutils_fitting.ipynb  instead of the specutils docs.  Should be moved into the docs

**Comment by rosteen** [comment]
Seems like these docs were added but this was never closed, closing.
