### ISSUE TITLE
Document the default loaders

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#394]
#376 added several data loaders.  But none of the loaders are actually in the docs.  We need to fix that by adding them to the sphinx docs before a release.

At the same time, the docs on this need some discussion of what the "generic" readers mean.  I.e., that they are intentionally limited because you should write a custom loader instead of using the "generic" readers if you can't do a simple column-to-attribute mapping.

**Comment by eteq** [comment]
Moving this to 0.6, which makes these loaders "private functionality" for v0.5.

**Comment by eteq** [comment]
I'm going to add a bit more to what this should do (and ping this...) due to #573 - it's clear from that we need to specify when the tabular fits loader should be used vs the generic cube loader.

**Comment by eteq** [comment]
Oh and to given an example of the sort of thing *I* at least had in mind here - see https://docs.astropy.org/en/stable/io/unified.html#built-in-table-readers-writers .  

That particular one is a *manually* generated table, which is not ideal because it's hard to maintain when new loaders are added.  But there are functions built into the I/O machinery that can print out what's present without any manual work required.  For example, if you do ``specutils.Spectrum1D.read.help()`` it prints an ready-to-go rst-formatted string that has a table with all the `Spectrum1D` readers and writers.  That function has an argument ``out`` that makes me think it was intended to be used to generate documentation.  I don't have an example off-hand of how that might be used, but I'm guessing searching around a bit in `astropy` will reveal an example?

While calling functions like that directly from the doc build is non-trivial, the easiest work around I know of is to do it at import-time in something that gets documented in sphinx.  To see a (somewhat complicated) example of this, you can compare https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/__init__.py to https://docs.astropy.org/en/latest/coordinates/#built-in-frame-classes - the fancy graph there is generated as part of the import of `builtin_frames`, and then sphinx just shows the docstring and doesn't have to run any special code.  We could do something similar here.

**Comment by nmearl** [comment]
This is solved with #672.
