### ISSUE TITLE
Fix all warnings in the test suite and turn warnings to errors

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#397]
Currently the test suite yields quite a lot of warnings. See e.g., https://travis-ci.org/astropy/specutils/jobs/457642734 .  Most if not all of these are avoidable and are indeed signs that we shouldn't be doing something we're doing.  We should fix whatever is causing those warnings at a minimum.  

As an additional bit, maybe we should turn on the pytest warnings-to-errors feature?  That would keep these from creeping in in the future...

**Comment by pllim** [comment]
This is still relevant and should be done sooner than later. @dhomeier caught a bunch of incompatibilities with `astropy` 4.3rc1.

**Comment by pllim** [comment]
From the dev job as of 2021-07-09: `422 passed, 3 skipped, 11 xfailed, 386 warnings in 228.54s`
