### ISSUE TITLE
What versions of Astropy do we support?

### ISSUE THREAD

**Issue by drdavella** [astropy/specutils#402]
This is important to declare explicitly in the package requirements. It also has implications for other parts of the package infrastructure.

**Comment by hamogu** [comment]
If it's undeclared right now, there is a chance to have a clean slate, so don't you want to start with a higher version, e.g. >=3.5?
That way, there is no need for backwards hacks down to 3.0. It's a pain to go through deprecation cycles later. 

Astropy itself required 3.5 or later (https://astropy.readthedocs.io/en/latest/install.html)

**Comment by hamogu** [comment]
@nmearl Sorry about that. :embarrassed face:
