### ISSUE TITLE
Equivalent to old `read_fits.read_fits_spectrum1d` function?

### ISSUE THREAD

**Issue by bmorris3** [astropy/specutils#414]
Hi all, 

I used to use `specutils.io.read_fits.read_fits_spectrum1d` to read IRAF-reduced echelle spectra, which would return a list of `Spectrum1D` objects. Is there an equivalent function in the latest version of specutils? `Spectrum1D.read` isn't working (yielding: `IORegistryError: Format could not be identified`).

An example file can be found [here](
http://staff.washington.edu/bmmorris/docs/KIC8462852.0001.wfrmcpc.fits)

cc @nmearl @crawfordsm
 
Thanks!
Brett

**Comment by nmearl** [comment]
There is not, but one could be easily created. We switch the package to using the astropy io registry, so loaders need to be registered to specutils classes. In general, most loaders are attached to `Spectrum1D` objects, but in your case (as is similar to the jwst loader), you'll want to return either a `SpectrumList` object or a `SpectrumCollection`. Unfortunately, we haven't gotten around to coding this up, but it might just be as simple as reading the [custom loader](https://specutils.readthedocs.io/en/latest/custom_loading.html) docs and copy/pasting from the old `read_fits_spectrum1d` function.

**Comment by bmorris3** [comment]
Cool – I'm trying to adapt the old code (available [here](https://github.com/astropy/specutils/blob/legacy-specutils/specutils/io/read_fits.py)) to a custom loader and I'm coming up on a few stumbling blocks. Do I also have to reimplement the old WCS framework, or is that code hiding somewhere that I'm missing in the new version?

**Comment by crawfordsm** [comment]
Yes, the old loader used some pretty custom code to handle the WCS.   However, [gwcs](https://gwcs.readthedocs.io/en/latest/) should be able to handle the creation of the WCS framework in a more elegant way and can also be used with a specutils object.

**Comment by bmorris3** [comment]
As a stopgap measure until `specutils` has a working loader, I've just copied over the requisite portions of legacy `specutils` into my package.

**Comment by nmearl** [comment]
@bmorris3 would you be comfortable sharing some representative sample of your data that we could use to ensure compatibility as we continue to work on specutils?

**Comment by bmorris3** [comment]
Sure, there's an example file linked in my [original post](
https://github.com/astropy/specutils/issues/414#issue-386950598).
