### ISSUE TITLE
Doctest directive showing up in code

### ISSUE THREAD

**Issue by astrofrog** [astropy/specutils#421]
The doctest directive ``IGNORE_OUTPUT`` shouldn't be showing up on the front page:

<img width="719" alt="screen shot 2018-12-04 at 11 01 06" src="https://user-images.githubusercontent.com/314716/49462722-fbc50580-f7b3-11e8-9a1c-bfca1d92dd41.png">

**Comment by nmearl** [comment]
No longer seems to be an issue.
