### ISSUE TITLE
Ensure strict ordering in specutils loaders? (JWST loaders)

### ISSUE THREAD

**Issue by SaOgaz** [astropy/specutils#423]
Depending on how #368 falls out, we may need to update the JWST loader to order x1d JWST files that are no in ascending order.

**Comment by nmearl** [comment]
Can you change the title of this issue to reflect the issue? :stuck_out_tongue:

**Comment by SaOgaz** [comment]
Some input spectra may not be in ascending wavelength order. Specutils does not natively handle this, should we?

**Comment by SaOgaz** [comment]
Apparently works fine now.... and I have no idea why.  I may have been using some outdated versions of libraries?

But closing this issue in the meantime.
