### ISSUE TITLE
fit_lines

### ISSUE THREAD

**Issue by Serosse** [astropy/specutils#425]
Hello

I am new to specutils

I have downloaded the package without problems and wanted to try to fit some 1-D spectra. I copy this from the tutorial and it says it is missing fit_lines and I cannot find it anywhere

import numpy as np
import matplotlib.pyplot as plt

from astropy.modeling import models
from astropy import units as u

from specutils import Spectrum1D
from specutils import fit_lines

the error it gives:cannot import name fit_lines

I cannot find it in the library

**Comment by nmearl** [comment]
Hi @Serosse. In the [example shown here](https://specutils.readthedocs.io/en/latest/fitting.html#simple-example), your imports should have

```python
from specutils import Spectrum1D
from specutils.fitting import fit_lines
```

Hope that helps.
