### ISSUE TITLE
handling not-wave-calibrated spectra

### ISSUE THREAD

**Issue by kobe90** [astropy/specutils#437]
Hello,
I am trying to use specutils for identifying lines in not-already-wavelength-calibrated spectra. To do this, I use the Spectrum1D class with a spectral axis in pixel units. 
My point now is that I would fit the continuum (using fit_generic_continuum or fit_continuum functions) but I get the following:

UnitConversionError: 'pix' and 'Angstrom' (length) are not convertible

can anyone suggest me something to avoid this?

**Comment by brechmos-stsci** [comment]
I'll take a look at it....

**Comment by brechmos-stsci** [comment]
So it comes down to the wavelength property is attempting to convert the spectral_axis to Angstroms regardless of the spectral_axis type:
```
   @property
   def wavelength(self):
       """
       The wavelength as a `~astropy.units.Quantity` in units of Angstroms     
       """
       return self.spectral_axis.to(u.AA, u.spectral())                        
```

I think easiest would be to check to see if it is convertible to AA or pixels and return the wavelengths in the appropriate units.

I'll create a PR...

**Comment by nmearl** [comment]
I'm seeing a few issues with using a spectral axis that's not in wavelength/frequency/energy/velocity space:

1. Continuum fitting seems to [explicitly call](https://github.com/astropy/specutils/blob/master/specutils/fitting/fitmodels.py#L306) the `.wavelength` property, even though it doesn't seem to be used anywhere in the fitting.
2. Operations in specutils that create new spectra internally convert the wcs to gwcs when not explicitly given a fits wcs. In the latest version of gwcs, a valid VO physical type has to be provided (similar case of #435). Gwcs will refuse to create a new wcs with dispersion value of `pix`.

Removing those lines and down-grading gwcs to version 0.9.1 solves the problem and I can fit the continuum.

**Comment by nmearl** [comment]
@brechmos The `.wavelength` probably _should_ fail if the units aren't convertible.

**Comment by brechmos-stsci** [comment]
I see that line is extraneous, and I'll remove.

Downgrading the GWCS doesn't seem to be a great solution.  Seems like something else needs to happen for it to work with a current version of GWCS.

**Comment by nmearl** [comment]
Yeah, definitely. I'm looking at the VO definitions now and seeing if I can extend what's in gwcs to handle pixel space units (or perhaps no units) gracefully.

**Comment by kobe90** [comment]
Hello! So, could you suggest me something to handle pixel units in Spectrum1D class? 
Thank you

**Comment by nmearl** [comment]
Hey @kobe90. If you pull down the latest master version of gwcs and the recent updates to specutils, you should be able to use pixel units and/or no units.

**Comment by kobe90** [comment]
Thank you! The point is that now, I use the following piece of code:

`from specutils import Spectrum1D
from astropy.io import fits
import numpy as np
import matplotlib.pyplot as plt
from astropy import units as u
from specutils.fitting import find_lines_derivative, fit_continuum, fit_generic_continuum

filename='spec4.ms.fits'
spec=fits.open(filename)[0].data[0][0]
x=np.arange(0, len(spec), 1)

plt.plot(x, spec)

spectrum = Spectrum1D(spectral_axis=x*u.pixel, flux=spec*u.count)
`
getting the following error:

`UnboundLocalError                         Traceback (most recent call last)
<ipython-input-9-75ae27e82b3b> in <module>
----> 1 spectrum = Spectrum1D(spectral_axis=x*u.pixel, flux=spec*u.Jy)

~/anaconda/lib/python3.6/site-packages/specutils/spectra/spectrum1d.py in __init__(self, flux, spectral_axis, wcs, velocity_convention, rest_value, *args, **kwargs)
     74                 raise ValueError("Spectral axis must be a `Quantity` object.")
     75 
---> 76             wcs = WCSWrapper.from_array(spectral_axis)
     77         elif wcs is not None:
     78             if not issubclass(wcs.__class__, WCSAdapter):

~/anaconda/lib/python3.6/site-packages/specutils/wcs/wcs_wrapper.py in from_array(array)
     55                                          axes_type=('SPECTRAL',),
     56                                          axes_order=(0,))
---> 57         spec_frame = cf.SpectralFrame(unit=array.unit, axes_order=(0,))
     58         forward_transform = Tabular1D(np.arange(len(array)), array.value)
     59         forward_transform.inverse = Tabular1D(array.value, np.arange(len(array)))

~/anaconda/lib/python3.6/site-packages/gwcs/coordinate_frames.py in __init__(self, axes_order, reference_frame, unit, axes_names, name, axis_physical_types, reference_position)
    348                                             unit=unit, name=name,
    349                                             reference_position=reference_position,
--> 350                                             axis_physical_types=axis_physical_types)
    351 
    352     def coordinates(self, *args, equivalencies=[]):

~/anaconda/lib/python3.6/site-packages/gwcs/coordinate_frames.py in __init__(self, naxes, axes_type, axes_order, reference_frame, reference_position, unit, axes_names, name, axis_physical_types)
     95 
     96         super(CoordinateFrame, self).__init__()
---> 97         self._axis_physical_types = self._set_axis_physical_types(axis_physical_types)
     98 
     99     def _set_axis_physical_types(self, pht=None):

~/anaconda/lib/python3.6/site-packages/gwcs/coordinate_frames.py in _set_axis_physical_types(self, pht)
    146         else:
    147             ph_type = tuple("custom:{}".format(t) for t in self.axes_type)
--> 148         validate_physical_types(ph_type)
    149         return ph_type
    150 

UnboundLocalError: local variable 'ph_type' referenced before assignment
`

**Comment by kobe90** [comment]
> Hey @kobe90. If you pull down the latest master version of gwcs and the recent updates to specutils, you should be able to use pixel units and/or no units.

Thank you!
The point is that now I use the following piece of code:

from specutils import Spectrum1D
from astropy.io import fits
import numpy as np
import matplotlib.pyplot as plt
from astropy import units as u
from specutils.fitting import find_lines_derivative, fit_continuum, fit_generic_continuum

filename='spec4.ms.fits'
spec=fits.open(filename)[0].data[0][0]
x=np.arange(0, len(spec), 1)

plt.plot(x, spec)

spectrum = Spectrum1D(spectral_axis=x*u.pixel, flux=spec*u.count)

g1_fit = fit_continuum(spectrum)

find_lines_derivative(spectrum)


Getting the following error:


UnboundLocalError                         Traceback (most recent call last)
<ipython-input-9-75ae27e82b3b> in <module>
----> 1 spectrum = Spectrum1D(spectral_axis=x*u.pixel, flux=spec*u.Jy)

~/anaconda/lib/python3.6/site-packages/specutils/spectra/spectrum1d.py in __init__(self, flux, spectral_axis, wcs, velocity_convention, rest_value, *args, **kwargs)
     74                 raise ValueError("Spectral axis must be a `Quantity` object.")
     75 
---> 76             wcs = WCSWrapper.from_array(spectral_axis)
     77         elif wcs is not None:
     78             if not issubclass(wcs.__class__, WCSAdapter):

~/anaconda/lib/python3.6/site-packages/specutils/wcs/wcs_wrapper.py in from_array(array)
     55                                          axes_type=('SPECTRAL',),
     56                                          axes_order=(0,))
---> 57         spec_frame = cf.SpectralFrame(unit=array.unit, axes_order=(0,))
     58         forward_transform = Tabular1D(np.arange(len(array)), array.value)
     59         forward_transform.inverse = Tabular1D(array.value, np.arange(len(array)))

~/anaconda/lib/python3.6/site-packages/gwcs/coordinate_frames.py in __init__(self, axes_order, reference_frame, unit, axes_names, name, axis_physical_types, reference_position)
    348                                             unit=unit, name=name,
    349                                             reference_position=reference_position,
--> 350                                             axis_physical_types=axis_physical_types)
    351 
    352     def coordinates(self, *args, equivalencies=[]):

~/anaconda/lib/python3.6/site-packages/gwcs/coordinate_frames.py in __init__(self, naxes, axes_type, axes_order, reference_frame, reference_position, unit, axes_names, name, axis_physical_types)
     95 
     96         super(CoordinateFrame, self).__init__()
---> 97         self._axis_physical_types = self._set_axis_physical_types(axis_physical_types)
     98 
     99     def _set_axis_physical_types(self, pht=None):

~/anaconda/lib/python3.6/site-packages/gwcs/coordinate_frames.py in _set_axis_physical_types(self, pht)
    146         else:
    147             ph_type = tuple("custom:{}".format(t) for t in self.axes_type)
--> 148         validate_physical_types(ph_type)
    149         return ph_type
    150 

UnboundLocalError: local variable 'ph_type' referenced before assignment

**Comment by nmearl** [comment]
It's hard to say without having access to your data file, but the below works for me. Can you verify that it works for you?

```python
from specutils import Spectrum1D
from astropy.io import fits
import numpy as np
from astropy import units as u
from specutils.fitting import find_lines_derivative, fit_continuum, fit_generic_continuum

x = np.arange(0, 100, 1)
spec = np.random.sample(100)

spectrum = Spectrum1D(spectral_axis=x * u.pixel, flux=spec * u.count)

g1_fit = fit_continuum(spectrum)

find_lines_derivative(spectrum)
```

**Comment by nmearl** [comment]
Are you using the lastest gwcs version from master? You can install it by typing `pip install git+https://github.com/spacetelescope/gwcs.git --upgrade` at your command line.

**Comment by kobe90** [comment]
> Are you using the lastest gwcs version from master? You can install it by typing `pip install git+https://github.com/spacetelescope/gwcs.git --upgrade` at your command line.

Perfect! The "Spectrum1D" object now seems set. The point now is that, when I try:

`g1_fit = fit_continuum(spectrum)`

I get:

UnitConversionError: 'pix' and 'Angstrom' (length) are not convertible

**Comment by eteq** [comment]
@kobe90 - I'm closing this because the *original* issue was solved.  But I've created #453 to track your new problem, so hopefully we can fix that problem there!
