### ISSUE TITLE
jwst loader loses most metadata

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#446]
If I load the nirspec test data from specviz (https://stsci.box.com/shared/static/3b01kkv5ndndtja4c7c748mwln7eyt2a.fits) into a `SpectrumList` using the JWST loader, I notice something odd: the metadata is *almost* empty:
```
>>> slist[0].meta
{'slitname': 'S200A1'}
```
Perhaps the meta dict should get all of the keywords from the relevant fits hdu? (e.g. "SLIT_RA", "SLITID", etc), and possible also all of the keywords from the primary HDU? (e.g. "DATE-OBS" and similar observation-related info).

Longer-term we may want to properly injest the asdf and load that in somehow, but as a temporary step perhaps the above is better than the current state of affairs?

cc @drdavella

**Comment by drdavella** [comment]
Yes I think just including the entire header for that HDU as metadata is a good idea. At the time it wasn't clear exactly which fields would be useful, but that makes sense.

And yes, eventually this should just use ASDF to read the data. Although there's a question of whether we would need JWST data models in order to do this properly.

**Comment by nmearl** [comment]
We took this approach in the [HST loaders](https://github.com/astropy/specutils/blob/master/specutils/io/default_loaders/hst_cos.py#L41): storing the `FITS` header object in the `meta` dict directly. Perhaps we should come up with a consistent way that `FITS` meta data gets stored on the `Spectrum1D` object.

**Comment by drdavella** [comment]
It seems like it might be a good idea to include both the header keywords from the primary HDU, and also from the HDU that contains the data. However, I'm not sure whether this makes sense in all cases; my frame of reference is the JWST data files.

**Comment by nmearl** [comment]
Based on the new JWST loaders, all header data is now stored in the `meta` dictionary on `Spectrum1D`/`SpectrumList` objects.
