### ISSUE TITLE
continuum fitting fails on pixel-axis spectrum

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#453]
>> Are you using the lastest gwcs version from master? You can install it by typing `pip install git+https://github.com/spacetelescope/gwcs.git --upgrade` at your command line.
>
>Perfect! The "Spectrum1D" object now seems set. The point now is that, when I try:
>
>`g1_fit = fit_continuum(spectrum)`
>
>I get:
>
>UnitConversionError: 'pix' and 'Angstrom' (length) are not convertible

_Originally posted by @kobe90 in https://github.com/astropy/specutils/issues/437#issuecomment-459393833_

**Comment by eteq** [comment]
@kobe90, can you past the full traceback when you see this problem? (including e.g. the line where the you see the error).

(Unless @brechmos-stsci sees the problem right away?)

**Comment by brechmos-stsci** [comment]
I don't know off hand. If we could get an example Spectrum1D object that is failing and the version of specutils, gwcs and astropy would be great.

**Comment by nmearl** [comment]
I've tested the following code and it shows the expected behavior. Closing until we have more information.

```python
In [8]: from specutils import Spectrum1D; import numpy as np; import astropy.units as u                                                    

In [9]: from specutils.fitting import fit_continuum                                                                                        

In [10]: spec = Spectrum1D(spectral_axis=np.arange(10) * u.pix, flux=np.random.sample(10) * u.Jy)                                          

In [11]: fit_continuum(spec)                                                                                                               
WARNING: Model is linear in parameters; consider using linear fitting methods. [astropy.modeling.fitting]
WARNING:astropy:Model is linear in parameters; consider using linear fitting methods.
Out[11]: <QuantityModel Chebyshev1D(3, c0=0.84601056, c1=-0.0899344, c2=-0.00021696, c3=0.00011186), input_units=pix, return_units=Jy>
```

**Comment by Ramlalunni** [comment]
Hi nmearl,

I tried out the code from your previous comment (from September 13, 2019), exactly as it is, and it shows the following error:

###############

runfile('/home/lal/Ramlal/M.Sc. Project/TRIALS - PNG239.6+13.9/Flux Comparison/trial.py', wdir='/home/lal/Ramlal/M.Sc. Project/TRIALS - PNG239.6+13.9/Flux Comparison')
Traceback (most recent call last):

  File "/home/lal/Ramlal/M.Sc. Project/TRIALS - PNG239.6+13.9/Flux Comparison/trial.py", line 5, in <module>
    fit_continuum(spec)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 97, in fit_continuum
    continuum_spectrum = fit_lines(spectrum, model, fitter, exclude_regions, weights)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 360, in fit_lines
    ignore_units, **kwargs)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 476, in _fit_lines
    _strip_units_from_model(model, spectrum, convert=not ignore_units)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 604, in _strip_units_from_model
    compound_model = model_in.n_submodels() > 1

TypeError: 'int' object is not callable

##############

This particular TypeError occurs whenever I try to use fit_generic_continuum or fit_continuum nowadays. Can you please help me out on this?

NOTE: The trial.py file used here contains exactly the  4 lines you have written:
from specutils import Spectrum1D; import numpy as np; import astropy.units as u                                                    
from specutils.fitting import fit_continuum                                                                                        
spec = Spectrum1D(spectral_axis=np.arange(10) * u.pix, flux=np.random.sample(10) * u.Jy)                                          
fit_continuum(spec)
