### ISSUE TITLE
Update gwcs requirement?

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#454]
#437 pointed out a bug in the "uncalibrated spectral axis" spectral use case, and the fix was in gwcs according to @nmearl .  We need to record that in the requirements.  This should be a trivial case of having `gwcs>x.y` in the setup.cfg, but I'm not clear what the required version is.  Do you know, @nmearl or @brechmos-stsci ?

**Comment by brechmos-stsci** [comment]
I am not sure. I could look into it, but @nmearl might know off-hand.

**Comment by nmearl** [comment]
There hasn't been a gwcs release yet, so we're not going to be able to update the requirements until then. @nden any plans on a new release?

**Comment by nden** [comment]
I can make a release next week if you need it.

**Comment by eteq** [comment]
@nden - that would be great since it's necessary to fix that specutils bug. Assuming that's the case, what would the be version be? (0.11.0 or 0.10.1?)

**Comment by eteq** [comment]
This would be fixed by #462, but if we don't get that in in time for 0.6, we should just bump the version number to close this @nmearl

**Comment by nden** [comment]
To make sure it's clear - gwcs v 0.11 is out. The next one will be using the new modeling in astropy.master.

**Comment by eteq** [comment]
Done in #462
