### ISSUE TITLE
Uncertainty ignored when initiating a Spectrum1D object if no spectral axis exists

### ISSUE THREAD

**Issue by andycasey** [astropy/specutils#463]
Hi,

I noticed some unusual behaviour that I suspect is not intentional. Consider the following example:

```python
import numpy as np
from astropy.nddata import InverseVariance
from astropy import units as u

from specutils import (Spectrum1D, __version__)

print(__version__)

pixels = 50
spectral_axis = np.linspace(300, 400, pixels) * u.nm
flux = np.random.uniform(0, 1, size=pixels) * u.Unit("1e-17 erg / (Angstrom cm2 s)")
uncertainty = InverseVariance(np.random.uniform(1, 100, size=pixels))

example_a = Spectrum1D(spectral_axis=spectral_axis, flux=flux, uncertainty=uncertainty)
example_b = Spectrum1D(flux=flux, uncertainty=uncertainty)

print("On uncertainties...")
print("Example A: {}".format(example_a.uncertainty is None))
print("Example B: {}".format(example_b.uncertainty is None))

# But for fluxes.
print("On fluxes...")
print("Example A: {}".format(example_a.flux is None))
print("Example B: {}".format(example_b.flux is None))
```

My expectation is that *because* I provide a valid `uncertainty` value to `example_a` and `example_b`, both spectra should have flux and uncertainty values, even though there is no dispersion axis present (e.g., it should print `False` across the board). This is the actual output:
```
0.5.2
On uncertainties...
Example A: False
Example B: True
On fluxes...
Example A: False
Example B: False
```

The `uncertainty` is being entirely ignored if there is no dispersion axis present. Is this expected?

Stack details:
```
Mac OSX 10.14 (Mojave)
python 3.6.2 (conda stack)
astropy version 3.1.2
specutils version 0.5.2
```

**Comment by rosteen** [comment]
@nmearl @eteq It looks like this was solved in the course of other work and can be closed. The example that previously demonstrated the bug now works properly.

**Comment by nmearl** [comment]
Thanks for checking on this, @rosteen! Looks like it indeed has been fixed. @andycasey if you're still seeing a related error, please feel free to reopen this issue.
