### ISSUE TITLE
if wavelength is given to Spectrum1D constructor, nonsense WCS results

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#466]
The following quite logical behavior already works in `Spectrum1D`:
```
>>> s = specutils.Spectrum1D(spectral_axis=[4000,5000]*u.angstrom, flux=[1,2]*u.AB)
>>> s.wavelength
<Quantity [4000., 5000.] Angstrom>
```
However, the following also *appears* to work:
```
>>> s = specutils.Spectrum1D(wavelength=[4000,5000]*u.angstrom, flux=[1,2]*u.AB)
>>> s
<Spectrum1D(flux=<Quantity [1., 2.] AB>)>
```
*but* as soon as you try to do the next step it fails:
```
>>> s.wavelength
AttributeError: 'NoneType' object has no attribute 'pixel_to_world'
```

Presumably this is because the `Spectrum1D` constructor is accepting ``wavelength`` but *not doing anything with it*? I think this is pretty counter-intuitive. The core problem is that the Spectrum1D initializer accepts *anything* that's not valid and doesn't give the standard invalid argument errors...

I can make a PR to make Spectrum1D stricter... But before I do, @nmearl, can you confirm there's not some reason I'm missing why the constructor is so loose with what it accepts?

**Comment by nmearl** [comment]
Hmm, is it because it's supposed to be `u.Angstrom`, not `u.angstrom`? Still doesn't resolve the issue that it should raise an error for an incorrect unit, but could mean that the machinery _works_ fundamentally, just without the proper notifications to the user.

**Comment by eteq** [comment]
no, it's the same unit with either capitalization.  I think it's just that we allow no-`spectral_axis` `Spectrum1D` objects, but instead of creating a "pixel" WCS in that case, it seems to be creating *no* WCS.  Do you think it makes sense to create a "pixel" WCS @nmearl?  In that case this is really two or maybe three issues:
1. Make a "pixel" WCS
2. Don't let the initializer accept ignored arguments
3. catch the `wavelength` case?

**Comment by nmearl** [comment]
Yeah, there should _always_ be a default wcs -- certainly oversight, which I think I fix in the [GWCS refactor PR](https://github.com/astropy/specutils/pull/462/files#diff-56be0a6d615d551046cefc37664eeae4).

I think whatever short circuit happens is the cause of #463 as well.
