### ISSUE TITLE
Errors on estimated parameters from specutils.fitting.fit_lines

### ISSUE THREAD

**Issue by gmduvvuri** [astropy/specutils#474]
Hello,
Is there a good way to access the errors on parameters estimated through the fit_lines function? It would be in the Fitter.fit_info dictionary, but this is not returned by fit_lines.

Thanks,
Girish.

**Comment by nmearl** [comment]
The fit information dictionary is not returned or stored by default (we are looking into ways to attaching parameter uncertainties to the returned model quantities). Currently, it is possible to access the fitter if you provide it yourself to the `fit_lines` function:

```python
from astropy.modeling.fitting import LevMarLSQFitter

fitter = LevMarLSQFitter()
models = fit_lines(spectrum, model, fitter=fitter)

print(fitter.fit_info)
```

Hope this helps for now!

**Comment by gmduvvuri** [comment]
This solves my current problem. But related to it: If I fit the continuum and subtract it from a Spectrum1D with uncertainties, how are the uncertainties updated considering the noise associated with subtraction separately from the noise associated with the continuum estimation?

**Comment by nmearl** [comment]
The fitted continuum knows nothing about the uncertainties, you're just evaluating a model that _represents_ the continuum and getting back an array. Before your subtraction, you'll have to re-compose a new `Spectrum1D` object with uncertainties representing a continuum-subtracted spectrum that represents the continuum, and then subtract the two `Spectrum1D` objects, which should propagate uncertainties.

**Comment by rayadastidar** [comment]
Hi!

> you'll have to re-compose a new Spectrum1D object with uncertainties representing a continuum-subtracted spectrum that represents the continuum

I did not understand what should be the uncertainty argument in new Spectrum1D object for the continuum.
