### ISSUE TITLE
bit of a problem with `spectrum.wavelength` in the docs

### ISSUE THREAD

**Issue by SaOgaz** [astropy/specutils#475]
So I've accidentally run across what really boils down to a documentation problem.  I had been using `my_spec1D.wavelength` the way I should have used `my_spec1D.spectral_axis`, not realizing that the `wavelength` attribute was getting auto-converted to Angstroms.  The reason I didn't realize this is because multiple examples in the docs make calls to `wavelength` with no notes about how the units for that get auto-updated.  I imagine a lot of these doc examples should be using `spectral_axis` and just haven't been updated.

Conversely, there's no documentation of `spectral_axis` or `spectral_axis_unit` in the API docs for `Spectrum1D`: https://specutils.readthedocs.io/en/latest/api/specutils.Spectrum1D.html?highlight=wavelength.

Does this take make sense to everyone or am I still mis-understanding something about the intended usage of these attributes.

**Comment by dhomeier** [comment]
Sounds related to #466, i.e. it's probably not just the documentation, but also argument checking that needs improvement.

**Comment by nmearl** [comment]
Docs now use `spectral_axis` instead of `wavelength`, and more information is provided about when to use which and how they are handled.
