### ISSUE TITLE
Fitting Continuum + Model together with units

### ISSUE THREAD

**Issue by gmduvvuri** [astropy/specutils#477]
Below I've pasted a minimal working example trying to test fitting continuum and lines together. It seems to fail because of the compound model not having compatible units. Is there a documented example that shows how to fit continuum and lines simultaneously?

`import astropy.units as u
import numpy as np
from astropy.modeling.models import Gaussian1D
from astropy.nddata import StdDevUncertainty
from astropy.modeling.fitting import LevMarLSQFitter
from astropy.modeling.polynomial import Polynomial1D
from specutils import Spectrum1D, SpectralRegion
from specutils.fitting import fit_lines, fit_generic_continuum

flux_unit = u.Unit('erg cm-2 s-1 AA-1')
wave_unit = u.AA

wave_arr = np.linspace(100, 200, 100) * u.AA
continuum = (1 * wave_arr * (flux_unit / wave_unit))
continuum += (1e-4 * (wave_arr**2) * (flux_unit / (wave_unit**2)))
continuum += 10 * flux_unit
continuum += np.random.normal(0.0, 1e-1, np.shape(continuum)) * flux_unit

true_gaussian = Gaussian1D(amplitude=2 * flux_unit,
                           mean=150 * wave_unit,
                           stddev=5 * wave_unit)

flux = continuum + true_gaussian(wave_arr)
uncertainty = 1e-1 * np.ones((len(continuum)))
uncertainty = StdDevUncertainty(uncertainty)

spec = Spectrum1D(spectral_axis=wave_arr, flux=flux, uncertainty=uncertainty)
mask_region = SpectralRegion(145 * wave_unit, 165 * wave_unit)
fitter = LevMarLSQFitter()
continuum_model = fit_generic_continuum(spec, exclude_regions=mask_region,
                                        fitter=fitter, model=Polynomial1D(2))

fit_gaussian = Gaussian1D(amplitude=1e-8 * flux_unit,
                          mean=145 * wave_unit,
                          stddev=2 * wave_unit)

combined_fit = fit_lines(spec, fit_gaussian + continuum_model,
                         fitter=fitter)
model = combined_fit(wave_arr)`

**Comment by nmearl** [comment]
This is technically not a supported use case -- specutils only implements basic modeling and fitting support for aspects of spectra. With that said, you can get what you want with a couple of edits, change your `fit_gaussian` and `combined_fit` as below:

```
fit_gaussian = Gaussian1D(amplitude=1e-8, mean=145, stddev=2)
combined_fit = fit_lines(spec, fit_gaussian + continuum_model.unitless_model, fitter=fitter)
```

And your model should work. Note that your continuum is very dominant.

**Comment by gmduvvuri** [comment]
Thank you for helping. For now I'm using my own fitting code with units removed from the arrays, but would this type of simultaneous fitting belong in a different astropy-affiliated package?

**Comment by nmearl** [comment]
You can try using the [spectacle package](https://spectacle-py.readthedocs.io/en/latest/), which focuses on creating a single `Spectral1D` model object representing spectral data, with units.
