### ISSUE TITLE
Import dosent work for snr_derived in version 0.5.2

### ISSUE THREAD

**Issue by lib-j** [astropy/specutils#501]
Following commands results in these errors.

from specutils.analysis import snr_derived 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-92db2545d73d> in <module>
----> 1 from specutils.analysis import snr_derived

ImportError: cannot import name 'snr_derived'

Having explored the code, even the following line also fails:

from specutils.analysis.uncertainty import snr_derived

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-cff27c1dd37e> in <module>
----> 1 from specutils.analysis.uncertainty import snr_derived

ImportError: cannot import name 'snr_derived'

**Comment by simontorres** [comment]
I checked the code and that function does not exist in 0.5.2

**Comment by lib-j** [comment]
Hi Simon,

I was working off the example located from here:
https://specutils.readthedocs.io/en/latest/analysis.html#snr
which is where the above import lines came from.

furthermore, the github files in this repo have such a function in file specutils.analysis.uncertainty (as shown here: https://github.com/astropy/specutils/blob/master/specutils/analysis/uncertainty.py#L94-L136), but i dont know what version the github repo is at, due to a lack of a __version__.py, but assumed it was inline with the read the docs.

any advice on getting this working would be appreciated.

**Comment by nmearl** [comment]
Hey @lib-j. Seems to be an issue with which documentation is presented as default (we will fix this!) Currently, the latest _release_ version is v5.2, so if you `pip install specutils`, you won't find the `snr_derived` function.

If you install the latest development version (the version currently on github can be found in [this file](https://github.com/astropy/specutils/blob/master/setup.cfg#L56)), you will have access to the `snr_derived` function. You can install the latest dev version by doing `pip install git+https://github.com/astropy/specutils`.

You can also get the version of specutils you are currently running by printing `specutils.__version__` at a command prompt.

Hope this helps.

**Comment by simontorres** [comment]
is **v5.2** a typo? should it be **0.5.2** or am I missing something?
