### ISSUE TITLE
Unable to import LinearInterpolatedResampler. Using python 3.7.3 and specutils 

### ISSUE THREAD

**Issue by Shru-Tri** [astropy/specutils#502]

**Comment by nmearl** [comment]
Hey @shruti1980, can you please provide the traceback that you're seeing?

**Comment by shruti1980** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-c3a2198153ef> in <module>
     36 new_disp_grid = np.arange(4323, 5459, 3)
     37 
---> 38 fluxcon = LinearInterpolatedResampler()
     39 new_spec_fluxcon = fluxcon(input_spec, new_disp_grid) # doctest: +IGNORE_OUTPUT
     40 f, ax = plt.subplots()  # doctest: +IGNORE_OUTPUT

NameError: name 'LinearInterpolatedResampler' is not defined

**Comment by shruti1980** [comment]
> Hey @shruti1980, can you please provide the traceback that you're seeing?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-defbc9a6e24b> in <module>
     33 ax.step(input_spec.spectral_axis, input_spec.flux)
     34 
---> 35 from specutils.manipulation import LinearInterpolatedResampler
     36 new_disp_grid = np.arange(4323, 5459, 3)
     37 

ImportError: cannot import name 'LinearInterpolatedResampler' from 'specutils.manipulation' (/home/shruti/anaconda3/lib/python3.7/site-packages/specutils-0.5.2-py3.7.egg/specutils/manipulation/__init__.py)

**Comment by shruti1980** [comment]
Above is the  correct traceback when I am trying to import the Resampler as defined in the documentation.

**Comment by shruti1980** [comment]
Hi, 

Following is the traceback 

############################### 

ImportError Traceback (most recent call last)
in 
33 ax.step(input_spec.spectral_axis, input_spec.flux)
34
---> 35 from specutils.manipulation import LinearInterpolatedResampler
36 new_disp_grid = np.arange(4323, 5459, 3)
37 

ImportError: cannot import name 'LinearInterpolatedResampler' from
'specutils.manipulation'
(/home/shruti/anaconda3/lib/python3.7/site-packages/specutils-0.5.2-py3.7.egg/specutils/manipulation/INIT.py)


##################################### 

Reg 

Shruti 

On 2019-08-21 16:47, Nicholas Earl wrote:

> Hey @shruti1980 [1], can you please provide the traceback that you're seeing? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/shruti1980
[2]
https://github.com/astropy/specutils/issues/502?email_source=notifications&amp;email_token=AKLVBFDAMHT6EK6LLFECQB3QFWLVBA5CNFSM4IONH2K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD425FCQ#issuecomment-523621002
[3]

**Comment by shruti1980** [comment]
Can anybody guide me how to resolve this?

**Comment by SaOgaz** [comment]
Hi @shruti1980, when did you last install specutils? This is a relatively new class.

**Comment by nmearl** [comment]
Indeed. `LinearInterpolatedResampler` does not exist in the current release version (v5.2). To get access, you must install the latest development version. You can do this at the command like by typing `pip install git+https://github.com/astropy/specutils`.
