### ISSUE TITLE
find_lines_threshold noise_factor strange behaviour

### ISSUE THREAD

**Issue by kyika** [astropy/specutils#504]
Hi,

I am using [find_lines_threshold](https://specutils.readthedocs.io/en/stable/api/specutils.fitting.find_lines_threshold.html#specutils.fitting.find_lines_threshold) to find emission lines of a spectrum, according the document, I think the function detects lines whose flux higher than noise_factor*uncertainty, but for my spectrum, I got more lines when I set the noise_factor to 100 than 10, would you like to explain it? Thanks in advance.

software information:
macOS 10.14
specutils 0.5.2

(Attached is the spectrum I used and the code)
https://drive.google.com/file/d/163mZFl6pqdn6AH3Li-nZ27zt_zu3rc0F/view?usp=sharing
```python
import os,shutil,glob

import numpy as np
import pandas as pd

from astropy import units as u

from IPython.display import display

from specutils import Spectrum1D, SpectralRegion
from specutils.manipulation import noise_region_uncertainty
from specutils.fitting import find_lines_threshold


operaspec = np.load(file='/Users/smao/mydrive/code/plot_spec/bug/spec.npy')

def get_noiRegion(spec,threshold):
    crit = list(spec[1]<threshold)
    end = 0
    ll=[]
    while True:
        try:
            start = crit.index(True,end)
            end = crit.index(False,start)
        except ValueError:
            break
        ll.append((start,end))
    ll = [elem for elem in ll if elem[1]-elem[0]>10]
    noiRegion = SpectralRegion([elem*u.pixel for elem in ll])
    
    return noiRegion

noise_factor = 10

spec = operaspec
perc = 10
threshold = np.percentile(spec[1],perc)
spectrum = Spectrum1D(flux=spec[1]*u.electron,spectral_axis=spec[0]*u.nm)
noiRegion = get_noiRegion(spec,threshold)
spectrum = noise_region_uncertainty(spectrum,noiRegion)
lines = find_lines_threshold(spectrum, noise_factor=noise_factor)
display(lines)


noise_factor = 100

spec = operaspec
perc = 10
threshold = np.percentile(spec[1],perc)
spectrum = Spectrum1D(flux=spec[1]*u.electron,spectral_axis=spec[0]*u.nm)
noiRegion = get_noiRegion(spec,threshold)
spectrum = noise_region_uncertainty(spectrum,noiRegion)
lines = find_lines_threshold(spectrum, noise_factor=noise_factor)
display(lines)

```

**Comment by andresgur** [comment]
Did you subtract the continuum? 

From the docs:
"This method only works with continuum-subtracted spectra and the uncertainty must be defined on the spectrum. To add the uncertainty, one could use noise_region_uncertainty to add the uncertainty."

For me, I also observed a weird behaviour. I see some lines that are detected with a factor 20 not being detected when lowering the noise factor to 5...

In my case this might be cause the uncertainties are not propagated when subtracting the modelled continuum, but I may be wrong...

**Comment by kyika** [comment]
Hi,

Thank you for your reply! I don't think I subtracted the continuum, I was using the raw data. After moving the baseline to zero, the function works better now, I can get more lines for a smaller factor. Thank you very much!
