### ISSUE TITLE
export the output of flux-resampling to a file!  

### ISSUE THREAD

**Issue by Shru-Tri** [astropy/specutils#507]

**Comment by nmearl** [comment]
If `new_spec_fluxcon` is already a `Spectrum1D`, you don't need to re-create a new spectrum object. You can simply do a `spec.write("my_output.fits", format="fits-writer")`.

You can also output directly to ascii by defining the output format for the `Table` object:

```python
@custom_writer("acii-writer")
def generic_ascii(spectrum, file_name, **kwargs):
    flux = spectrum.flux.value
    disp = spectrum.dispersion.value
    meta = spectrum.meta

    tab = Table([disp, flux], names=("dispersion", "flux"), meta=meta)

    tab.write(file_name, format="ascii")
```

Alternatively, your first attempt of writing to a file should work as well, but note that `new_spec_fluxcon.spectral_axis[i]` returns a [`Quantity`](https://docs.astropy.org/en/stable/units/) object. So, based on your print formatting, you might want to do `new_spec_fluxcon.spectral_axis[i].value`.
