### ISSUE TITLE
Be a bit clearer on when "spectral_axis" vs "wavelength"/etc are relevant

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#512]
I first noticed this in #478, but #466 is also relevant: we don't really have a consistent stance on when to use the "real" `.spectral_axis` vs `.wavelength`/`.frequency`/etc "convenience" accessors.  I see the philosophy as something like: when talking about anything subtle/complex, it's best to use `.spectral_axis` because it's the "real" attribute and has fewer layers of conversion/etc.  `.wavelength`/`.frequency` are there for two things: 
1. convenience, i.e., for plotting or human-readable display, and 
2. when you really want a wavelength or a frequency, even if you `spectral_axis` is in the "other" one.  (e.g., if you're making a galaxy SED where some measurements are from an instrument that is traditionally shown in frequency, whereas others are traditionally in wavelength, but you want a plot that shows all of them in wavelength).

Neither of these subtleties really come out in the current docs - it currently comes across sort of as "randomly wavelength and spectral_axis seem to get used interchangably".  That should be fixed.

**Comment by nmearl** [comment]
Addressed in #532. More specific cases should be opened in new issues.
