### ISSUE TITLE
Setting up stages for travis

### ISSUE THREAD

**Issue by bsipocz** [astropy/specutils#514]
E.g. having stages would be rather useful, there is no need to run the whole matrix and populate the queue with failing jobs when there those failures would be already present in a small number of initial jobs (e.g one test job and the codestyle one).

**Comment by nmearl** [comment]
Is there an example repo that implements the travis stages?

**Comment by bsipocz** [comment]
Sure. the package-template does it, as well as e.g. astropy/photutil/astroquery etc.

I'm happy to open a quick PR if you find that helpful.
