### ISSUE TITLE
0.6: doctests failures

### ISSUE THREAD

**Issue by olebole** [astropy/specutils#521]
When running the tests on the source package, I get the following failures:
```
___________________________ [doctest] docs/index.rst ___________________________
061 
062     >>> from specutils import Spectrum1D
063     >>> lamb = 10**specdata['loglam'] * u.AA # doctest: +REMOTE_DATA
064     >>> flux = specdata['flux'] * 10**-17 * u.Unit('erg cm-2 s-1 AA-1') # doctest: +REMOTE_DATA
065     >>> spec = Spectrum1D(spectral_axis=lamb, flux=flux) # doctest: +REMOTE_DATA
066 
067     And we plot it:
068 
069     >>> f, ax = plt.subplots()  # doctest: +IGNORE_OUTPUT
070     >>> ax.step(spec.spectral_axis, spec.flux) # doctest: +IGNORE_OUTPUT
UNEXPECTED EXCEPTION: NameError("name 'spec' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest index.rst[14]>", line 1, in <module>

NameError: name 'spec' is not defined

/tmp/autopkgtest-lxc.1sg_etm6/downtmp/build.Y1W/src/docs/index.rst:70: UnexpectedException
_______________________ [doctest] docs/manipulation.rst ________________________
151     Then we re-format this dataset into astropy quantities, and create a
152     `~specutils.Spectrum1D` object:
153 
154     >>> from specutils import Spectrum1D
155     >>> lamb = 10**specdata['loglam'] * u.AA # doctest: +REMOTE_DATA
156     >>> flux = specdata['flux'] * 10**-17 * u.Unit('erg cm-2 s-1 AA-1') # doctest: +REMOTE_DATA
157     >>> input_spec = Spectrum1D(spectral_axis=lamb, flux=flux) # doctest: +REMOTE_DATA
158 
159     >>> f, ax = plt.subplots()  # doctest: +IGNORE_OUTPUT
160     >>> ax.step(input_spec.spectral_axis, input_spec.flux) # doctest: +IGNORE_OUTPUT
UNEXPECTED EXCEPTION: NameError("name 'input_spec' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest manipulation.rst[31]>", line 1, in <module>

NameError: name 'input_spec' is not defined

/tmp/autopkgtest-lxc.1sg_etm6/downtmp/build.Y1W/src/docs/manipulation.rst:160: UnexpectedException
```
Full test log [here](https://salsa.debian.org/debian-astro-team/specutils/-/jobs/333034/raw).

**Comment by nmearl** [comment]
Thanks. Can you please include your system specs as well?

**Comment by olebole** [comment]
Sure. That is Debian Linux unstable (bullyeye), 
* Python 3.7.4+, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
* Pytest plugins: doctestplus-0.4.0, remotedata-0.3.2, arraydiff-0.3, openfiles-0.4.0

**Comment by nmearl** [comment]
Do you see the same issue when you build the docs directly using sphinx? Also, what is your local version of sphinx?

**Comment by olebole** [comment]
I currently don't build the documentation. However, I would guess that during sphinx-build, the tests are not executed. Sphinx version is 1.8.5, but sphinx is not installed during the test - the doctests are directly taken from the rst files.

**Comment by nmearl** [comment]
Are you running with the `--remote-data` flag? The `spec` object requires data downloaded from the internet, but by default, the regular testing infrastructure will not attempt to download data from  the internet. (Hence why the tests pass in travis setup and the docs build correctly on readthedocs -- they are setup to use the `--remote-data` flag.)

```
$ python setup.py test --remote-data
```

**Comment by olebole** [comment]
I use 

    $ pytest-3 --remote-data=none --doctest-rst

So, I ignore the `+REMOTE_DATA` doctest lines (since we don't have remote access here).
IMO, also all tests that indirectly depend on remote data need to be marked with `+REMOTE_DATA` as well, otherwise they get executed.

**Comment by olebole** [comment]
Thanks! I can confirm that it works correctly.
