### ISSUE TITLE
Issue with pytest

### ISSUE THREAD

**Issue by ibusko** [astropy/specutils#540]
I am getting errors when I try to run a test in the specutils/tests subdirectory. I am guessing it has to do with the test configuration file conftest.py, but I am not sure.

I can create a simple dummy pytest file and run it successfully from the command line, as long as it is located outside the top specutils directory structure. However, moving this dummy test to any place inside the specutils main tree and running it, I get this error:
9:38 AM
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --remote-data=any --doctest-rst
 inifile: /Users/busko/Projects/specutils/setup.cfg
 rootdir: /Users/busko/Projects/specutils

That is, pytest is picking up something inside the tree and getting confused by that. I am guessing it may be connected to conftest.py because in conftest there is a reference to a remote data path, and the error message reports something about remote data. But the spelling is different in each case.

**Comment by dhomeier** [comment]
Is there a reason why your file needs to be placed inside the specutils dir (i.e. is it something you plan to add to specutils)? While inside this dir, pytest will pick up the specutils-specific customisations from `conftest.py` and `setup.cfg`, but it is not quite clear why it then does not recognise these options...

**Comment by ibusko** [comment]
@dhomeier yes, the test script is being added to specutils. But I was able to go around this by running it from an external script in this way:

import astropy
astropy.test(test_path='../specutils/specutils/tests/test_correlation.py')

**Comment by nmearl** [comment]
@ibusko What command are you running when the file is inside the specutils directory? What version of pytest are you using when you run the command?

**Comment by ibusko** [comment]
@nmearl it's weird, because I can no longer reproduce the problem. pytest is working with both my dummy pytest file, as well as with the test scripts in specutils. I am guessing it's somthing I did with the python env in the last couple weeks. I am closing the issue because it's no longer relevant.
