### ISSUE TITLE
Error in importing cextinction

### ISSUE THREAD

**Issue by Astronomer-Mohit** [astropy/specutils#541]
To whom it may concern,

I have installed latest version of specutils (version '0.6'), and have the latest version of cython ('0.29.13') and astropy ('3.2.2') installed as well, in the my anaconda environment,'astroconda'.
However, I am getting the following error when I run this command - 'from specutils import cextinction'.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-4301274db4f2> in <module>
----> 1 from specutils import cextinction

ImportError: cannot import name 'cextinction' from 'specutils' (/home/xxxx/anaconda3/envs/astroconda/lib/python3.7/site-packages/specutils/__init__.py)
---------------------------------------------------------------------------

I would greatly appreciate any help in resolving this issue.

Thanks,
Mohit

**Comment by dhomeier** [comment]
This module was removed more than 2 years ago, after version 0.2.1. Actually it appears that virtually the entire old specutils was wiped at the time, but I could not find any documentation or changelog entry on how its development continued, or what would be the recommended replacement for extinction calculations. @nmearl - do you have any further info?

**Comment by nmearl** [comment]
@Astronomer-Mohit the legacy specutils was branched off in version 0.2.1 and now lives in the [`legacy-specutils` branch](https://github.com/astropy/specutils/tree/legacy-specutils). The new specutils does not contain a `cextinction` module. There is a currently open issue to introduce wrappers for the [dust extinction](http://dust-extinction.readthedocs.io/en/latest/) package, but work has not yet begun on that.

**Comment by Astronomer-Mohit** [comment]
@dhomeier and @nmearl , thanks a lot for your prompt replies. I really appreciate your messages! Although I could not get around with specutils, but I found another way to solve my problem, and it worked!
