### ISSUE TITLE
Do some perfomance testing of the warn_continuum_below_threshold decorator

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#546]
This is a follow-on to #535 and #538.  More details are in #535, but the core thing here is to do number 3 of https://github.com/astropy/specutils/issues/535#issuecomment-541783378 .  (#538 did 1 and 2).  Basically, take a few realistic spectra, do a few operations that require continuum-subtracted spectra (easiest ones might be line-flux measurements, or line-finding?), and check how much slower they are with the continuum checker implemented in #538 on vs off. That will help us know if we really want to expand it to everything.

**Comment by ibusko** [comment]
I did run tests using a slightly modified version of the test function `test_find_lines_threshold`  in `specutils/tests/test_fitting.py`. Basically, it runs the `find_lines_threshold` function 1000 times in a timing loop, using as spectrum an instance created by the test data creation functions in the same test file.

I found that the code with check decorator runs systematically 1.6-1.7 times slower than without the decorator, regardless of the input spectrum. I believe this result shouldn't change significantly for other types of spectrum, but may be different when using masked arrays (which typically incur in a large speed penalty anyways).

**Comment by eteq** [comment]
@ibusko - that approach to testing sounds good, and 1.6-1.7 sounds plausible.  But for "a few realistic spectra" here, I think we need a few more examples: can you try it with a few different sizes of spectrum?  it looks to me like `test_find_lines_threshold` is a spectrum of ~200 pixels, which is relatively small.  So it would be useful to also try these cases:
* spectrum of size 2048 (A fairly typical MOS spectrum)
* spectrum of size 100000 (more like the volume one expects from an IFU.)

And maybe also repeat the 3 spectrum size cases but adding the decorator to `line_flux` and using the test `test_analysis.test_line_flux`?

I think that spans the realistic space of "small or large spectrum" as well as "fast or slow analysis function"?

**Comment by ibusko** [comment]
@eteq these are the factors I found:

2048 data points: 1.4-1.5 slower
100000 data points: 1.2 slower

Thus it seems that for very large spectra it's not much worse. Just worse. I am sure it can be justified as acceptable, depending on the application.

(`line_flux` analysis is coming...)

**Comment by eteq** [comment]
Ok, great, @ibusko! This is definitely the info needed.  The `line_flux` one is worrisome, though. Why does it get slower for larger number of data points?

**Comment by eteq** [comment]
Turns out the answer is probably that `line_flux` only works on a small fraction of the spectrum, whereas the decorator runs over the whole spectrum. So it makes sense that the decorator gets worse as the spectrum gets bigger because the decorator has more it has to work on.

That's possibly a deal breaker.  Will have to think more on it, but that can be discussed in #547 since that's the next step.  The performance testing itself is done so I'll close this.
