### ISSUE TITLE
fit continuum error

### ISSUE THREAD

**Issue by xiangyun19** [astropy/specutils#563]
**Dear authors,**

I have tried to run the example codes on the official documents. But I can not run through the first example. **The follow code are from the documents.**

from astropy.io import fits
from astropy import units as u
import numpy as np
from matplotlib import pyplot as plt
from astropy.visualization import quantity_support
quantity_support()  # for getting units on the axes below 

f = fits.open('https://dr14.sdss.org/optical/spectrum/view/data/format=fits/spec=lite?plateid=1323&mjd=52797&fiberid=12')  
# The spectrum is in the second HDU of this file.
specdata = f[1].data 
f.close() 

from specutils import Spectrum1D
lamb = 10**specdata['loglam'] * u.AA 
flux = specdata['flux'] * 10**-17 * u.Unit('erg cm-2 s-1 AA-1') 
spec = Spectrum1D(spectral_axis=lamb, flux=flux) 

f, ax = plt.subplots()  
ax.step(spec.spectral_axis, spec.flux) 

from specutils.fitting import fit_generic_continuum
cont_norm_spec = spec / fit_generic_continuum(spec)(spec.spectral_axis) 
f, ax = plt.subplots()  
ax.step(cont_norm_spec.wavelength, cont_norm_spec.flux)  
ax.set_xlim(654*u.nm, 660*u.nm)  

plt.show()

**When I tried to run this script, I received the following error:**

WARNING:root:'asciireader' data loader provided for Spectrum1D without explicit identifier or list of compatible extensions
WARNING:root:'hpareader.py' data loader provided for Spectrum1D without explicit identifier or list of compatible extensions
Traceback (most recent call last):
  File "specfitting.py", line 23, in <module>
    cont_norm_spec = spec / fit_generic_continuum(spec)(spec.spectral_axis) 
  File "/home/xiangyun/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 57, in fit_generic_continuum
    return fit_continuum(spectrum_smoothed, model, fitter, exclude_regions, weights)
  File "/home/xiangyun/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 97, in fit_continuum
    continuum_spectrum = fit_lines(spectrum, model, fitter, exclude_regions, weights)
  File "/home/xiangyun/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 360, in fit_lines
    ignore_units, **kwargs)
  File "/home/xiangyun/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 476, in _fit_lines
    _strip_units_from_model(model, spectrum, convert=not ignore_units)
  File "/home/xiangyun/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 604, in _strip_units_from_model
    compound_model = model_in.n_submodels() > 1
TypeError: 'int' object is not callable

I do not know what is going wrong, please help me.
Thank you.

**Comment by nmearl** [comment]
Hello @xiangyun19, what version of specutils and astropy are you currently using?

**Comment by Ramlalunni** [comment]
The exact same error has occurred for me today. Is there any way to fix this?

**Comment by nmearl** [comment]
I'd love to help, but I need more information -- what version of specutils and astropy are you using? The error suggests that the installed astropy version is out dated.

**Comment by Ramlalunni** [comment]
```
import astropy, specutils
astropy.__version__
```
Out[2]: '4.0'
`specutils.__version__`
Out[3]: '0.6'

conda update specutils and conda update astropy give the output:

    All requested packages already installed.

Please help out.

**Comment by nmearl** [comment]
Your specutils version is outdated, current version is 0.7. Try updating using pip instead of conda:

```python
pip install specutils --upgrade
```

**Comment by Ramlalunni** [comment]
Hi,

I tried out removing specutils from my Anaconda, and reinstalled it by cloning from the specutils GitHub repository. Now I have specutils version '0.8.dev1906', and everything seems to work normally. The error is no longer showing. 

Thank you.
