### ISSUE TITLE
fix the astropy LTS travis build

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#565]
Right now the LTS travis build is failing because it's going all the way back to 2.x for some reason (which is no longer compatible with specutils).  See https://travis-ci.org/astropy/specutils/jobs/632616063 for an example.  I don't understand why it's doing this given that 4.0 is now the LTS.  It might be that something in ci-helpers needs updating (perhaps @bsipocz can advise?)

Not urgent by any means since the LTS already is getting tested since it's the latest stable.  But something to fix so that we can get green check marks in PRs...

**Comment by bsipocz** [comment]
Yes, LTS hasn't yet been updated in ci-helpers (I was kept it pending due to the delay in conda packaging, etc.)
