### ISSUE TITLE
specutils read_fits

### ISSUE THREAD

**Issue by mariollerena1991** [astropy/specutils#568]
Hi, 
Maybe someone can help me with this issue. I am trying to use a code that uses read_fits from specutils.io but it can not be imported. How can I install the version in which it is still supported? currently, I am using astropy 3.2.1 and specutils 0.5.2
Thanks!

**Comment by simontorres** [comment]
Can you copy/paste the full traceback please?

**Comment by nmearl** [comment]
Can you also include the code you're using to read in your data?

**Comment by mariollerena1991** [comment]
The part of the code that uses read_fits is:

def read_spectra(filename, scaleFlux):
    x = []
    y = []
    try:
        spectra = read_fits.read_fits_spectrum1d(filename)
    except (OSError, IOError):
        spectra = read_fits.read_fits_spectrum1d(os.path.join(constants.DATA_FILES, filename))

    if isinstance(spectra, list):
        for spectrum in spectra:
            x.append(spectrum.dispersion / u.angstrom)
            y.append(spectrum.flux * scaleFlux)
        x = np.array(x)
        y = np.array(y)
    else:
        x = np.array([spectra.dispersion / u.angstrom])
        y = np.array([spectra.flux * scaleFlux])

    return x, y

**Comment by nmearl** [comment]
`read_fits` was removed from specutils several versions ago. If you want to use the old legacy version of specutils, you can install it using:

`pip install "specutils==0.2.2"`

**Comment by mariollerena1991** [comment]
thanks! it worked with that version.
