### ISSUE TITLE
Priority system in loaders no longer works

### ISSUE THREAD

**Issue by nmearl** [astropy/specutils#584]
Loaders are assigned priorities and they should be taken into consideration when conflicts arise amongst potential loaders when a format is not explicitly give.

**Comment by dhomeier** [comment]
Those are passed as kwarg to `data_loader`, right? But where are they (supposed to be) assigned? I'd expect they might be written into the `@data_loader` decorators, but can't find one that has a `priority` value or seems to have had one in recent times...

**Comment by nmearl** [comment]
The loader priorty is stored [here](https://github.com/astropy/specutils/blob/master/specutils/io/registers.py#L79), but it looks like we need to be more specific about using it (before, it seemed that the order in the registry was part of the determination for which loader to choose). It seems at some point, we took them out during a refactor.

I'm imagining that we'll want to find all loaders that meet the identifier criteria. If there is more than one, simply compare priorities and return the appropriate loader.

**Comment by aragilar** [comment]
This is fixed by #757.
