### ISSUE TITLE
Combining Two Spectral Cubes

### ISSUE THREAD

**Issue by robelgeda** [astropy/specutils#588]
The user may want to combine two cubes to add spaxels or to extend the spectral range of the cube. How should each of these cases be handled?

**Comment by nmearl** [comment]
What does the data look like that's being parsed? Is the wavelength solution an array or fits information? In general, they would have to extend their flux data themselves and create a new `Spectrum1D` object with a wavelength solution that is appropriate for the new data range.

**Comment by robelgeda** [comment]
For the wavelength situation, it would be like combining a spectrum 1d object like:
```
>>> spec1 = Spectrum1D(spectral_axis=np.arange(1, 50) * u.micron, flux=np.random.randn(49)*u.Jy)
>>> spec2 = Spectrum1D(spectral_axis=np.arange(51, 100) * u.micron, flux=(np.random.randn(49)+1)*u.Jy)
>>>
>>> new_spectral_axis = np.concatenate([spec1.spectral_axis.value, spec2.spectral_axis.to_value(spec1.spectral_axis.unit)]) * spec1.spectral_axis.unit
>>>
>>> resampler = LinearInterpolatedResampler(extrapolation_treatment='zero_fill')
>>> new_spec1 = resampler(spec1, new_spectral_axis)
>>> new_spec2 = resampler(spec2, new_spectral_axis)
>>>
>>> final_spec = new_spec1 + new_spec2
```
But in this case it would be done on a cube.

**Comment by nmearl** [comment]
This should work with `SpectrumCollection` objects -- did you run into issues?

**Comment by robelgeda** [comment]
I didn't know this. Is there an example notebook for `SpectrumCollection` objects?

**Comment by nmearl** [comment]
(Note that "should" is used loosely, 😁.) There isn't a specific notebook for `SpectrumCollection`, but all the specutils objects should _behave_ the same. So in the documentation, a user should be able to replace an example that uses `Spectrum1D` with `SpectrumCollection` and get out a reasonable answer.

I'd say in the code above, you'd want to try replacing `spec1` and `spec2` with `SpectrumCollections` (representing cubes), and see if the rest of the behavior works. If it doesn't, then that is definitely something we should work on!

**Comment by nmearl** [comment]
Closing for now since this isn't an _issue_ per se. Feel free to reopen when you get the chance to explore this a bit more.
