### ISSUE TITLE
Cube Indexing

### ISSUE THREAD

**Issue by robelgeda** [astropy/specutils#589]
How are spectral cubes indexed?

A hint might be found in one of the STScI JDADF notebooks, which indexes its cube as follows:

```
#Select spaxel
spec=data_cube[:,8,16]
specerr=error_cube[:,8,16]

#Composite model (powerlaw + PAHs + H2 + Atomic lines, no extinction)
generic_mod = p_law + silicate + pahs + gaussH2  + gaussAt

print(generic_mod.param_names)

#Fit and plot
spax_result=fit_and_plot(spec,specerr,generic_mod,generic_pars,False)

#Save results
save_modelresult(spax_result, 'OnePointResult.sav')

#Update generic model starting parameters
for par in spax_result.params:
    value=spax_result.params[par].value
    vary=spax_result.params[par].vary
    minus=spax_result.params[par].min
    if minus==float("-inf"):
        minus=None
    generic_pars[par].set(value,vary=vary,min=minus)
```

The way I see it,  it would be good to have the first two indices represent the spaxels and the third index represent a wavelength on the spectral axis. This way when the user indexes a spaxel position, we can provide a `Spectrum1D` object with the appropriate WCS properties. If they use a third index we know that they want a value so we return a quantity. 

Another usage I saw was distributing the cube to multiple threads or processes. There arises a second question of the properties of the returned object. Does editing values in the returned object change the values of the data stored in the cube object? If so, how would this work for a multiprocess workflow?
 
**Edits:**
- My recommendations from notebook
- Multiprocessing

**Comment by nmearl** [comment]
What is the data structure of `data_cube`?

**Comment by robelgeda** [comment]
It was a bumpy array

**Comment by nmearl** [comment]
It's not clear what the use case is, but I'd point you to the documentation on dealing with multi-dimensional data: https://specutils.readthedocs.io/en/stable/spectrum1d.html#multi-dimensional-data-sets

**Comment by robelgeda** [comment]
So if we had a 3D cube, how would you index, let's say, the pixel `(10, 10)` to get the spectra at that pixel across wavelengths?

**Comment by nmearl** [comment]
> The way I see it, it would be good to have the first two indices represent the spaxels and the third index represent a wavelength on the spectral axis. This way when the user indexes a spaxel position, we can provide a Spectrum1D object with the appropriate WCS properties. If they use a third index we know that they want a value so we return a quantity.

This is purposely not within the purview of specutils.

Specutils has no concept of a cube, and does not understand spatial dimensions. A `SpectrumCollection` by design is simply a collection of 1d spectra (i.e. a stack of `n` spectra representing every spaxel with `m` flux values), which means it has _at most_ two dimensions. If you were to read a cube into a `SpectrumCollection`, the `(10, 10)` spaxel would be found at the index `10 * data_cube.shape[0] + 10` (or in more general terms `axis1_index * length_of_axis1 + axis2_index`.

**Comment by robelgeda** [comment]
I see, thanks for the explanation! 
I think we should leave this ticket open for discussion. Not sure who to tag.

**Comment by nmearl** [comment]
I think we should bring @keflavich and @eteq in to the conversation. The main question is: where does `spectral-cube` stop and `specutils` begin -- what's the vision for cube support in `specutils`?

**Comment by keflavich** [comment]
I'd favor keeping them and their development as separate as possible, but I do want to make them talk to each other better. I'm pretty sure there's still an open PR in spectral-cube to return specutils spectrum1ds or use specutils as a mixin.

**Comment by robelgeda** [comment]
@nmearl given you question about `spectral-cube` it seems like you are saying cube users should be pointed to `spectral-cube` as opposed to working directly with `specutils`. Is my understanding correct?

**Comment by nmearl** [comment]
@robelgeda For spectroscopic analysis and manipulation functionality, specutils needs to support loading in multi-dimensional cube data and to be able to perform these functions over multi-dimensional data. 

However, we imagine the future being such the one dimensional spectrum object extracted from `spectral-cube` object will be represented as a `Spectrum1D`.

So for data for which all a user cares about is the spectral analysis, specutils should be able to parse and load the data. That said, it is not going to be capable of e.g. slicing a cube in such a way as to get back a 2d image. For that, `spectral-cube` would be used.

**Comment by nmearl** [comment]
I think we should open a new issue to continue the discussion about the `spectral-cube` and `specutils` integrations.
