### ISSUE TITLE
Cubes and numpy's where function

### ISSUE THREAD

**Issue by robelgeda** [astropy/specutils#590]
I found in the STScI JDADF sprints that where function is often used. If the cube in SpecUtils is technically a spectrum collection of `Spectrum1D` objects, how would numpy functions work on them?

**Comment by nmearl** [comment]
If general, you'd simply look over the collection and apply the numpy function to each individual `Spectrum1D` object. It'd help if you had an example of your use case.

**Comment by robelgeda** [comment]
For example:
```
#Spiral arm extraction region
arm_mask=np.where(((pahcube_neutral_flux>=0.155e-14) &((pahcube_ion_flux/pahcube_neutral_flux)>0.8) & (nuc_mask==0)),1,0)

#Inner disk extraction region        
pah_mask=np.where(((pahcube_neutral_flux>=0.155e-14) & (h2cube_flux<1e-15) & (nuc_mask==0)),1,0) - arm_mask
```

**Comment by nmearl** [comment]
Are you seeing issues with this in specutils? Seems that you want to simply replace all the references to the flux with value from the `.flux` attributes of a specutils object.

**Comment by robelgeda** [comment]
This makes sense to me. Closing this ticket.
