### ISSUE TITLE
Remove requirement on existence of WCSDIM to identify wcs1d-fits

### ISSUE THREAD

**Issue by aragilar** [astropy/specutils#601]
It looks like https://github.com/astropy/specutils/pull/192/commits/6e3689529d5b7fb3b62b3a7dccc1d4f9df8f5051 introduced the requirement that `WCSDIM` is in the header for a file a file to be considered a "wcs1d-fits" file. The `WCSDIM` seems to come from IRAF - I can't see anything in the standards at https://fits.gsfc.nasa.gov/fits_wcs.html requiring `WCSDIM`. I'm happy to create a PR which removes the line, but this assumes there's not some (currently) undocumented reason for requiring `WCSDIM`.

**Comment by dhomeier** [comment]
This has been changed in https://github.com/astropy/specutils/commit/4839369f2517754605d4956f8fa0933e0d1bc054#diff-920cf9c8fff1f949c94060dc2aeddad6
to `hdu[0].header.get('WCSDIM', 1) == 1`, i.e. it already assumes a default of 1 if the card is not present.
The test file `_v1410ori_20181204_261_Forrest_Sims.fit` e.g. does not have a `WCSDIM` key and can be read. Perhaps the test could be run without the `format='wcs1d-fits'` kwarg to make this clearer.
