### ISSUE TITLE
Hide or delete spectral_resolution method

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#604]
I just realized there's a `spectral_resolution` method of `Spectrum1D` which is quite old (~3 years) but has no implementation.  I think this is an artifact from when `Spectrum1D` was a concept API instead of actually being implemented.  This method should either be changed to ``raise NotImplementedError` instead of ``pass``, or perhaps just removed (or at least made private with a leading underscore) instead of left in the API seemingly to do something.

If I can find the time I might make a quick PR to do this a bit later.

**Comment by rosteen** [comment]
According to the [python docs](https://docs.python.org/3/library/exceptions.html#NotImplementedError) , NotImplementedError "should not be used to indicate that an operator or method is not meant to be supported at all". My vote is to remove or make private for now if we might want it later.

**Comment by hcferguson** [comment]
My recollection from the workshop a few years ago is that DESI was planning to carry around a line-spread function (LSF) in metadata; either that or a spectral-resolution value. It would be interesting to find out what they have implemented for their pipeline.

**Comment by rosteen** [comment]
I created a PR that removes the function, which seemed like the cleanest fix for the 1.0 release while we look into e.g. the DESI implementation and decide on what to do in the future.
