### ISSUE TITLE
Relax the requirement that SpectralRegion be in a increasing order

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#615]
To see the issue at hand, the following snippet is illustrative:
```
>>> spectral_axis = np.linspace(10, 1, 200) * u.GHz
>>> flux = np.random.randn(len(spectral_axis)) * u.Jy
>>> spec = specutils.Spectrum1D(spectral_axis=spectral_axis, flux=flux)
>>> manipulation.extract_region(spec, specutils.SpectralRegion([(3, 0)] * u.GHz))
<Spectrum1D(flux=...>
```
That works fine and extracts a spectrum around the 0-3 GHz range.  *However* the following gives an error:
```
>>> manipulation.extract_region(spec, specutils.SpectralRegion([(3, 0)] * u.GHz))
...
ValueError: Lower bound must be strictly less than the upper bound
```
That error is confusing because there's really no reason why the order should matter at all in spectral region - it's a one-dimensional segment so the user shouldn't have to care about getting the order right.  That's not just academic, either: frequency, wavelength, and energy can swap a seemingly "natural" order for the axis, so the user might use various different conventions for the ordering.  So they should be free to do that and have the `extract_region` machinery not freak out.

(Note that this has additional consequences than just `extract_region` itself because `extract_region` is used quite widely in other places where an analysis or manipulation step is applied to a region)

**Comment by nmearl** [comment]
I don't understand the error. In the snippet you show, you're calling `manipulation.extract_region(spec, specutils.SpectralRegion([(3, 0)] * u.GHz))` the same way each time?

**Comment by abeelen** [comment]
I am seeing a similar issue here : 
I am working with `specutils.Spectrum1D` where the `spectrum_axis` is defined in frequency, and thus, I wand to define `SpectralRegion` as  `specutils.SpectralRegion(1*u.GHz, 2*u.GHz)` which leads to the same

**Comment by abeelen** [comment]
This also imply a strange behavior on the `from_center` method, `specutils.SpectralRegion.from_center(1*u.GHz, 0.1*u.GHz)` leads to the same error

**Comment by abeelen** [comment]
Related to that, it seems that `specutils.extract_region` expect a wavelength ordered spectral axis

**Comment by nmearl** [comment]
@abeelen Thanks for the report! In general, frequency space should be descending (to match ascending wavelength space), but the issue with `from_center` is definitely a bug.

**Comment by nmearl** [comment]
@abeelen `extract_region` should already handle non-wavelength ordered spectral axes. Are you getting a specific error?

**Comment by DanRyanIrish** [comment]
I'm having the same issue because I'm working in energy.  @nmearl, is there a bugfix release planned for this issue?  If not, what's the timescale for the next release?  In the meantime I can revert to v0.7.

**Comment by eteq** [comment]
Realized just now that #656 only *partially* solved this by sort of papering around the behavior, not acutally fixing it, so I just re-opened this.

**Comment by eteq** [comment]
But I think #911 did, so closing...
