### ISSUE TITLE
Integrate SpectralCoord with SpectralCollection

### ISSUE THREAD

**Issue by rosteen** [astropy/specutils#616]
SpectralCoord has been implemented and is used in Spectrum1D, this task is to use it in SpectralCollection. Should be a fairly straight forward drop-in.

**Comment by rosteen** [comment]
Looks like a bit more work than I initially thought, after poking things for a bit to see how they currently work. I think SpectrumCollection will need to do some work internally to store the extra information built into SpectralCoord and make it available as arrays for vectorized computations.

@nmearl @eteq One small observation about SpectralCoord is that it's happy to take in a list of SpectralCoord objects and stack the main arrays for the resulting object, but quietly drops all the extra information (I tried just replacing u.Quantity() with SpectralCoord() to wrap a list of spectral axes to see what would happen). Might be useful to add a warning or something to point to SpectrumCollection as the tool for that use case.

**Comment by rosteen** [comment]
Do we want to allow each spectral_axis in the collection to be completely different with respect to the parameters (radial_velocity, doppler_rest, etc) that are part of a SpectralCoord? 

This task would be very simple if these parameters were required to be the same for each of the input spectra, but I've been thinking hard without coming to a solid conclusion about how to implement storing differing SpectralCoord parameters without breaking back-compatibility.  I'm not sure if the science use case demands that capability or not - some context would be useful.

**Comment by nmearl** [comment]
Yes, the `SpectralCoord` should be different for each `Spectrum1D` in the collection. This is because `SpectralCollection` contains potentially heterogeneous spectral axis definitions, so each one's `spectral_axis` should be different.

What issues are you seeing with making them complete different?

**Comment by rosteen** [comment]
Basically, as it is right now SpectrumCollection.spectral_axis is always an NxM Quantity, but there's no way to store multiple SpectralCoord objects as a single Quantity/SpectralCoord object and have them all retain their parameters. I think the best approach is to store a list of SpectralCoords internally and then serve up the information requested as multidimensional Quantities as needed, but I was hesitant to do that since I could see the internal machinery required being messy/inelegant.

**Comment by nmearl** [comment]
Ah, yes. I see what you mean now. Having the `spectral_axis` be one single `SpectralCoord` with a shared definition of attributes should actually be just fine. We have `SpectrumList` to deal with completely incompatible spectral axes definitions.

If this ends up being an issue, we can make changes later on, but I think this is a reasonable approach for our current definition of `SpectrumCollection`.

**Comment by rosteen** [comment]
Sounds good, I'll make sure to add appropriate checks and whatnot to check that those attributes are the same in the inputs.
