### ISSUE TITLE
Have the FluxConservingResampler use SpectralCoord's bin edge functionality

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#629]
This is an issue that depends on #626 getting finished.  But once that's done, the `FluxConservingResampler` should use the same way of understanding the "edge" of a bin as what #626 implements. 

This is a bit circular in that my hunch is that #626 might be implemented by taking some of the machinery from `FluxConservingResampler`.  But either way, it's important this circles back and ensures that the resampler machinery ends up consistent with `SpectralCoord` (and the pre-existing tests pass!)

**Comment by rosteen** [comment]
This was addressed but not closed, closing.
