### ISSUE TITLE
Spectrum1D error for combining spectra : ValueError: Flux must be a `Quantity` object

### ISSUE THREAD

**Issue by amanpkaur** [astropy/specutils#647]
**Specutils version 1.0**
**ipython 7.5.0, python 3.7.5**
I am trying to combine two spectra using SpectrumID and LinearInterpolatedResampler and I get this error: 
"Flux must be a `Quantity` object. 
To confirm, I ran an online example and obtained the same error. Here is the online example:
[Online Example](https://specutils.readthedocs.io/en/stable/api/specutils.manipulation.LinearInterpolatedResampler.html?fbclid=IwAR1Voyw7EatpAv7Byr5pAuGJDqiCFadKd7jSr_ztmsSt7OSXKbB4HGCG1NI)

**Code:**

`import numpy as np`
`import astropy.units as u`
`from specutils import Spectrum1D`
`from specutils.manipulation import LinearInterpolatedResampler`
`input_spectra = Spectrum1D(flux=np.array([1, 3, 7, 6, 20]) * u.mJy,spectral_axis=np.array([2, 4, 12, 16, 20]) * u.nm)`
`resample_grid = [1, 5, 9, 13, 14, 17, 21, 22, 23] * u.nm`
`fluxc_resample = LinearInterpolatedResampler()`
`output_spectrum1D = fluxc_resample(input_spectra, resample_grid)`
   
**Error: The last step "output_spectrum1D" produces the following error**     
                  
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f354941e168b> in <module>
      8 resample_grid = [1, 5, 9, 13, 14, 17, 21, 22, 23] * u.nm
      9 fluxc_resample = LinearInterpolatedResampler()
---> 10 output_spectrum1D = fluxc_resample(input_spectra, resample_grid)

/usr/local/lib/python3.7/site-packages/specutils/manipulation/resample.py in __call__(self, orig_spectrum, fin_spec_axis)
     37         Return the resulting `~specutils.Spectrum1D` of the resampling.
     38         """
---> 39         return self.resample1d(orig_spectrum, fin_spec_axis)
     40 
     41     @abstractmethod

/usr/local/lib/python3.7/site-packages/specutils/manipulation/resample.py in resample1d(self, orig_spectrum, fin_spec_axis)
    323         return Spectrum1D(spectral_axis=fin_spec_axis,
    324                           flux=out_flux,
--> 325                           uncertainty=new_unc)
    326 
    327 

/usr/local/lib/python3.7/site-packages/specutils/spectra/spectrum1d.py in __init__(self, flux, spectral_axis, wcs, velocity_convention, rest_value, redshift, radial_velocity, **kwargs)
     69         if flux is not None:
     70             if not isinstance(flux, u.Quantity):
---> 71                 raise ValueError("Flux must be a `Quantity` object.")
     72             elif flux.isscalar:
     73                 flux = u.Quantity([flux])

ValueError: Flux must be a `Quantity` object.

**Comment by dhomeier** [comment]
> 323 return Spectrum1D(spectral_axis=fin_spec_axis,
> 324 flux=out_flux,
> --> 325 uncertainty=new_unc)

That looks a bit odd, as if the installed library is not in sync with the one loaded in your session – have you tried to repeat this in a fresh ipython session?

Just to make sure, what do you get from
```
input_spectra.uncertainty
input_spectra.uncertainty is None
```

**Comment by amanpkaur** [comment]
> > 323 return Spectrum1D(spectral_axis=fin_spec_axis,
> > 324 flux=out_flux,
> > --> 325 uncertainty=new_unc)
> 
> That looks a bit odd, as if the installed library is not in sync with the one loaded in your session – have you tried to repeat this in a fresh ipython session?
> 
> Just to make sure, what do you get from
> 
> ```
> input_spectra.uncertainty
> input_spectra.uncertainty is None
> ```

I get nothing for the uncertainty i.e. it returns a blank line

**Comment by nmearl** [comment]
@amanpkaur Can you provide the versions of specutils and astropy you're currently using?

```bash
$ python -c "import specutils; print(specutils.__version__)"
$ python -c "import astropy; print(astropy.__version__)"
```

**Comment by amanpkaur** [comment]
> ```shell
> -c "import astropy; print(astropy.__version__)"
> ```

1.0 for specutils and 4.0.1.post1 for astropy. I use python 3.6 and replaced python by python3 in the above commands. I tried to check by adding uncertainties and I still have the same issue.

**Comment by dhomeier** [comment]
The uncertainty was just a wild guess since the traceback pointed to line 325, while the call to `return Spectrum1D` in 323 would be expected, but I guess that might just be offsets between the byte-compiled and original source files... But the exception is evidently raised on setting the `flux`.

Oh, what is your Scipy version?

**Comment by amanpkaur** [comment]
> The uncertainty was just a wild guess since the traceback pointed to line 325, while the call to `return Spectrum1D` in 323 would be expected, but I guess that might just be offsets between the byte-compiled and original source files... But the exception is evidently raised on setting the `flux`.
> 
> Oh, what is your Scipy version?

1.41

**Comment by dhomeier** [comment]
And the numpy version (sorry about the red herring, I thought this was using `scipy.interpolate`, but actually it is `numpy.interp`)?

**Comment by amanpkaur** [comment]
haha no problem.. 1.16.3 for numpy

**Comment by dhomeier** [comment]
> haha no problem.. 1.16.3 for numpy

Thanks, that was it - that version apparently cannot cope with units in `np.interp`.
I am looking into a fix on the `specutils` side, but for now you should be able to get set by upgrading to at least 1.17.

**Comment by amanpkaur** [comment]
> > haha no problem.. 1.16.3 for numpy
> 
> Thanks, that was it - that version apparently cannot cope with units in `np.interp`.
> I am looking into a fix on the `specutils` side, but for now you should be able to get set by upgrading to at least 1.17.

wow perfect! It worked after the upgrade. Thanks a lot for the help!

**Comment by dhomeier** [comment]
Thanks for the report and help with troubleshooting!
