### ISSUE TITLE
specutils should not globally set enabled equivalencies

### ISSUE THREAD

**Issue by astrofrog** [astropy/specutils#671]
Currently, importing specutils causes spectral equivalencies to be enabled by default for the rest of the Python session:

https://github.com/astropy/specutils/blob/ca093ea8757d17a728f1ee1adafc04bbeff083c4/specutils/spectra/spectrum1d.py#L18

This should be removed, and the equivalencies should only be enabled temporarily in the context where they are used (currently the astropy test suite breaks if specutils is installed because of this: https://github.com/astropy/astropy/issues/10283)

**Comment by nmearl** [comment]
Fixes in #673.
