### ISSUE TITLE
Fix asdf-related failures in development version of astropy tests

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#680]
This is a follow-on from #674, which introduced some failures on the astropy-dev tests from asdf.  There's some context with @astrofrog and @jdavies-st in https://github.com/astropy/specutils/pull/674#issuecomment-627319487, but perhaps @astrofrog can add a bit more here if there's more?

**Comment by astrofrog** [comment]
I'm not sure what the correct fix is, but just wanted to say that when Astropy 4.1 is available, we should make sure the ASDF serialization machinery for SpectralCoord in specutils doesn't have any effect since this should then be handled by astropy core.

**Comment by nmearl** [comment]
While that's true, I'm thinking that as long as we have a copy of the `SpectralCoord` class in specutils, we'll probably need the asdf schema files in specutils as well. I'm not sure if this absolutely true though?

**Comment by astrofrog** [comment]
Right - I mean more that if astropy 4.1 is installed, the specutils schemas for that class should not be used to serialize the astropy class (since the backports are only effective when astropy<4.1 is used)

**Comment by jdavies-st** [comment]
Is the tag the same for `SpectralCoord` serialization in astropy vs specutils?  If it is not, then the serialization machinery can be left in place in specutils as is, as it should not be used.

If the tag *is* the same, then that's a can of worms, as both package entry points extensions will provide competing serializations.  I think.

**Comment by astrofrog** [comment]
I'm not familiar enough with ASDF to know the answer to that :) But if we need to update the tag in astropy core, we should do this soon before the 4.1 release.

**Comment by pllim** [comment]
CI is green now. 🤷
