### ISSUE TITLE
The 1.0 release on pypi does not contain astropy_helpers

### ISSUE THREAD

**Issue by mwcraig** [astropy/specutils#682]
The source release of 1.0 on pypi does not contain `astropy_helpers`, which makes it difficult to build for conda. It isn't possible to replace the src package on pypi sso you would need to either do a post release or do a 1.x or 1.0.x release. I'm not sure *why* helpers wasn't included; the proper magic seems like it is there in `MANIFEST.in`.

**Comment by nmearl** [comment]
Thanks @mwcraig. Once 4.1 is released, we plan to update the packaging to the new tox-based approach which should remove the dependency entirely.

**Comment by mwcraig** [comment]
That will be awesome! I did get the conda package built, and it shouldn't be an issue with pip.

**Comment by rosteen** [comment]
@nmearl removed `astropy_helpers` and implemented the tox-based approach in #562 , closing this issue.
