### ISSUE TITLE
Cannot use the function "read_fits" from specutils.io

### ISSUE THREAD

**Issue by lkeitadk** [astropy/specutils#686]
Hello everyone,
I am trying to use the function read_fits from specutils to create Spectra1D objects from a fits file.
However, whenever I run the line "from specutils.io import read_fits", I get the following error:
"cannot import name 'read_fits' from 'specutils.io' (C:\Users\hp\anaconda3\lib\site-packages\specutils\io\__init__.py)"
To provide more context, I am using Python 3.7.7, and I installed it with Anaconda. 
The astropy version is v.4.0.1.post1 and the specutils version is 0.7 (both found using conda list).
Let me know if more information is needed.

Thank you !

**Comment by dhomeier** [comment]
1. By "Spectra1D" do you mean a `SpectrumList` or `SpectrumCollection` of several `Spectrum1D` objects, or do you want to load just a single `Spectrum1D`?

2. For the latter, in the simplest case `Spectrum1D.read('filename.fits')` will load your spectrum; for formats not automatically recognised you may need to specify more information or write your own loader as described in the [docs](https://specutils.readthedocs.io/en/latest/spectrum1d.html#reading-from-a-file).

3. There exists no 'read_fits' function in the current specutils version, where did you get the suggestion to use this?

**Comment by lkeitadk** [comment]
Hello @dhomeier , thank you for your response, it is much appreciated.
1. I meant to do exactly the latter. I apologize for the poor phrasing.
2. I have tried to make this work. However, I keep on running into this error:
"IORegistryError: Format could not be identified based on the file name or contents, please provide a 'format' argument."
3. I have found this suggestion in [this Astropy tutorial](https://specutils.readthedocs.io/en/doc-testing/specutils/read_fits.html) (in the section "Reading simple linear 1D WCS").

Thanks again!

**Comment by lkeitadk** [comment]
Actually, it seems that I was able to fix it. I added the argument "format = "wcs1d-fits" to the function call and it worked.
Thank you again for suggesting the function Spectrum1D.read().

**Comment by dhomeier** [comment]
Thanks for the feedback! We try to provide loaders for common spectral formats in FITS, but it's not always possible to detect the correct format automatically. But if you already know it is a WCS-based spectrum, you were already well on your way. Newer versions might even be able to auto-detect this, but for that you'd probably need to update to at least the 1.0 release or the Github version.

**Comment by nmearl** [comment]
Feel free to reopen this issue or open a new issue if you run into further problems, @lkeitadk! I also do want to point out that the docs you linked are _very_ outdated (from version 0.0), so the astropy tutorial is certainly no longer relevant. Please see the docs linked by @dhomeier.

**Comment by dhomeier** [comment]
@nmearl is `doc-testing` a tag for that archaic version? These issues from information found in outdated doc versions seem to pop up every now and then; but for a version _this_ old to pop up under an seemingly unconspicous url looks really problematic. Should really be removed or at least put behind some kind of warning firewall, at least for those docs we have any control over (of course if someone digs up an ancient recipe on stackoverflow, there is probably not much to be done about it).
