### ISSUE TITLE
Don't create `~/.specutils` if it doesn't exist

### ISSUE THREAD

**Issue by aragilar** [astropy/specutils#687]
It seems unnecessary to create `~/.specutils`, as is done in https://github.com/astropy/specutils/blob/master/specutils/io/registers.py#L150. The only reason to do this would be as a convenience to users, except:
1. As written, there's a race condition, the directory may not exist when the check is done, but the directory may be there when `os.mkdir` is called (throwing an exception at import time).
2. The creation of the directory may fail (in the case I came across, it was due to specutils being unable to write to the directory), hence crashing the process needlessly.

I'll send a PR on Friday changing the code to only import when the directory exists, I think it would be also worthwhile to add an environment variable to disable the homedir import entirely.

**Comment by nmearl** [comment]
See #330 for discussion happening on a similar issue.

>  there's a race condition, the directory may not exist when the check is done

Can you expand on this, I'm not quite seeing where the race condition lies.

**Comment by aragilar** [comment]
Say your homedir is on NFS, and you import specutils on two different systems, you can have both systems find that the directory does not exist, then both systems will try to create the directory, with one failing (you don't need NFS or two different systems to trigger this, but it'll be easier to trigger). The better way would be to try to make the directory and catch the exception, or use makedirs with exist_ok.

#330 seems to be focusing alternative systems, this is more to do with assuming that creating `~/.specutils` cannot fail.
