### ISSUE TITLE
Function `extract_region` fails with 3D data

### ISSUE THREAD

**Issue by ibusko** [astropy/specutils#690]
When applying `extraction_region` to a `Spectrum1D` instance which was defined with a 3D flux array, the resulting `Spectrum1D` instance is broken.

For example, submiting a Spectrum1D with shape (100, 100, 2500) (2500 being the spatial axis size)  to `extract_region`, results in a Spectrum1D with shape (0, 100, 2500).

This suggests that `extract_region` wasn't coded to handle 3D data. The same problem may be affecting other parts of `specutils`.

**Comment by gkanarek** [comment]
I've run into the same problem for 2D data. The docs on multidimensional `Spectrum1D` datasets says that the spectral axis should be the last, and it looks like `extract_region` is working either on the first axis or the flattened array.

<img width="1120" alt="Screen Shot 2020-10-09 at 9 38 02 AM" src="https://user-images.githubusercontent.com/19858800/95590918-aa6fa800-0a14-11eb-945c-7dfc721dbaf3.png">
