### ISSUE TITLE
Result from fit_lines drops names of compound model components

### ISSUE THREAD

**Issue by rosteen** [astropy/specutils#694]
As of ~May 7th, it was possible to use `specutils.fitting.fit_lines()` on an astropy `CompoundModel` with the `name` parameters set in its component models, then use those `name` values to index the resulting fitted model and retrieve the fitted parameters for the component models. Now, it looks like either the `fit_lines` function or the `QuantityModel` object itself is dropping the `name`s of the component models. This results in an error for previously working code:

`TypeError: 'QuantityModel' object is not subscriptable`

Some code to reproduce the error is below:

```
>>> import numpy as np
>>> import astropy.units as u
>>> from astropy.modeling import models
>>> from specutils.fitting import fit_lines
>>> from specutils.spectra import Spectrum1D

>>> flux = (np.random.randn(100)*10 + np.exp(-np.power(x - 40, 2.) / (2 * np.power(12, 2.))) * 100)*u.Jy
>>> wavelength = np.linspace(6000, 6198, 100)*u.AA
>>> spec = Spectrum1D(flux, wavelength)
>>> a = models.Const1D(amplitude=10, name="A")
>>> b = models.Gaussian1D(amplitude=30, mean=6060, stddev = 40, name="B")

>>> m=a+b
>>> output_model = fit_lines(spec, m)
>>> print(m)
Model: CompoundModel
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Expression: [0] + [1]
Components:
    [0]: <Const1D(amplitude=10., name='A')>

    [1]: <Gaussian1D(amplitude=30., mean=6060., stddev=40., name='B')>
Parameters:
    amplitude_0 amplitude_1 mean_1 stddev_1
    ----------- ----------- ------ --------
           10.0        30.0 6060.0     40.0

>>> print(output_model)
<QuantityModel CompoundModel(amplitude_0=0.93153264, amplitude_1=96.32878616, mean_1=6080.54416182, stddev_1=24.00109947), input_units=Angstrom, return_units=Jy>

>>> m["A"]
<Const1D(amplitude=10., name='A')>

>>> output_model["A"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'QuantityModel' object is not subscriptable
```

The specific context in which I'm affected by this error is using the model fitting tool implemented in [this PR](https://github.com/spacetelescope/jdaviz/pull/119) to fit any combination of 2 or more models. Also note that fitting a single model rather than a compound model preserves the `name` parameter in the output:

`<QuantityModel Const1D(amplitude=1.61789905, name='C'), input_units=m, return_units=1e-17 erg / (Angstrom cm2 s)>`

**Comment by nmearl** [comment]
`QuantityModel` was never subscriptable, so I'm not sure how it was working for you before?

You can however just access the underlying unitless compound model and subscript that.

<img width="878" alt="Screen Shot 2020-06-16 at 8 19 58 AM" src="https://user-images.githubusercontent.com/4141126/84773389-55fa7580-afaa-11ea-9bfa-68a66c989896.png">

**Comment by rosteen** [comment]
Well, I was already feeling crazy since there are obviously no recent commits that would have changed this, good to have confirmation that I'm just nuts. Thanks for the tip on grabbing the unitless model for subscripting purposes. Might be worth adding a note about that to the docs somewhere, but I'll go ahead and close this since it's expected behavior, not a bug.
