### ISSUE TITLE
Missing data for 2SLAQ-LRG

### ISSUE THREAD

**Issue by nmearl** [astropy/specutils#705]
The recent [tests are failing](https://travis-ci.org/github/astropy/specutils/jobs/711544252#L923) due to missing data for 2SLAQ-LRG loader tests. @aragilar can you point us to a new data set to use in place of the (apparently no longer existing) https://datacentral.org.au/services/sov/81480/download/gama.dr2.spectra.2slaq-lrg.spectrum_1d/J143529.78-004306.4_1.fit/ file?

**Comment by aragilar** [comment]
I've uploaded the file to https://zenodo.org/record/3970324, and will make a PR with the change.
