### ISSUE TITLE
Smoothing spectra drops meta information about spectra

### ISSUE THREAD

**Issue by aragilar** [astropy/specutils#709]
It appears https://github.com/astropy/specutils/blob/master/specutils/manipulation/smoothing.py#L97 does not pass the metadata on the spectra along, stripping it out. Was this intended, or should I make a PR fixing this.

**Comment by nmearl** [comment]
Hi @aragilar, this was not intentional, so please feel free to provide a PR that passes on the meta information!

**Comment by javerbukh** [comment]
Should this issue be closed? @nmearl @eteq
