### ISSUE TITLE
Can't set radial velocity of Spectrum1D object

### ISSUE THREAD

**Issue by AWehrhahn** [astropy/specutils#721]
Trying to set the radial velocity of a Spectrum1D object raises an Attribute error.
This happens only in specutils version 1.1, but not in version 1.0.

Error Message:
```
Exception has occurred: AttributeError
SpectralAxis instance has no attribute 'with_radial_velocity'
```

Minimal Code:
```
import numpy as np
from astropy import units as u
from specutils.spectra import Spectrum1D


wave = np.linspace(100, 200, 100) << u.AA
flux = np.ones(100) << u.one
spec = Spectrum1D(spectral_axis=wave, flux=flux, radial_velocity=0 * u.km / u.s)

spec.radial_velocity = 1 * u.km / u.s
```

**Comment by nmearl** [comment]
@AWehrhahn thanks for the bug report! Seems this was never cleaned up when we transitioned to using `SpectralAxis`. I will explore this and get back to you.
