### ISSUE TITLE
Update travis tests to have more descriptive test titles

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#727]
Hopefully this change is a matter of just porting over the most recent update of the `astropy/astropy` travis configuration... but right now the "details" on travis (see e.g. https://github.com/astropy/specutils/pull/726/checks?check_run_id=1293331774) are pretty inscrutable.  By contrast, PRs in astropy/astropy (see e.g. https://github.com/astropy/astropy/pull/10895/checks?check_run_id=1289669984 ) have meaningful job names that explain their purpose. This helps a lot when less-familiar contributors are trying to interpret CI failures.

**Comment by nmearl** [comment]
See https://github.com/astropy/specutils/pull/562 which we've been waiting on 4.1 to release to pull in.

**Comment by nmearl** [comment]
This should addressed with the #562 merge.
