### ISSUE TITLE
Can't get the Getting Started demo working

### ISSUE THREAD

**Issue by janerigby** [astropy/specutils#739]
I'm trying to run the Demo at https://specutils.readthedocs.io/en/stable/

And get this error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-3699f915aeed> in <module>()
      5 flux = specdata['flux'] * 10**-17 * u.Unit('erg cm-2 s-1 AA-1')
      6 
----> 7 spec = Spectrum1D(spectral_axis=lamb, flux=flux)
TypeError: __init__() takes at least 3 arguments (2 given)

I'm baffled.  I gave it the two arguments it asked for.

**Comment by nmearl** [comment]
Hi @janerigby. Can you provide the version of astropy and specutils that you have installed? You can run the following commands in your terminal:

```
$ python -c "import astropy; print(astropy.__version__)"
$ python -c "import specutils; print(specutils.__version__)"
```

And can you also provide what python you're using as well?

```
python --version
```

Thanks!

**Comment by janerigby** [comment]
I should be using the base stsci astroconda:
python -c "import astropy; print(astropy.__version__)"
2.0.16
 python -c "import specutils; print(specutils.__version__)"
0.2.2
python --version
Python 2.7.15
That's weird.  Why is it 2.7?

**Comment by janerigby** [comment]
I re-installed astroconda and it works now.  The problem was with astroconda, not specutils.
