### ISSUE TITLE
fit_generic_continuum() documentation does not explain argument median_window

### ISSUE THREAD

**Issue by janerigby** [astropy/specutils#742]
I'm trying to get fit_generic_continuum() to fit a continuum. The fit is terrible, and I'm wondering if the problem is the median_window argument. But, the documentation does not explain what that argument is, what its units are (Angstroms?  pixels), or what changing it is likely to do.

**Comment by nmearl** [comment]
Thanks for the report. `median_smooth` is used in the median filter smoothing function which is performed on the spectrum prior to attempting to fit a continuum. Internally, it uses [scipy's `medfilt` function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.medfilt.html). The `median_window` is the same as the `kernal_size` used in the median filter function.
