### ISSUE TITLE
Implement NDCube handling for Spectrum1D/SpectrumCollection

### ISSUE THREAD

**Issue by rosteen** [astropy/specutils#743]
As part of transitioning the [spectral-cube](https://github.com/radio-astro-tools/spectral-cube) functionality into `specutils`, a decision needs to be made (and implemented) on how to handle `NDCube` compatibility. Some experimentation in this direction can be found [here](https://github.com/astrofrog/nddata-experiments). 

An ideal path might be to subclass `NDCube` rather than `NDDataRef` for `Spectrum1D` and `SpectrumCollection` so that we can make use of nice features that `NDCube` has, rather than just handling ingesting `NDCube` objects. However, this introduces an internal dependency to `sunpy` that comes along with `NDCube`, and some organizational oddity in that we'd have a class in our astropy-affiliated package that depends on a non-astropy-affiliated subclass of an astropy data structure. I don't think either of those things are big deals/dealbreakers on going down this path, but we should at least think about them and make a conscious decision.

**Comment by eteq** [comment]
As a possible starting point for experimentation, one can imagine using `NDCube` as a convenience for producing a moment map.  The way this would work would be to use NDCube's functionality to determine which is the spectral axis, and have a `make_moment_map(spectrum)` that uses that information automatically to yield an appropriate 2d moment map (i.e. ``sum_along_spectral_axis((spectral_axis**moment)*flux)/sum(flux)`` ).  This could be done with `specutils` on its own, but the idea would be that `NDCube` could offer things like convenient indexing along the spectral axis a la `make_moment_map(spectrum[6500*u.angstrom:6600*u.angstrom])` .
