### ISSUE TITLE
Output of fit_lines_derivative() is the wrong format to feed to the exclude_regions() paramter of fit_continuum_generic()

### ISSUE THREAD

**Issue by janerigby** [astropy/specutils#749]
The specutils function fit_continuum_generic() will be fooled by strong emission lines.  A common use case is to mask those emission lines before fitting the continuum.  However, the output of find_lines_derivative() is the wrong format to be readable by the exclude_regions() parameter of fit_continuum_generic(), and there appears to be no conversion tool. 

A real-world example of this issue:  https://github.com/janerigby/NB/blob/master/spectutils_testdrive.ipynb

Here is the conversion function I made to get around it.  Spectools needs the functionality of converting its output linelists to SpectralRegions -- it's going to be a common concern.

```
def convert_lines_to_spectralregions(linelist, window=10., unit=u.AA) :
    temp =  [((x - window) * u.AA, (x + window)* u.AA)  for x in linelist['line_center'].value] # must be Quantities
    return (SpectralRegion(temp))
```

**Comment by jdavies-st** [comment]
This issue was resolved by #759 and can be closed.  See

https://specutils.readthedocs.io/en/stable/spectral_regions.html#line-list-compatibility

and 

https://specutils.readthedocs.io/en/stable/api/specutils.SpectralRegion.html#specutils.SpectralRegion.from_line_list
