### ISSUE TITLE
Continuum fitting "window"

### ISSUE THREAD

**Issue by rbaer25** [astropy/specutils#771]
Release 1.1.1, page 125,  Release 1.1 page 127

fitted_continuum = fit_continuum(spectrum, window=region)

results in

window and weights are not yet implemented

is there a work around?

**Comment by emigardiner** [comment]
I have the same question!

**Comment by rbaer25** [comment]
In the meantime I found a work around

fitted_continuum = fit_continuum(spectrum,exclude_regions=[SpectralRegion(excl_min*u.AA, excl_max*u.AA)])

with excl_min and excl_max being the lower and upper bound of the excluded region.
I am also looking for solutions to do power law and black body fitting.
