### ISSUE TITLE
SpectralRegion requires frequencies to be in descending order

### ISSUE THREAD

**Issue by PatrickOgle** [astropy/specutils#796]
As mentioned in a previous github issue:
[https://github.com/astropy/specutils/issues/615](#615)

The order of arguments in Spectral region shouldn't matter.  However, it still does and gives an
error for this example:

noise_region = SpectralRegion(531.*u.GHz, 559.*u.GHz)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-8c6a1914651a> in <module>
      3 
      4 #noise_region = SpectralRegion(559.*u.GHz, 531.*u.GHz)
----> 5 noise_region = SpectralRegion(531.*u.GHz, 559.*u.GHz)
      6 #noise_region2 = SpectralRegion(531.*u.um, 559.*u.um)
      7 

~/miniconda3/envs/science/lib/python3.8/site-packages/specutils/spectra/spectral_region.py in __init__(self, *args)
     76         #  Check validity of the input sub regions.
     77         #
---> 78         if not self._valid():
     79             raise ValueError('SpectralRegion 2-tuple lower extent must be less than upper extent.')
     80 

~/miniconda3/envs/science/lib/python3.8/site-packages/specutils/spectra/spectral_region.py in _valid(self)
    165 
    166         if any(x[0] >= x[1] for x in sub_regions):
--> 167             raise ValueError('Lower bound must be strictly less than the upper bound')
    168 
    169         return True

ValueError: Lower bound must be strictly less than the upper bound

This is very confusing as data in frequency units are typically in ascending order.
Recommend adding code so that the order of the arguments in SpectralRegion doesn't matter.

**Comment by EfremBraun** [comment]
Agreed. I'm using energy units, and it's extremely odd having to reverse all my spectral data before forming the Spectrum1D object.
