### ISSUE TITLE
Catch the JWSTExtension AsdfWarning in the jwst loaders

### ISSUE THREAD

**Issue by jdavies-st** [astropy/specutils#804]
If the `jwst` package is not installed, the JWST loaders emit the following warning when loading the files as `asdf` to read some of the metadata and WCS info:

```
./site-packages/asdf/asdf.py:193: AsdfWarning: File 'NRS00001-faintQSO-F100LP-G140H-01_1_491_SE_2020-08-25T12h15m00_s3d.fits' was created with extension 'jwst.transforms.jwextension.JWSTExtension', which is not currently installed (from package jwst-0.16.3.dev88+gd82efc89)
  warnings.warn(fmt_msg, AsdfWarning)
```

This warning is not important for the `specutils` user, as by design, the loaders are intended to work without `jwst` package being installed.

These specific warnings should be captured so the user does not see them.

**Comment by pllim** [comment]
Data models are now in `stdatamodels`, so this issue is no longer relevant.
