### ISSUE TITLE
Update ndcube dependency to a released version

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#808]
#754 introduced a dependency on NDCube. It requires some features that are currently in a developer version, though, and the `install_requires` in `setup.cfg` is set to reflect that. Before the next `specutils` release we should be sure this requirement is set to a "real" `NDCube` version. (My understanding is @Cadair plans a release sometime in the next few weeks, so it's not a serious issue, just something we have to remember to update prior to a 1.3 release.

**Comment by dhomeier** [comment]
https://pypi.org/project/ndcube/2.0.0rc1/

**Comment by rosteen** [comment]
Awesome, I'll try to do some testing with that on Monday.

**Comment by dhomeier** [comment]
Tested 1.3.dev92+g1f6eded with astropy 4.2 +  4.3rc1

**Comment by rosteen** [comment]
Done!
