### ISSUE TITLE
Work with energy as spectral axis

### ISSUE THREAD

**Issue by dagnic** [astropy/specutils#814]
Hi

I would like to define a spectrum in the form of counts versus energy, as it is commonly used for X-ray instruments. 

However, the following example does not work: `sub_spectrum` is exactly the same as `spectrum`. Also, I have to reverse the bounds in decreasing energy to be able to call `SpectralRegion`.

    from specutils import Spectrum1D, SpectralRegion
    from specutils.manipulation import extract_region
    import astropy.units as u
    import numpy as np

    ydata = np.random.rand(10)
    xdata = np.linspace(1,10,10)

    spectrum = Spectrum1D(flux=ydata*u.count, spectral_axis=xdata*u.keV)
    sub_region = SpectralRegion(7*u.keV, 4*u.keV)
    sub_spectrum = extract_region(spectrum, sub_region)

It follows the last message from @DanRyanIrish after the issue was closes (https://github.com/astropy/specutils/issues/615).

I am using specutils=1.2 from conda-forge. 

Thanks.

**Comment by nmearl** [comment]
I certainly think we should add something to give the user some feedback, but in this case, you should be able to get this to work as expected by defining your `xdata` in descending order:

```python
In [1]: from specutils import Spectrum1D, SpectralRegion
   ...: from specutils.manipulation import extract_region
   ...: import astropy.units as u
   ...: import numpy as np

In [2]: ydata = np.random.rand(10)
   ...: xdata = np.linspace(10, 1, 10)  # Note that it's in descending order

In [3]: spectrum = Spectrum1D(flux=ydata*u.count, spectral_axis=xdata*u.keV)
   ...: sub_region = SpectralRegion(7*u.keV, 4*u.keV)
   ...: sub_spectrum = extract_region(spectrum, sub_region)

In [4]: sub_spectrum
Out[4]: <Spectrum1D(flux=<Quantity [0.5189312 , 0.17643062, 0.84891002, 0.24742911] ct>, spectral_axis=<SpectralAxis [7., 6., 5., 4.] keV>)>
```

**Comment by dagnic** [comment]
Thanks for you fast answer. I suppose that we have also to reverse the order in the ydata.  Doing so it works.
