### ISSUE TITLE
Tests against development astropy seem to be failing due to some new unit handling

### ISSUE THREAD

**Issue by aragilar** [astropy/specutils#826]
https://github.com/astropy/specutils/runs/2775139306 is an example (latest main when I posted this).

The failures seem mostly to be in `test_tabular_fits_multid` and `test_tabular_fits_writer` with `assert Unit("W / (Angstrom m2)") == Unit("erg / (Angstrom cm2 s)")` (which is true, they are not equal to a factor of 1000). I'm wondering if something has changed with astropy's unit handling (I know I did some work on unit aliases, which could be the problem). It may be worth flagging with astropy (I haven't had a detailed look, I noticed it when working on #757).

**Comment by dhomeier** [comment]
See #831, sorry I missed this when I filed it.
