### ISSUE TITLE
TST: Do not skip valid doctest examples

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#849]
For example, I see you download real data in `docs/spectral_cube.rst` but then you skip testing actually using the object generated by the data.

```python
>>> sc.shape #doctest:+SKIP
(74, 74, 4563)
```

Why not just run the whole example with doctest?

**Comment by dhomeier** [comment]
I agree checking the shape should be feasible at a minimum.
For the actual content might be tricky to set up the `+FLOAT_CMP` etc. the right way, but I think there are some examples of this in the docs.
