### ISSUE TITLE
Some methods appearing as attributes in API docs

### ISSUE THREAD

**Issue by rosteen** [astropy/specutils#867]
See e.g. https://specutils.readthedocs.io/en/stable/api/specutils.Spectrum1D.html#specutils.Spectrum1D, where the read and write methods (and others?) are listed under the Attributes section.

**Comment by nmearl** [comment]
This is expect as the [`NDIOMixin` uses attributes](https://docs.astropy.org/en/stable/_modules/astropy/nddata/mixins/ndio.html#NDIOMixin) to attach the functionality to the inheriting class.

**Comment by rosteen** [comment]
Pretend I posted a "the more you know" gif here. I guess we can close this then.

**Comment by pllim** [comment]
Thanks for the clarifications!
