### ISSUE TITLE
Can´t load 1D spectrum in ASCII format

### ISSUE THREAD

**Issue by jortiz12** [astropy/specutils#880]
Dear Community, 
I´ve a 2-column 1D spectrum in ASCII format taht can´t loadwith the code
`file_path = os.path.join('estrellasdeprueba_2122', 'estrella1.dat')`
`spec = Spectrum1D.read(file_path, format='ASCII')`
Error message is the following:
`OSError: Could not identify column containing the wavelength, frequency or energy`
This is a snapshot of the spectrum (in a xxx.dat file)
![imagen](https://user-images.githubusercontent.com/2719866/136777084-801efaef-215c-4042-87d9-76a4cb965e47.png)
Any advice would be much appreciated

**Comment by keflavich** [comment]
It looks like you could do something like this:
```python
from astropy import units as u
wavelength, flux = np.loadtxt(file_path)
flux_units = u.Jy # specify the correct units here
spec = Spectrum1D(wavelength=wavelength*u.AA, flux=flux*flux_units)
```
based on https://specutils.readthedocs.io/en/stable/spectrum1d.html#basic-spectrum-creation.
