### ISSUE TITLE
Spectrum1D.with_spectral_unit does not change spectral unit and overwrites WCS

### ISSUE THREAD

**Issue by kecnry** [astropy/specutils#889]
`Spectrum1D.with_spectral_unit` seems create a copy of the `Spectrum1D` object with meta-data storing the original unit and with a newly created WCS from the original `spectral_axis` (so would overwrite any original WCS if it had been provided), but does not actually change units.

```
import specutils
import astropy.units as u

sp = specutils.Spectrum1D(spectral_axis=[0,1,2,3]*u.cm, flux=[0.1, 0.2, 0.3, 0.4]*u.erg/u.AA/u.cm**2/u.s)

sp.spectral_axis.unit
# Angstroms

sp.wcs.unit
# Angstroms

sp_wsu = sp.with_spectral_unit(u.um)

sp_wsu.spectral_axis.unit
# Angstroms

sp_wsu.wcs.unit
# Angstroms
```

**Comment by rosteen** [comment]
Closed by #1119
