### ISSUE TITLE
TST: Remove xfail conditions in test_template_comparison.py and fix the tests

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#928]
Someone familiar with template thingies need to fix these:

https://github.com/astropy/specutils/blob/9a5bf9368586b420549c70e8279f31e93e567ad9/specutils/tests/test_template_comparison.py#L38-L41

https://github.com/astropy/specutils/blob/9a5bf9368586b420549c70e8279f31e93e567ad9/specutils/tests/test_template_comparison.py#L73-L76

**Comment by rosteen** [comment]
I fixed this in #1121, closing.
