### ISSUE TITLE
Revisit PR 912 that got reverted (moment transpose for order > 1)

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#931]
Original problem:

* spacetelescope/jdaviz#947

Original fix:

* #912 (reverted by #929 and never released)
    * This patches code added in #781

Simple test case presented at https://github.com/astropy/specutils/pull/929#issuecomment-1043739843 did not convince @eteq , @rosteen , and myself that it is worth the risk being in a release without a better test case. @eteq proposed a following test case:

1. Create 12 Gaussian1D models with known sigma.
2. Pack them into a spectral cube that is 3 x 4 in spatial, uh, space.
3. Run moment calculations on the cube.
4. Do the results agree with theoretical values with and without #912?

Related issues:

* #930 
* #925

**Comment by javerbukh** [comment]
When you say "create 12 Gaussian 1D models", do you have a code example of how to do that?  And do they all have to be different models? @pllim
