### ISSUE TITLE
Spectrum1D  is reading the file but not able to plot on matplotlib

### ISSUE THREAD

**Issue by astrohitc** [astropy/specutils#950]
I am trying to plot a 1d spectrum using specutils. Spectrum1D.read is reading the file but when I use plt.plot(spec.wavelength, spec.flux), 
it is giving an error saying 

"x and y must have same first dimension, but have shapes (27001,) and (3, 27001)"

Can anyone please help on how to solve this issue?

Thanks

**Comment by pllim** [comment]
Do you know why your flux has shape of `(3, 27001)`?

**Comment by pllim** [comment]
No reply, so closing.
