### ISSUE TITLE
Is it possible to write out 3D Spectrum1D and have it roundtrip?

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#951]
Consider a file like this:

```
Filename: allcube_ch1-2-3-4-shortlongmedium-s3d.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     243   ()      
  1  SCI           1 ImageHDU        61   (93, 75, 9099)   float32   
  2  ERR           1 ImageHDU        12   (93, 75, 9099)   float32   
  3  DQ            1 ImageHDU        12   (93, 75, 9099)   int32 (rescales to uint32)   
  4  WMAP          1 ImageHDU        10   (93, 75, 9099)   float32   
  5  WCS-TABLE     1 BinTableHDU     14   1R x 1C   [9099E]   
  6  HDRTAB        1 BinTableHDU    816   48R x 403C   [23A, 24A, D, ..., D]   
  7  ASDF          1 BinTableHDU     11   1R x 1C   [143088B]
```

1. Read in the SCI data into a 3D `Spectrum1D` object.
2. Have that object write it back out with its `myspec3d.write('out.fits')` method.
    * Also see #952

The output file will look like this:

```
Filename: out.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1                1 BinTableHDU     15   9099R x 2C   [D, 6975E]
```

I was hoping for something like this... is it possible? Should it be possible?

```
Filename: out.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()     
  1  SCI           1 ImageHDU        61   (93, 75, 9099)   float32   
  2  WCS-TABLE     1 BinTableHDU     14   1R x 1C   [9099E]
  ...
```

**Comment by pllim** [comment]
The answer is currently no. Also see:

* #592 
* #1009

**Comment by dhomeier** [comment]
I assume the `WCS-TABLE` HDU in this case is supposed to hold any general [g]WCS? Yes; then I think currently (or with #1009) only WCS that can be represented in the header of the same HDU are supported. Although I left some points for discussion about writing identical WCS to each `ERR`, `DQ` etc. header; one could discuss a convention to store the WCS separately in its own HDU.
