### ISSUE TITLE
Implement Error Propagation for all Fitters

### ISSUE THREAD

**Issue by orifox** [astropy/specutils#959]
Right now, LMFitter gives you error propagation, but similar results are not returned for the other fitters, which may have more complicated calculations. Error propagation should be considered in these cases (i.e., linear fitters).

**Comment by rosteen** [comment]
@orifox I'm not sure that there's anything to do here, other than improve documentation on how to get the errors out. The default fitter now returns the errors, and the user is free to set `calc_uncertainties=True` in any other Astropy fitter they provide to `fit_lines` instead of the default.

**Comment by rosteen** [comment]
Closing, this was possible but needed to be documented, which is done.
