### ISSUE TITLE
Increase number of fit iterations in 'fit_lines'

### ISSUE THREAD

**Issue by wendeborn8** [astropy/specutils#966]
I am trying to fit some multi-component spectral lines with unrestricted `Gaussian1D` models, but the fit sometimes does not converge.

In some cases (like the image below), the fit seems perfectly fine: each component contributes to the total flux as I would expect and the resulting parameters are all reasonable.
![image](https://user-images.githubusercontent.com/31413424/179613771-a4f9deee-917d-46f6-af90-b25ef9d78766.png)

Then there are cases (like below) where the fit not only visually fails, but a warning (`WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]`) is thrown, indicating a poor fit (right?).
![image](https://user-images.githubusercontent.com/31413424/179613894-60471884-8187-4cad-a1cd-94e7a832fe03.png)

I see nothing intrinsically 'wrong' with these spectra; the poorly-fitting ones are hardly different than the well-fitting ones, yet the fit does not converge. My guess is that the fit isn't converging due to too few fit attempts, and it simply needs to run longer to converge, but `LevMarLSQFitter` and/or `scipy.optimize.leastsq` simply isn't running long enough. Is there a way to lengthen the number of iterations that `fit_lines` attempts? If not, that would be a useful feature.

**Comment by PauCaBu** [comment]
Hi, I have the same problem :(. I also have tried to recover what the fit_info['message'] prints, but I haven't been able to print it correctly, so I don't know what it says to be 'wrong'....

**Comment by rosteen** [comment]
I know this issue is old, but in the interest of having an answer here for posterity, the `fit_lines` function passes any extra keyword arguments that it doesn't use on to the fitter. At least the default fitter (and probably most astropy fitters) has `max_iter` argument, so if you define a `max_iter` in `fit_lines` it will be passed on to the `LevMarLSQFitter`.
