### ISSUE TITLE
snr_threshold assumes that uncertainty is represented as a standard deviation

### ISSUE THREAD

**Issue by mhallum** [astropy/specutils#983]
The snr_threshold function calculates SNR by dividing the flux by "spectrum.uncertainty.quantity". This assumes that the uncertainty is of type StdDevUncertainty. In some cases, if it is of type InverseVariance for example, this would yield an incorrect SNR. Changing "spectrum.uncertainty.quantity" to "spectrum.uncertainty.represent_as(StdDevUncertainty).quantity" and including "from astropy.nddata import StdDevUncertainty" in the imports should fix it.

**Comment by mhallum** [comment]
After looking into the code some more, I see that this is the case for many functions. I suggest that a note be added to the documentation explaining that if the uncertainty is represented as something other than the standard deviation some built-in spectuils functions will not yield the correct results.

**Comment by rosteen** [comment]
Thanks for bringing this up. There's been some recent work that has fixed this in some places (e.g. `centroid` in analysis), but it seems a couple still remain without the conversion to `StdDevUncertainty`. I'll try to get a fix out for this soon.
